/* <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk */
/* The typed API of every curated type path (cuo:modding/components: no JSON). See the
 * "typed components" section of cuo.h for how to use it. */
#ifndef CUO_TYPED_H
#define CUO_TYPED_H

#ifdef __cplusplus
extern "C" {
#endif

/* `cuo:player/hits` */
const cuo_Hits *cuo_Hits_column(cuo_query q, size_t term);
const cuo_Hits *cuo_Hits_obs_typed(const cuo_obs *ev);

/* `cuo:player/mana` */
const cuo_Mana *cuo_Mana_column(cuo_query q, size_t term);
const cuo_Mana *cuo_Mana_obs_typed(const cuo_obs *ev);

/* `cuo:player/stamina` */
const cuo_Stamina *cuo_Stamina_column(cuo_query q, size_t term);
const cuo_Stamina *cuo_Stamina_obs_typed(const cuo_obs *ev);

/* `cuo:player/data` */
const cuo_PlayerData *cuo_PlayerData_column(cuo_query q, size_t term);
const cuo_PlayerData *cuo_PlayerData_obs_typed(const cuo_obs *ev);

/* `cuo:ent/serial` */
const cuo_NetworkSerial *cuo_NetworkSerial_column(cuo_query q, size_t term);
const cuo_NetworkSerial *cuo_NetworkSerial_obs_typed(const cuo_obs *ev);

/* `cuo:ent/graphic` */
cuo_comp cuo_Graphic_typed(const cuo_Graphic *v);
const cuo_Graphic *cuo_Graphic_column(cuo_query q, size_t term);
void cuo_Graphic_set(cuo_query q, cuo_entity e, size_t term, const cuo_Graphic *v);
const cuo_Graphic *cuo_Graphic_obs_typed(const cuo_obs *ev);

/* `cuo:ent/hue` */
cuo_comp cuo_Hue_typed(const cuo_Hue *v);
const cuo_Hue *cuo_Hue_column(cuo_query q, size_t term);
void cuo_Hue_set(cuo_query q, cuo_entity e, size_t term, const cuo_Hue *v);
const cuo_Hue *cuo_Hue_obs_typed(const cuo_obs *ev);

/* `cuo:ent/world-position` */
cuo_comp cuo_WorldPosition_typed(const cuo_WorldPosition *v);
const cuo_WorldPosition *cuo_WorldPosition_column(cuo_query q, size_t term);
void cuo_WorldPosition_set(cuo_query q, cuo_entity e, size_t term, const cuo_WorldPosition *v);
const cuo_WorldPosition *cuo_WorldPosition_obs_typed(const cuo_obs *ev);

/* `cuo:ent/notoriety` */
cuo_comp cuo_Notoriety_typed(const cuo_Notoriety *v);
const cuo_Notoriety *cuo_Notoriety_column(cuo_query q, size_t term);
void cuo_Notoriety_set(cuo_query q, cuo_entity e, size_t term, const cuo_Notoriety *v);
const cuo_Notoriety *cuo_Notoriety_obs_typed(const cuo_obs *ev);

/* `cuo:ent/name` */
cuo_comp cuo_EntityName_typed(const cuo_EntityName *v);
const cuo_EntityName *cuo_EntityName_column(cuo_query q, size_t term);
void cuo_EntityName_set(cuo_query q, cuo_entity e, size_t term, const cuo_EntityName *v);
const cuo_EntityName *cuo_EntityName_obs_typed(const cuo_obs *ev);

/* `cuo:ent/amount` */
cuo_comp cuo_Amount_typed(const cuo_Amount *v);
const cuo_Amount *cuo_Amount_column(cuo_query q, size_t term);
void cuo_Amount_set(cuo_query q, cuo_entity e, size_t term, const cuo_Amount *v);
const cuo_Amount *cuo_Amount_obs_typed(const cuo_obs *ev);

/* `cuo:ui/node` */
cuo_comp cuo_Node_typed(const cuo_Node *v);
const cuo_Node *cuo_Node_column(cuo_query q, size_t term);
void cuo_Node_set(cuo_query q, cuo_entity e, size_t term, const cuo_Node *v);
const cuo_Node *cuo_Node_obs_typed(const cuo_obs *ev);

/* `cuo:ui/text` */
cuo_comp cuo_Text_typed(const cuo_Text *v);
const cuo_Text *cuo_Text_column(cuo_query q, size_t term);
void cuo_Text_set(cuo_query q, cuo_entity e, size_t term, const cuo_Text *v);
const cuo_Text *cuo_Text_obs_typed(const cuo_obs *ev);

/* `cuo:ui/text-font` */
cuo_comp cuo_TextFont_typed(const cuo_TextFont *v);
const cuo_TextFont *cuo_TextFont_column(cuo_query q, size_t term);
void cuo_TextFont_set(cuo_query q, cuo_entity e, size_t term, const cuo_TextFont *v);
const cuo_TextFont *cuo_TextFont_obs_typed(const cuo_obs *ev);

/* `cuo:ui/text-color` */
cuo_comp cuo_TextColor_typed(const cuo_TextColor *v);
const cuo_TextColor *cuo_TextColor_column(cuo_query q, size_t term);
void cuo_TextColor_set(cuo_query q, cuo_entity e, size_t term, const cuo_TextColor *v);
const cuo_TextColor *cuo_TextColor_obs_typed(const cuo_obs *ev);

/* `cuo:ui/bg-color` */
cuo_comp cuo_BackgroundColor_typed(const cuo_BackgroundColor *v);
const cuo_BackgroundColor *cuo_BackgroundColor_column(cuo_query q, size_t term);
void cuo_BackgroundColor_set(cuo_query q, cuo_entity e, size_t term, const cuo_BackgroundColor *v);
const cuo_BackgroundColor *cuo_BackgroundColor_obs_typed(const cuo_obs *ev);

/* `cuo:ui/border-radius` */
cuo_comp cuo_BorderRadius_typed(const cuo_BorderRadius *v);
const cuo_BorderRadius *cuo_BorderRadius_column(cuo_query q, size_t term);
void cuo_BorderRadius_set(cuo_query q, cuo_entity e, size_t term, const cuo_BorderRadius *v);
const cuo_BorderRadius *cuo_BorderRadius_obs_typed(const cuo_obs *ev);

/* `cuo:ecs/child-of` */
cuo_comp cuo_ChildOfDto_typed(const cuo_ChildOfDto *v);
const cuo_ChildOfDto *cuo_ChildOfDto_column(cuo_query q, size_t term);
void cuo_ChildOfDto_set(cuo_query q, cuo_entity e, size_t term, const cuo_ChildOfDto *v);
const cuo_ChildOfDto *cuo_ChildOfDto_obs_typed(const cuo_obs *ev);

/* `cuo:ui/movable` */
cuo_comp cuo_UiMovable_typed(void);

/* `cuo:ui/no-window-drag` */
cuo_comp cuo_UiNoWindowDrag_typed(void);

/* `cuo:ui/global-z` */
cuo_comp cuo_GlobalZIndex_typed(const cuo_GlobalZIndex *v);
const cuo_GlobalZIndex *cuo_GlobalZIndex_column(cuo_query q, size_t term);
void cuo_GlobalZIndex_set(cuo_query q, cuo_entity e, size_t term, const cuo_GlobalZIndex *v);
const cuo_GlobalZIndex *cuo_GlobalZIndex_obs_typed(const cuo_obs *ev);

/* `cuo:ui/interaction` */
cuo_comp cuo_InteractionDto_typed(const cuo_InteractionDto *v);
const cuo_InteractionDto *cuo_InteractionDto_column(cuo_query q, size_t term);
void cuo_InteractionDto_set(cuo_query q, cuo_entity e, size_t term, const cuo_InteractionDto *v);
const cuo_InteractionDto *cuo_InteractionDto_obs_typed(const cuo_obs *ev);

/* `cuo:input/mouse` */
bool cuo_MouseInputDto_res(const cuo_input *in, cuo_param p, cuo_MouseInputDto *out);
bool cuo_MouseInputDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_MouseInputDto *out);

/* `cuo:input/keyboard` */
bool cuo_KeyboardInputDto_res(const cuo_input *in, cuo_param p, cuo_KeyboardInputDto *out);
bool cuo_KeyboardInputDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_KeyboardInputDto *out);

/* `cuo:chat/message` */
void cuo_ModChatMessage_send(cuo_cmds *c, const cuo_ModChatMessage *v);
const cuo_ModChatMessage *cuo_ModChatMessage_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ModChatMessage *cuo_ModChatMessage_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ModChatMessage *cuo_ModChatMessage_obs_typed(const cuo_obs *ev);

/* `cuo:chat/prompt` */
void cuo_PromptOpenedEvent_send(cuo_cmds *c, const cuo_PromptOpenedEvent *v);
const cuo_PromptOpenedEvent *cuo_PromptOpenedEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_PromptOpenedEvent *cuo_PromptOpenedEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_PromptOpenedEvent *cuo_PromptOpenedEvent_obs_typed(const cuo_obs *ev);

/* `cuo:engine/time` */
bool cuo_Time_res(const cuo_input *in, cuo_param p, cuo_Time *out);
bool cuo_Time_obs_res(const cuo_obs *ev, cuo_param p, cuo_Time *out);

/* `cuo:ent/auto-opened-corpse` */

/* `cuo:ent/contained-into` */

/* `cuo:ent/equipment` */
const cuo_EquipmentSlotsDto *cuo_EquipmentSlotsDto_column(cuo_query q, size_t term);
const cuo_EquipmentSlotsDto *cuo_EquipmentSlotsDto_obs_typed(const cuo_obs *ev);

/* `cuo:ent/facing` */
cuo_comp cuo_Facing_typed(const cuo_Facing *v);
const cuo_Facing *cuo_Facing_column(cuo_query q, size_t term);
void cuo_Facing_set(cuo_query q, cuo_entity e, size_t term, const cuo_Facing *v);
const cuo_Facing *cuo_Facing_obs_typed(const cuo_obs *ev);

/* `cuo:ent/is-container` */

/* `cuo:ent/is-item` */

/* `cuo:ent/is-mobile` */

/* `cuo:ent/manual-opened-corpse` */

/* `cuo:ent/properties` */
const cuo_EntityPropertiesDto *cuo_EntityPropertiesDto_column(cuo_query q, size_t term);
const cuo_EntityPropertiesDto *cuo_EntityPropertiesDto_obs_typed(const cuo_obs *ev);

/* `cuo:ent/server-flags` */
const cuo_ServerFlags *cuo_ServerFlags_column(cuo_query q, size_t term);
const cuo_ServerFlags *cuo_ServerFlags_obs_typed(const cuo_obs *ev);

/* `cuo:ent/slot-position` */
cuo_comp cuo_ContainerSlotPosition_typed(const cuo_ContainerSlotPosition *v);
const cuo_ContainerSlotPosition *cuo_ContainerSlotPosition_column(cuo_query q, size_t term);
void cuo_ContainerSlotPosition_set(cuo_query q, cuo_entity e, size_t term, const cuo_ContainerSlotPosition *v);
const cuo_ContainerSlotPosition *cuo_ContainerSlotPosition_obs_typed(const cuo_obs *ev);

/* `cuo:game/context` */
bool cuo_GameContextDto_res(const cuo_input *in, cuo_param p, cuo_GameContextDto *out);
bool cuo_GameContextDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_GameContextDto *out);

/* `cuo:game/settings` */
bool cuo_GameSettingsDto_res(const cuo_input *in, cuo_param p, cuo_GameSettingsDto *out);
bool cuo_GameSettingsDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_GameSettingsDto *out);

/* `cuo:game/state` */
bool cuo_GameStateDto_res(const cuo_input *in, cuo_param p, cuo_GameStateDto *out);
bool cuo_GameStateDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_GameStateDto *out);

/* `cuo:gump/container` */
cuo_comp cuo_ContainerWindow_typed(const cuo_ContainerWindow *v);
const cuo_ContainerWindow *cuo_ContainerWindow_column(cuo_query q, size_t term);
void cuo_ContainerWindow_set(cuo_query q, cuo_entity e, size_t term, const cuo_ContainerWindow *v);
const cuo_ContainerWindow *cuo_ContainerWindow_obs_typed(const cuo_obs *ev);

/* `cuo:gump/container-closed` */
void cuo_ContainerClosedEvent_send(cuo_cmds *c, const cuo_ContainerClosedEvent *v);
const cuo_ContainerClosedEvent *cuo_ContainerClosedEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ContainerClosedEvent *cuo_ContainerClosedEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ContainerClosedEvent *cuo_ContainerClosedEvent_obs_typed(const cuo_obs *ev);

/* `cuo:gump/container-opened` */
void cuo_ContainerOpenedEvent_send(cuo_cmds *c, const cuo_ContainerOpenedEvent *v);
const cuo_ContainerOpenedEvent *cuo_ContainerOpenedEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ContainerOpenedEvent *cuo_ContainerOpenedEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ContainerOpenedEvent *cuo_ContainerOpenedEvent_obs_typed(const cuo_obs *ev);

/* `cuo:gump/container-positions` */
bool cuo_ContainerPositionsDto_res(const cuo_input *in, cuo_param p, cuo_ContainerPositionsDto *out);
bool cuo_ContainerPositionsDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_ContainerPositionsDto *out);

/* `cuo:gump/container-slot` */
void cuo_ContainerSlotEvent_send(cuo_cmds *c, const cuo_ContainerSlotEvent *v);
const cuo_ContainerSlotEvent *cuo_ContainerSlotEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ContainerSlotEvent *cuo_ContainerSlotEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ContainerSlotEvent *cuo_ContainerSlotEvent_obs_typed(const cuo_obs *ev);

/* `cuo:gump/container-tag` */
cuo_comp cuo_ContainerGumpTagDto_typed(const cuo_ContainerGumpTagDto *v);
const cuo_ContainerGumpTagDto *cuo_ContainerGumpTagDto_column(cuo_query q, size_t term);
void cuo_ContainerGumpTagDto_set(cuo_query q, cuo_entity e, size_t term, const cuo_ContainerGumpTagDto *v);
const cuo_ContainerGumpTagDto *cuo_ContainerGumpTagDto_obs_typed(const cuo_obs *ev);

/* `cuo:gump/context-menu` */
void cuo_ContextMenuEvent_send(cuo_cmds *c, const cuo_ContextMenuEvent *v);
const cuo_ContextMenuEvent *cuo_ContextMenuEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ContextMenuEvent *cuo_ContextMenuEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ContextMenuEvent *cuo_ContextMenuEvent_obs_typed(const cuo_obs *ev);

/* `cuo:gump/grid-container` */
cuo_comp cuo_GridContainerWindow_typed(const cuo_GridContainerWindow *v);
const cuo_GridContainerWindow *cuo_GridContainerWindow_column(cuo_query q, size_t term);
void cuo_GridContainerWindow_set(cuo_query q, cuo_entity e, size_t term, const cuo_GridContainerWindow *v);
const cuo_GridContainerWindow *cuo_GridContainerWindow_obs_typed(const cuo_obs *ev);

/* `cuo:gump/grid-loot` */
cuo_comp cuo_GridLootWindow_typed(const cuo_GridLootWindow *v);
const cuo_GridLootWindow *cuo_GridLootWindow_column(cuo_query q, size_t term);
void cuo_GridLootWindow_set(cuo_query q, cuo_entity e, size_t term, const cuo_GridLootWindow *v);
const cuo_GridLootWindow *cuo_GridLootWindow_obs_typed(const cuo_obs *ev);

/* `cuo:gump/health-bar` */
cuo_comp cuo_HealthBarWindow_typed(const cuo_HealthBarWindow *v);
const cuo_HealthBarWindow *cuo_HealthBarWindow_column(cuo_query q, size_t term);
void cuo_HealthBarWindow_set(cuo_query q, cuo_entity e, size_t term, const cuo_HealthBarWindow *v);
const cuo_HealthBarWindow *cuo_HealthBarWindow_obs_typed(const cuo_obs *ev);

/* `cuo:gump/server` */
const cuo_ServerGumpDto *cuo_ServerGumpDto_column(cuo_query q, size_t term);
const cuo_ServerGumpDto *cuo_ServerGumpDto_obs_typed(const cuo_obs *ev);

/* `cuo:gump/vendor` */

/* `cuo:input/consume` */
void cuo_ModInputConsume_send(cuo_cmds *c, const cuo_ModInputConsume *v);
const cuo_ModInputConsume *cuo_ModInputConsume_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ModInputConsume *cuo_ModInputConsume_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ModInputConsume *cuo_ModInputConsume_obs_typed(const cuo_obs *ev);

/* `cuo:input/host-hotkeys` */
bool cuo_HostHotkeysDto_res(const cuo_input *in, cuo_param p, cuo_HostHotkeysDto *out);
bool cuo_HostHotkeysDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_HostHotkeysDto *out);

/* `cuo:input/hotkey` */
void cuo_ModHotkeyFired_send(cuo_cmds *c, const cuo_ModHotkeyFired *v);
const cuo_ModHotkeyFired *cuo_ModHotkeyFired_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ModHotkeyFired *cuo_ModHotkeyFired_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ModHotkeyFired *cuo_ModHotkeyFired_obs_typed(const cuo_obs *ev);

/* `cuo:input/mod-hotkeys` */
bool cuo_ModHotkeyBindingsDto_res(const cuo_input *in, cuo_param p, cuo_ModHotkeyBindingsDto *out);
bool cuo_ModHotkeyBindingsDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_ModHotkeyBindingsDto *out);

/* `cuo:input/world-single-click` */
bool cuo_WorldSingleClickDto_res(const cuo_input *in, cuo_param p, cuo_WorldSingleClickDto *out);
bool cuo_WorldSingleClickDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_WorldSingleClickDto *out);

/* `cuo:item/drop-sent` */
void cuo_ItemDropSent_send(cuo_cmds *c, const cuo_ItemDropSent *v);
const cuo_ItemDropSent *cuo_ItemDropSent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ItemDropSent *cuo_ItemDropSent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ItemDropSent *cuo_ItemDropSent_obs_typed(const cuo_obs *ev);

/* `cuo:item/move-result` */
void cuo_ItemMoveResult_send(cuo_cmds *c, const cuo_ItemMoveResult *v);
const cuo_ItemMoveResult *cuo_ItemMoveResult_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ItemMoveResult *cuo_ItemMoveResult_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ItemMoveResult *cuo_ItemMoveResult_obs_typed(const cuo_obs *ev);

/* `cuo:options/schema` */
bool cuo_ModOptionsSchemaDto_res(const cuo_input *in, cuo_param p, cuo_ModOptionsSchemaDto *out);
bool cuo_ModOptionsSchemaDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_ModOptionsSchemaDto *out);

/* `cuo:player/buffs` */
bool cuo_PlayerBuffsDto_res(const cuo_input *in, cuo_param p, cuo_PlayerBuffsDto *out);
bool cuo_PlayerBuffsDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_PlayerBuffsDto *out);

/* `cuo:player/grabbed-item` */
bool cuo_GrabbedItem_res(const cuo_input *in, cuo_param p, cuo_GrabbedItem *out);
bool cuo_GrabbedItem_obs_res(const cuo_obs *ev, cuo_param p, cuo_GrabbedItem *out);

/* `cuo:player/player` */
cuo_comp cuo_Player_typed(void);

/* `cuo:player/skills` */
bool cuo_PlayerSkillsDto_res(const cuo_input *in, cuo_param p, cuo_PlayerSkillsDto *out);
bool cuo_PlayerSkillsDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_PlayerSkillsDto *out);

/* `cuo:player/stat-locks` */
const cuo_StatLocks *cuo_StatLocks_column(cuo_query q, size_t term);
const cuo_StatLocks *cuo_StatLocks_obs_typed(const cuo_obs *ev);

/* `cuo:target/local-result` */
void cuo_LocalTargetResultEvent_send(cuo_cmds *c, const cuo_LocalTargetResultEvent *v);
const cuo_LocalTargetResultEvent *cuo_LocalTargetResultEvent_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_LocalTargetResultEvent *cuo_LocalTargetResultEvent_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_LocalTargetResultEvent *cuo_LocalTargetResultEvent_obs_typed(const cuo_obs *ev);

/* `cuo:target/state` */
bool cuo_TargetingState_res(const cuo_input *in, cuo_param p, cuo_TargetingState *out);
bool cuo_TargetingState_obs_res(const cuo_obs *ev, cuo_param p, cuo_TargetingState *out);

/* `cuo:ui/border-color` */
cuo_comp cuo_BorderColorDto_typed(const cuo_BorderColorDto *v);
const cuo_BorderColorDto *cuo_BorderColorDto_column(cuo_query q, size_t term);
void cuo_BorderColorDto_set(cuo_query q, cuo_entity e, size_t term, const cuo_BorderColorDto *v);
const cuo_BorderColorDto *cuo_BorderColorDto_obs_typed(const cuo_obs *ev);

/* `cuo:ui/button` */
cuo_comp cuo_UOButton_typed(const cuo_UOButton *v);
const cuo_UOButton *cuo_UOButton_column(cuo_query q, size_t term);
void cuo_UOButton_set(cuo_query q, cuo_entity e, size_t term, const cuo_UOButton *v);
const cuo_UOButton *cuo_UOButton_obs_typed(const cuo_obs *ev);

/* `cuo:ui/click` */
void cuo_ModClick_send(cuo_cmds *c);
size_t cuo_ModClick_events(const cuo_input *in, cuo_param p);
size_t cuo_ModClick_obs_events(const cuo_obs *ev, cuo_param p);

/* `cuo:ui/computed` */
const cuo_ComputedNode *cuo_ComputedNode_column(cuo_query q, size_t term);
const cuo_ComputedNode *cuo_ComputedNode_obs_typed(const cuo_obs *ev);

/* `cuo:ui/container-item` */
cuo_comp cuo_ContainerItemUI_typed(const cuo_ContainerItemUI *v);
const cuo_ContainerItemUI *cuo_ContainerItemUI_column(cuo_query q, size_t term);
void cuo_ContainerItemUI_set(cuo_query q, cuo_entity e, size_t term, const cuo_ContainerItemUI *v);
const cuo_ContainerItemUI *cuo_ContainerItemUI_obs_typed(const cuo_obs *ev);

/* `cuo:ui/contains-by-bounds` */
cuo_comp cuo_UiContainsByBounds_typed(void);

/* `cuo:ui/custom` */
cuo_comp cuo_UiCustomDto_typed(const cuo_UiCustomDto *v);
const cuo_UiCustomDto *cuo_UiCustomDto_column(cuo_query q, size_t term);
void cuo_UiCustomDto_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiCustomDto *v);
const cuo_UiCustomDto *cuo_UiCustomDto_obs_typed(const cuo_obs *ev);

/* `cuo:ui/editable-text` */
cuo_comp cuo_EditableText_typed(const cuo_EditableText *v);
const cuo_EditableText *cuo_EditableText_column(cuo_query q, size_t term);
void cuo_EditableText_set(cuo_query q, cuo_entity e, size_t term, const cuo_EditableText *v);
const cuo_EditableText *cuo_EditableText_obs_typed(const cuo_obs *ev);

/* `cuo:ui/hover` */
void cuo_ModHover_send(cuo_cmds *c, const cuo_ModHover *v);
const cuo_ModHover *cuo_ModHover_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ModHover *cuo_ModHover_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ModHover *cuo_ModHover_obs_typed(const cuo_obs *ev);

/* `cuo:ui/hover-tint` */
cuo_comp cuo_UiHoverTint_typed(const cuo_UiHoverTint *v);
const cuo_UiHoverTint *cuo_UiHoverTint_column(cuo_query q, size_t term);
void cuo_UiHoverTint_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiHoverTint *v);
const cuo_UiHoverTint *cuo_UiHoverTint_obs_typed(const cuo_obs *ev);

/* `cuo:ui/movable-no-drag` */
cuo_comp cuo_UiMovableNoDrag_typed(void);

/* `cuo:ui/name` */
cuo_comp cuo_UiName_typed(const cuo_UiName *v);
const cuo_UiName *cuo_UiName_column(cuo_query q, size_t term);
void cuo_UiName_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiName *v);
const cuo_UiName *cuo_UiName_obs_typed(const cuo_obs *ev);

/* `cuo:ui/no-blur` */
cuo_comp cuo_UiNoBlur_typed(void);

/* `cuo:ui/no-pickup` */
cuo_comp cuo_GridPinnedCell_typed(void);

/* `cuo:ui/no-right-click-close` */
cuo_comp cuo_UiNoRightClickClose_typed(void);

/* `cuo:ui/options-window` */
cuo_comp cuo_OptionsWindow_typed(void);

/* `cuo:ui/pick` */
bool cuo_UiPickDto_res(const cuo_input *in, cuo_param p, cuo_UiPickDto *out);
bool cuo_UiPickDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_UiPickDto *out);

/* `cuo:ui/popup` */
cuo_comp cuo_UiPopup_typed(void);

/* `cuo:ui/resizable` */
cuo_comp cuo_UiResizable_typed(const cuo_UiResizable *v);
const cuo_UiResizable *cuo_UiResizable_column(cuo_query q, size_t term);
void cuo_UiResizable_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiResizable *v);
const cuo_UiResizable *cuo_UiResizable_obs_typed(const cuo_obs *ev);

/* `cuo:ui/right-click` */
void cuo_ModRightClick_send(cuo_cmds *c, const cuo_ModRightClick *v);
const cuo_ModRightClick *cuo_ModRightClick_events(const cuo_input *in, cuo_param p, size_t *count);
const cuo_ModRightClick *cuo_ModRightClick_obs_events(const cuo_obs *ev, cuo_param p, size_t *count);
const cuo_ModRightClick *cuo_ModRightClick_obs_typed(const cuo_obs *ev);

/* `cuo:ui/scroll` */
cuo_comp cuo_ScrollPosition_typed(const cuo_ScrollPosition *v);
const cuo_ScrollPosition *cuo_ScrollPosition_column(cuo_query q, size_t term);
void cuo_ScrollPosition_set(cuo_query q, cuo_entity e, size_t term, const cuo_ScrollPosition *v);
const cuo_ScrollPosition *cuo_ScrollPosition_obs_typed(const cuo_obs *ev);

/* `cuo:ui/scrollbar` */
cuo_comp cuo_UiScrollbar_typed(const cuo_UiScrollbar *v);
const cuo_UiScrollbar *cuo_UiScrollbar_column(cuo_query q, size_t term);
void cuo_UiScrollbar_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiScrollbar *v);
const cuo_UiScrollbar *cuo_UiScrollbar_obs_typed(const cuo_obs *ev);

/* `cuo:ui/stat-lock-button` */
cuo_comp cuo_StatLockButton_typed(const cuo_StatLockButton *v);
const cuo_StatLockButton *cuo_StatLockButton_column(cuo_query q, size_t term);
void cuo_StatLockButton_set(cuo_query q, cuo_entity e, size_t term, const cuo_StatLockButton *v);
const cuo_StatLockButton *cuo_StatLockButton_obs_typed(const cuo_obs *ev);

/* `cuo:ui/statusbar-window` */
cuo_comp cuo_StatusBarWindow_typed(const cuo_StatusBarWindow *v);
const cuo_StatusBarWindow *cuo_StatusBarWindow_column(cuo_query q, size_t term);
void cuo_StatusBarWindow_set(cuo_query q, cuo_entity e, size_t term, const cuo_StatusBarWindow *v);
const cuo_StatusBarWindow *cuo_StatusBarWindow_obs_typed(const cuo_obs *ev);

/* `cuo:ui/supersedes` */
cuo_comp cuo_ModSupersedes_typed(const cuo_ModSupersedes *v);
const cuo_ModSupersedes *cuo_ModSupersedes_column(cuo_query q, size_t term);
void cuo_ModSupersedes_set(cuo_query q, cuo_entity e, size_t term, const cuo_ModSupersedes *v);
const cuo_ModSupersedes *cuo_ModSupersedes_obs_typed(const cuo_obs *ev);

/* `cuo:ui/surface` */
bool cuo_UiSurfaceDto_res(const cuo_input *in, cuo_param p, cuo_UiSurfaceDto *out);
bool cuo_UiSurfaceDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_UiSurfaceDto *out);

/* `cuo:ui/text-caret` */
bool cuo_TextCaretDto_res(const cuo_input *in, cuo_param p, cuo_TextCaretDto *out);
bool cuo_TextCaretDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_TextCaretDto *out);

/* `cuo:ui/text-completion-state` */
bool cuo_TextCompletionStateDto_res(const cuo_input *in, cuo_param p, cuo_TextCompletionStateDto *out);
bool cuo_TextCompletionStateDto_obs_res(const cuo_obs *ev, cuo_param p, cuo_TextCompletionStateDto *out);

/* `cuo:ui/text-hue` */
cuo_comp cuo_TextHue_typed(const cuo_TextHue *v);
const cuo_TextHue *cuo_TextHue_column(cuo_query q, size_t term);
void cuo_TextHue_set(cuo_query q, cuo_entity e, size_t term, const cuo_TextHue *v);
const cuo_TextHue *cuo_TextHue_obs_typed(const cuo_obs *ev);

/* `cuo:ui/text-input` */
cuo_comp cuo_TextInput_typed(void);

/* `cuo:ui/text-spans` */
cuo_comp cuo_TextSpans_typed(const cuo_TextSpans *v);
const cuo_TextSpans *cuo_TextSpans_column(cuo_query q, size_t term);
void cuo_TextSpans_set(cuo_query q, cuo_entity e, size_t term, const cuo_TextSpans *v);
const cuo_TextSpans *cuo_TextSpans_obs_typed(const cuo_obs *ev);

/* `cuo:ui/text-wrap` */
cuo_comp cuo_TextWrap_typed(const cuo_TextWrap *v);
const cuo_TextWrap *cuo_TextWrap_column(cuo_query q, size_t term);
void cuo_TextWrap_set(cuo_query q, cuo_entity e, size_t term, const cuo_TextWrap *v);
const cuo_TextWrap *cuo_TextWrap_obs_typed(const cuo_obs *ev);

/* `cuo:ui/tooltip` */
cuo_comp cuo_UiTooltip_typed(const cuo_UiTooltip *v);
const cuo_UiTooltip *cuo_UiTooltip_column(cuo_query q, size_t term);
void cuo_UiTooltip_set(cuo_query q, cuo_entity e, size_t term, const cuo_UiTooltip *v);
const cuo_UiTooltip *cuo_UiTooltip_obs_typed(const cuo_obs *ev);

/* `cuo:ui/topbar-bg` */
cuo_comp cuo_TopBarDragHandle_typed(void);

/* `cuo:ui/topbar-button` */
cuo_comp cuo_TopBarButton_typed(void);

/* `cuo:ui/topbar-full` */
cuo_comp cuo_TopBarFull_typed(void);

/* `cuo:ui/topbar-root` */
cuo_comp cuo_IsTopBar_typed(void);

#ifdef __cplusplus
}
#endif

#endif
