/* <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk */
/* The typed observer value parameter kinds (exports.h CUO__KIND): one per record a
 * typed trigger crosses as. */
#ifndef CUO_TYPED_KINDS_H
#define CUO_TYPED_KINDS_H

#define CUO__K_TYPED 16

#define CUO__TYPED_KINDS \
        cuo_modding_types_hits_t *: 16, \
        cuo_modding_types_mana_t *: 17, \
        cuo_modding_types_stamina_t *: 18, \
        cuo_modding_types_player_data_t *: 19, \
        cuo_modding_types_serial_t *: 20, \
        cuo_modding_types_graphic_t *: 21, \
        cuo_modding_types_hue_t *: 22, \
        cuo_modding_types_world_position_t *: 23, \
        cuo_modding_types_notoriety_t *: 24, \
        cuo_modding_types_entity_name_t *: 25, \
        cuo_modding_types_amount_t *: 26, \
        cuo_modding_types_node_t *: 27, \
        cuo_modding_types_text_t *: 28, \
        cuo_modding_types_text_font_t *: 29, \
        cuo_modding_types_text_color_t *: 30, \
        cuo_modding_types_background_color_t *: 31, \
        cuo_modding_types_border_radius_t *: 32, \
        cuo_modding_types_child_of_t *: 33, \
        cuo_modding_types_global_z_index_t *: 34, \
        cuo_modding_types_interaction_t *: 35, \
        cuo_modding_types_chat_message_t *: 36, \
        cuo_modding_types_prompt_opened_event_t *: 37, \
        cuo_modding_types_equipment_slots_t *: 38, \
        cuo_modding_types_facing_t *: 39, \
        cuo_modding_types_entity_properties_t *: 40, \
        cuo_modding_types_server_flags_t *: 41, \
        cuo_modding_types_container_slot_position_t *: 42, \
        cuo_modding_types_container_window_t *: 43, \
        cuo_modding_types_container_closed_event_t *: 44, \
        cuo_modding_types_container_opened_event_t *: 45, \
        cuo_modding_types_container_slot_event_t *: 46, \
        cuo_modding_types_container_gump_tag_t *: 47, \
        cuo_modding_types_context_menu_event_t *: 48, \
        cuo_modding_types_grid_container_window_t *: 49, \
        cuo_modding_types_grid_loot_window_t *: 50, \
        cuo_modding_types_health_bar_window_t *: 51, \
        cuo_modding_types_server_gump_t *: 52, \
        cuo_modding_types_input_consume_t *: 53, \
        cuo_modding_types_mod_hotkey_fired_t *: 54, \
        cuo_modding_types_item_drop_sent_t *: 55, \
        cuo_modding_types_item_move_result_t *: 56, \
        cuo_modding_types_stat_locks_t *: 57, \
        cuo_modding_types_local_target_result_event_t *: 58, \
        cuo_modding_types_border_color_t *: 59, \
        cuo_modding_types_uo_button_t *: 60, \
        cuo_modding_types_computed_node_t *: 61, \
        cuo_modding_types_container_item_ui_t *: 62, \
        cuo_modding_types_ui_custom_t *: 63, \
        cuo_modding_types_editable_text_t *: 64, \
        cuo_modding_types_ui_hover_t *: 65, \
        cuo_modding_types_ui_hover_tint_t *: 66, \
        cuo_modding_types_ui_name_t *: 67, \
        cuo_modding_types_ui_resizable_t *: 68, \
        cuo_modding_types_ui_right_click_t *: 69, \
        cuo_modding_types_scroll_position_t *: 70, \
        cuo_modding_types_ui_scrollbar_t *: 71, \
        cuo_modding_types_stat_lock_button_t *: 72, \
        cuo_modding_types_status_bar_window_t *: 73, \
        cuo_modding_types_mod_supersedes_t *: 74, \
        cuo_modding_types_text_hue_t *: 75, \
        cuo_modding_types_text_spans_t *: 76, \
        cuo_modding_types_text_wrap_t *: 77, \
        cuo_modding_types_ui_tooltip_t *: 78,

#endif
