// <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk
//! Registry type-path constants, mirrored from
//! `src/ClassicUO.Ecs/Modding/CuoModdingRegistry.cs`. A typed mod never needs them:
//! every [`crate::types`] struct carries its path (`HasPath::PATH`).
//!
//! Naming rules (deterministic, applied by the generator):
//! - `cuo:<module>/<leaf>` → `paths::<module>::<LEAF>`; the `cuo:` vendor prefix is
//!   dropped (every path has it), `-` becomes `_`, the leaf is SCREAMING_SNAKE_CASE.
//!   `cuo:player/stat-locks` → `paths::player::STAT_LOCKS`.
//! - A module segment that is a Rust keyword gets a `_` suffix (`mod` → `mod_`).

pub mod chat {
    /// `cuo:chat/message` — event.
    pub const MESSAGE: &str = "cuo:chat/message";
    /// `cuo:chat/prompt` — event.
    pub const PROMPT: &str = "cuo:chat/prompt";
}

pub mod ecs {
    /// `cuo:ecs/child-of` — component.
    pub const CHILD_OF: &str = "cuo:ecs/child-of";
}

pub mod engine {
    /// `cuo:engine/time` — resource.
    pub const TIME: &str = "cuo:engine/time";
}

pub mod ent {
    /// `cuo:ent/amount` — component.
    pub const AMOUNT: &str = "cuo:ent/amount";
    /// `cuo:ent/animation` — component.
    pub const ANIMATION: &str = "cuo:ent/animation";
    /// `cuo:ent/auto-opened-corpse` — component.
    pub const AUTO_OPENED_CORPSE: &str = "cuo:ent/auto-opened-corpse";
    /// `cuo:ent/contained-into` — component.
    pub const CONTAINED_INTO: &str = "cuo:ent/contained-into";
    /// `cuo:ent/equipment` — component.
    pub const EQUIPMENT: &str = "cuo:ent/equipment";
    /// `cuo:ent/facing` — component.
    pub const FACING: &str = "cuo:ent/facing";
    /// `cuo:ent/graphic` — component.
    pub const GRAPHIC: &str = "cuo:ent/graphic";
    /// `cuo:ent/hue` — component.
    pub const HUE: &str = "cuo:ent/hue";
    /// `cuo:ent/is-container` — component.
    pub const IS_CONTAINER: &str = "cuo:ent/is-container";
    /// `cuo:ent/is-item` — component.
    pub const IS_ITEM: &str = "cuo:ent/is-item";
    /// `cuo:ent/is-mobile` — component.
    pub const IS_MOBILE: &str = "cuo:ent/is-mobile";
    /// `cuo:ent/is-multi` — component.
    pub const IS_MULTI: &str = "cuo:ent/is-multi";
    /// `cuo:ent/manual-opened-corpse` — component.
    pub const MANUAL_OPENED_CORPSE: &str = "cuo:ent/manual-opened-corpse";
    /// `cuo:ent/mob-steps` — component.
    pub const MOB_STEPS: &str = "cuo:ent/mob-steps";
    /// `cuo:ent/name` — component.
    pub const NAME: &str = "cuo:ent/name";
    /// `cuo:ent/notoriety` — component.
    pub const NOTORIETY: &str = "cuo:ent/notoriety";
    /// `cuo:ent/properties` — component.
    pub const PROPERTIES: &str = "cuo:ent/properties";
    /// `cuo:ent/serial` — component.
    pub const SERIAL: &str = "cuo:ent/serial";
    /// `cuo:ent/server-flags` — component.
    pub const SERVER_FLAGS: &str = "cuo:ent/server-flags";
    /// `cuo:ent/slot-position` — component.
    pub const SLOT_POSITION: &str = "cuo:ent/slot-position";
    /// `cuo:ent/world-position` — component.
    pub const WORLD_POSITION: &str = "cuo:ent/world-position";
}

pub mod game {
    /// `cuo:game/context` — resource.
    pub const CONTEXT: &str = "cuo:game/context";
    /// `cuo:game/settings` — resource.
    pub const SETTINGS: &str = "cuo:game/settings";
    /// `cuo:game/state` — resource.
    pub const STATE: &str = "cuo:game/state";
}

pub mod gump {
    /// `cuo:gump/book` — component (presence-only).
    pub const BOOK: &str = "cuo:gump/book";
    /// `cuo:gump/buff` — component.
    pub const BUFF: &str = "cuo:gump/buff";
    /// `cuo:gump/bulletin-board` — component (presence-only).
    pub const BULLETIN_BOARD: &str = "cuo:gump/bulletin-board";
    /// `cuo:gump/combat-book` — component.
    pub const COMBAT_BOOK: &str = "cuo:gump/combat-book";
    /// `cuo:gump/container` — component.
    pub const CONTAINER: &str = "cuo:gump/container";
    /// `cuo:gump/container-closed` — event.
    pub const CONTAINER_CLOSED: &str = "cuo:gump/container-closed";
    /// `cuo:gump/container-opened` — event.
    pub const CONTAINER_OPENED: &str = "cuo:gump/container-opened";
    /// `cuo:gump/container-positions` — resource.
    pub const CONTAINER_POSITIONS: &str = "cuo:gump/container-positions";
    /// `cuo:gump/container-slot` — event.
    pub const CONTAINER_SLOT: &str = "cuo:gump/container-slot";
    /// `cuo:gump/container-tag` — component.
    pub const CONTAINER_TAG: &str = "cuo:gump/container-tag";
    /// `cuo:gump/context-menu` — event.
    pub const CONTEXT_MENU: &str = "cuo:gump/context-menu";
    /// `cuo:gump/grid-container` — component.
    pub const GRID_CONTAINER: &str = "cuo:gump/grid-container";
    /// `cuo:gump/grid-loot` — component.
    pub const GRID_LOOT: &str = "cuo:gump/grid-loot";
    /// `cuo:gump/health-bar` — component.
    pub const HEALTH_BAR: &str = "cuo:gump/health-bar";
    /// `cuo:gump/house-design` — component.
    pub const HOUSE_DESIGN: &str = "cuo:gump/house-design";
    /// `cuo:gump/journal` — component.
    pub const JOURNAL: &str = "cuo:gump/journal";
    /// `cuo:gump/logout` — component.
    pub const LOGOUT: &str = "cuo:gump/logout";
    /// `cuo:gump/map` — component (presence-only).
    pub const MAP: &str = "cuo:gump/map";
    /// `cuo:gump/menu` — component.
    pub const MENU: &str = "cuo:gump/menu";
    /// `cuo:gump/message-box` — component.
    pub const MESSAGE_BOX: &str = "cuo:gump/message-box";
    /// `cuo:gump/minimap` — component.
    pub const MINIMAP: &str = "cuo:gump/minimap";
    /// `cuo:gump/paperdoll` — component.
    pub const PAPERDOLL: &str = "cuo:gump/paperdoll";
    /// `cuo:gump/party-invite` — component.
    pub const PARTY_INVITE: &str = "cuo:gump/party-invite";
    /// `cuo:gump/party-manifest` — component.
    pub const PARTY_MANIFEST: &str = "cuo:gump/party-manifest";
    /// `cuo:gump/profile` — component.
    pub const PROFILE: &str = "cuo:gump/profile";
    /// `cuo:gump/racial-book` — component.
    pub const RACIAL_BOOK: &str = "cuo:gump/racial-book";
    /// `cuo:gump/server` — component.
    pub const SERVER: &str = "cuo:gump/server";
    /// `cuo:gump/server-closed` — event.
    pub const SERVER_CLOSED: &str = "cuo:gump/server-closed";
    /// `cuo:gump/server-opened` — event.
    pub const SERVER_OPENED: &str = "cuo:gump/server-opened";
    /// `cuo:gump/skills` — component.
    pub const SKILLS: &str = "cuo:gump/skills";
    /// `cuo:gump/spellbook` — component.
    pub const SPELLBOOK: &str = "cuo:gump/spellbook";
    /// `cuo:gump/split-menu` — component.
    pub const SPLIT_MENU: &str = "cuo:gump/split-menu";
    /// `cuo:gump/tip-notice` — component.
    pub const TIP_NOTICE: &str = "cuo:gump/tip-notice";
    /// `cuo:gump/trade` — component.
    pub const TRADE: &str = "cuo:gump/trade";
    /// `cuo:gump/vendor` — component (presence-only).
    pub const VENDOR: &str = "cuo:gump/vendor";
    /// `cuo:gump/worldmap` — component.
    pub const WORLDMAP: &str = "cuo:gump/worldmap";
}

pub mod input {
    /// `cuo:input/consume` — event.
    pub const CONSUME: &str = "cuo:input/consume";
    /// `cuo:input/host-hotkeys` — resource.
    pub const HOST_HOTKEYS: &str = "cuo:input/host-hotkeys";
    /// `cuo:input/hotkey` — event.
    pub const HOTKEY: &str = "cuo:input/hotkey";
    /// `cuo:input/keyboard` — resource.
    pub const KEYBOARD: &str = "cuo:input/keyboard";
    /// `cuo:input/mod-hotkeys` — resource.
    pub const MOD_HOTKEYS: &str = "cuo:input/mod-hotkeys";
    /// `cuo:input/mouse` — resource.
    pub const MOUSE: &str = "cuo:input/mouse";
    /// `cuo:input/world-single-click` — resource.
    pub const WORLD_SINGLE_CLICK: &str = "cuo:input/world-single-click";
}

pub mod item {
    /// `cuo:item/drop-sent` — event.
    pub const DROP_SENT: &str = "cuo:item/drop-sent";
    /// `cuo:item/move-result` — event.
    pub const MOVE_RESULT: &str = "cuo:item/move-result";
}

pub mod options {
    /// `cuo:options/schema` — resource.
    pub const SCHEMA: &str = "cuo:options/schema";
    /// `cuo:options/values` — resource.
    pub const VALUES: &str = "cuo:options/values";
}

pub mod player {
    /// `cuo:player/buffs` — resource.
    pub const BUFFS: &str = "cuo:player/buffs";
    /// `cuo:player/data` — component.
    pub const DATA: &str = "cuo:player/data";
    /// `cuo:player/grabbed-item` — resource.
    pub const GRABBED_ITEM: &str = "cuo:player/grabbed-item";
    /// `cuo:player/hits` — component.
    pub const HITS: &str = "cuo:player/hits";
    /// `cuo:player/mana` — component.
    pub const MANA: &str = "cuo:player/mana";
    /// `cuo:player/move-request` — event.
    pub const MOVE_REQUEST: &str = "cuo:player/move-request";
    /// `cuo:player/party` — resource.
    pub const PARTY: &str = "cuo:player/party";
    /// `cuo:player/player` — component.
    pub const PLAYER: &str = "cuo:player/player";
    /// `cuo:player/skills` — resource.
    pub const SKILLS: &str = "cuo:player/skills";
    /// `cuo:player/spellbook` — resource.
    pub const SPELLBOOK: &str = "cuo:player/spellbook";
    /// `cuo:player/stamina` — component.
    pub const STAMINA: &str = "cuo:player/stamina";
    /// `cuo:player/stat-locks` — component.
    pub const STAT_LOCKS: &str = "cuo:player/stat-locks";
    /// `cuo:player/steps` — resource.
    pub const STEPS: &str = "cuo:player/steps";
}

pub mod scene {
    /// `cuo:scene/character-creation` — component.
    pub const CHARACTER_CREATION: &str = "cuo:scene/character-creation";
    /// `cuo:scene/character-list` — event.
    pub const CHARACTER_LIST: &str = "cuo:scene/character-list";
    /// `cuo:scene/character-selection` — component.
    pub const CHARACTER_SELECTION: &str = "cuo:scene/character-selection";
    /// `cuo:scene/game` — component.
    pub const GAME: &str = "cuo:scene/game";
    /// `cuo:scene/login` — component.
    pub const LOGIN: &str = "cuo:scene/login";
    /// `cuo:scene/login-error` — component.
    pub const LOGIN_ERROR: &str = "cuo:scene/login-error";
    /// `cuo:scene/login-error-info` — event.
    pub const LOGIN_ERROR_INFO: &str = "cuo:scene/login-error-info";
    /// `cuo:scene/login-request` — event.
    pub const LOGIN_REQUEST: &str = "cuo:scene/login-request";
    /// `cuo:scene/server-list` — event.
    pub const SERVER_LIST: &str = "cuo:scene/server-list";
    /// `cuo:scene/server-selection` — component.
    pub const SERVER_SELECTION: &str = "cuo:scene/server-selection";
}

pub mod target {
    /// `cuo:target/local-result` — event.
    pub const LOCAL_RESULT: &str = "cuo:target/local-result";
    /// `cuo:target/state` — resource.
    pub const STATE: &str = "cuo:target/state";
}

pub mod ui {
    /// `cuo:ui/bg-color` — component.
    pub const BG_COLOR: &str = "cuo:ui/bg-color";
    /// `cuo:ui/border-color` — component.
    pub const BORDER_COLOR: &str = "cuo:ui/border-color";
    /// `cuo:ui/border-radius` — component.
    pub const BORDER_RADIUS: &str = "cuo:ui/border-radius";
    /// `cuo:ui/button` — component.
    pub const BUTTON: &str = "cuo:ui/button";
    /// `cuo:ui/click` — event.
    pub const CLICK: &str = "cuo:ui/click";
    /// `cuo:ui/clipboard-set` — resource.
    pub const CLIPBOARD_SET: &str = "cuo:ui/clipboard-set";
    /// `cuo:ui/computed` — component.
    pub const COMPUTED: &str = "cuo:ui/computed";
    /// `cuo:ui/container-item` — component.
    pub const CONTAINER_ITEM: &str = "cuo:ui/container-item";
    /// `cuo:ui/contains-by-bounds` — component.
    pub const CONTAINS_BY_BOUNDS: &str = "cuo:ui/contains-by-bounds";
    /// `cuo:ui/custom` — component.
    pub const CUSTOM: &str = "cuo:ui/custom";
    /// `cuo:ui/editable-text` — component.
    pub const EDITABLE_TEXT: &str = "cuo:ui/editable-text";
    /// `cuo:ui/focused-input` — resource.
    pub const FOCUSED_INPUT: &str = "cuo:ui/focused-input";
    /// `cuo:ui/global-z` — component.
    pub const GLOBAL_Z: &str = "cuo:ui/global-z";
    /// `cuo:ui/hover` — event.
    pub const HOVER: &str = "cuo:ui/hover";
    /// `cuo:ui/hover-tint` — component.
    pub const HOVER_TINT: &str = "cuo:ui/hover-tint";
    /// `cuo:ui/interaction` — component.
    pub const INTERACTION: &str = "cuo:ui/interaction";
    /// `cuo:ui/masked-text` — component.
    pub const MASKED_TEXT: &str = "cuo:ui/masked-text";
    /// `cuo:ui/movable` — component.
    pub const MOVABLE: &str = "cuo:ui/movable";
    /// `cuo:ui/movable-no-drag` — component.
    pub const MOVABLE_NO_DRAG: &str = "cuo:ui/movable-no-drag";
    /// `cuo:ui/name` — component.
    pub const NAME: &str = "cuo:ui/name";
    /// `cuo:ui/no-blur` — component.
    pub const NO_BLUR: &str = "cuo:ui/no-blur";
    /// `cuo:ui/no-pickup` — component.
    pub const NO_PICKUP: &str = "cuo:ui/no-pickup";
    /// `cuo:ui/no-right-click-close` — component.
    pub const NO_RIGHT_CLICK_CLOSE: &str = "cuo:ui/no-right-click-close";
    /// `cuo:ui/no-window-drag` — component.
    pub const NO_WINDOW_DRAG: &str = "cuo:ui/no-window-drag";
    /// `cuo:ui/node` — component.
    pub const NODE: &str = "cuo:ui/node";
    /// `cuo:ui/options-window` — component.
    pub const OPTIONS_WINDOW: &str = "cuo:ui/options-window";
    /// `cuo:ui/pick` — resource.
    pub const PICK: &str = "cuo:ui/pick";
    /// `cuo:ui/popup` — component.
    pub const POPUP: &str = "cuo:ui/popup";
    /// `cuo:ui/resizable` — component.
    pub const RESIZABLE: &str = "cuo:ui/resizable";
    /// `cuo:ui/right-click` — event.
    pub const RIGHT_CLICK: &str = "cuo:ui/right-click";
    /// `cuo:ui/scroll` — component.
    pub const SCROLL: &str = "cuo:ui/scroll";
    /// `cuo:ui/scrollbar` — component.
    pub const SCROLLBAR: &str = "cuo:ui/scrollbar";
    /// `cuo:ui/stat-lock-button` — component.
    pub const STAT_LOCK_BUTTON: &str = "cuo:ui/stat-lock-button";
    /// `cuo:ui/statusbar-window` — component.
    pub const STATUSBAR_WINDOW: &str = "cuo:ui/statusbar-window";
    /// `cuo:ui/supersedes` — component.
    pub const SUPERSEDES: &str = "cuo:ui/supersedes";
    /// `cuo:ui/surface` — resource.
    pub const SURFACE: &str = "cuo:ui/surface";
    /// `cuo:ui/text` — component.
    pub const TEXT: &str = "cuo:ui/text";
    /// `cuo:ui/text-caret` — resource.
    pub const TEXT_CARET: &str = "cuo:ui/text-caret";
    /// `cuo:ui/text-clipboard-action` — resource.
    pub const TEXT_CLIPBOARD_ACTION: &str = "cuo:ui/text-clipboard-action";
    /// `cuo:ui/text-color` — component.
    pub const TEXT_COLOR: &str = "cuo:ui/text-color";
    /// `cuo:ui/text-completion` — resource.
    pub const TEXT_COMPLETION: &str = "cuo:ui/text-completion";
    /// `cuo:ui/text-completion-pick` — resource.
    pub const TEXT_COMPLETION_PICK: &str = "cuo:ui/text-completion-pick";
    /// `cuo:ui/text-completion-state` — resource.
    pub const TEXT_COMPLETION_STATE: &str = "cuo:ui/text-completion-state";
    /// `cuo:ui/text-font` — component.
    pub const TEXT_FONT: &str = "cuo:ui/text-font";
    /// `cuo:ui/text-hue` — component.
    pub const TEXT_HUE: &str = "cuo:ui/text-hue";
    /// `cuo:ui/text-input` — component.
    pub const TEXT_INPUT: &str = "cuo:ui/text-input";
    /// `cuo:ui/text-spans` — component.
    pub const TEXT_SPANS: &str = "cuo:ui/text-spans";
    /// `cuo:ui/text-wrap` — component.
    pub const TEXT_WRAP: &str = "cuo:ui/text-wrap";
    /// `cuo:ui/tooltip` — component.
    pub const TOOLTIP: &str = "cuo:ui/tooltip";
    /// `cuo:ui/tooltip-serial` — component.
    pub const TOOLTIP_SERIAL: &str = "cuo:ui/tooltip-serial";
    /// `cuo:ui/topbar-bg` — component.
    pub const TOPBAR_BG: &str = "cuo:ui/topbar-bg";
    /// `cuo:ui/topbar-button` — component.
    pub const TOPBAR_BUTTON: &str = "cuo:ui/topbar-button";
    /// `cuo:ui/topbar-full` — component.
    pub const TOPBAR_FULL: &str = "cuo:ui/topbar-full";
    /// `cuo:ui/topbar-root` — component.
    pub const TOPBAR_ROOT: &str = "cuo:ui/topbar-root";
}

