// <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk
//! Payload types for every registered type-path: the exact JSON the host writes and
//! reads through `System.Text.Json` (`IncludeFields = true`, no naming policy, enums as
//! numbers). Serialize one of these instead of hand-building a JSON string.
//!
//! Conventions:
//! - Field names are snake_case; `#[serde(rename_all = "PascalCase")]` (or a per-field
//!   `rename`) restores the host's verbatim member names on the wire.
//! - `#[serde(default)]` everywhere: a host that omits a field (or a mod that fills in
//!   only part of a component) round-trips instead of erroring.
//! - C# enums cross as their underlying integer. Each one also gets a consts module
//!   (`display::FLEX`), and the field carries the member list in its doc comment.
//! - Zero-size tags and `ModPresence` markers are empty structs — the host's payload
//!   for them is literally `{}`.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

use crate::paths;

/// Associates a payload type with the registry type-path it is registered under.
/// Implemented for every type reachable from exactly one path (types shared by several
/// paths get the first one, listed in the struct's doc comment).
pub trait HasPath {
    const PATH: &'static str;
}

/// `TinyEcs.Bevy.UI.AlignItems` — crosses as `u8`.
pub type AlignItems = u8;
pub mod align_items {
    pub const START: super::AlignItems = 0;
    pub const CENTER: super::AlignItems = 1;
    pub const END: super::AlignItems = 2;
}

/// `cuo:ent/amount`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Amount {
    pub value: i32,
}
impl HasPath for Amount {
    const PATH: &'static str = paths::ent::AMOUNT;
}

/// `cuo:ui/bg-color`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct BackgroundColor {
    pub value: Color,
}
impl HasPath for BackgroundColor {
    const PATH: &'static str = paths::ui::BG_COLOR;
}

/// `cuo:gump/book`
/// Presence-only marker: the host always answers `{}` and ignores writes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BookWindow {}
impl HasPath for BookWindow {
    const PATH: &'static str = paths::gump::BOOK;
}

/// `cuo:ui/border-radius`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct BorderRadius {
    pub top_left: f32,
    pub top_right: f32,
    pub bottom_left: f32,
    pub bottom_right: f32,
}
impl HasPath for BorderRadius {
    const PATH: &'static str = paths::ui::BORDER_RADIUS;
}

/// `cuo:gump/buff`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BuffGumpUI {}
impl HasPath for BuffGumpUI {
    const PATH: &'static str = paths::gump::BUFF;
}

/// `cuo:gump/bulletin-board`
/// Presence-only marker: the host always answers `{}` and ignores writes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BulletinBoardWindow {}
impl HasPath for BulletinBoardWindow {
    const PATH: &'static str = paths::gump::BULLETIN_BOARD;
}

/// `cuo:action/cast-spell`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct CastSpellAction {
    pub id: i32,
}
impl HasPath for CastSpellAction {
    const PATH: &'static str = paths::action::CAST_SPELL;
}

/// `cuo:scene/character-creation`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct CharCreationScene {}
impl HasPath for CharCreationScene {
    const PATH: &'static str = paths::scene::CHARACTER_CREATION;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.CharInfoDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct CharInfoDto {
    pub name: String,
    pub index: u32,
}

/// `cuo:scene/character-list`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct CharacterSelectionDto {
    pub characters: Vec<CharInfoDto>,
    pub towns: Vec<TownInfoDto>,
}
impl HasPath for CharacterSelectionDto {
    const PATH: &'static str = paths::scene::CHARACTER_LIST;
}

/// `cuo:scene/character-selection`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct CharacterSelectionScene {}
impl HasPath for CharacterSelectionScene {
    const PATH: &'static str = paths::scene::CHARACTER_SELECTION;
}

/// Nested payload type (`Clay.Color`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
    /// Host-computed: written by the host, ignored when a mod sets it.
    pub is_visible: bool,
}

/// `cuo:gump/combat-book`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct CombatBookWindow {
    pub page: i32,
    pub sounded_page: i32,
    pub page_count: i32,
    pub dict_pages: i32,
    pub ability_count: i32,
    pub dirty: bool,
    pub content: u64,
    pub left: u64,
    pub right: u64,
}
impl HasPath for CombatBookWindow {
    const PATH: &'static str = paths::gump::COMBAT_BOOK;
}

/// `cuo:ent/container`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContainedInDto {
    pub container: u32,
}
impl HasPath for ContainedInDto {
    const PATH: &'static str = paths::ent::CONTAINER;
}

/// `cuo:ent/contained-into`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ContainedInto {}
impl HasPath for ContainedInto {
    const PATH: &'static str = paths::ent::CONTAINED_INTO;
}

/// `cuo:gump/container-closed`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContainerClosedEvent {
    pub serial: u32,
    pub user_initiated: bool,
}
impl HasPath for ContainerClosedEvent {
    const PATH: &'static str = paths::gump::CONTAINER_CLOSED;
}

/// `cuo:gump/container-opened`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContainerOpenedEvent {
    pub serial: u32,
    pub graphic: u16,
}
impl HasPath for ContainerOpenedEvent {
    const PATH: &'static str = paths::gump::CONTAINER_OPENED;
}

/// `cuo:ent/slot-position`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContainerSlotPosition {
    pub x: u16,
    pub y: u16,
    pub grid_index: u8,
}
impl HasPath for ContainerSlotPosition {
    const PATH: &'static str = paths::ent::SLOT_POSITION;
}

/// `cuo:gump/container`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContainerWindow {
    pub serial: u32,
}
impl HasPath for ContainerWindow {
    const PATH: &'static str = paths::gump::CONTAINER;
}

/// Nested payload type (`ClassicUO.Ecs.ContextMenuEntry`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContextMenuEntry {
    pub index: u16,
    pub cliloc: i32,
    pub text: String,
    pub flags: u16,
    pub hue: u16,
}

/// `cuo:gump/context-menu`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContextMenuEvent {
    pub serial: u32,
    pub entries: Vec<ContextMenuEntry>,
}
impl HasPath for ContextMenuEvent {
    const PATH: &'static str = paths::gump::CONTEXT_MENU;
}

/// `cuo:action/context-menu-reply`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ContextMenuReplyAction {
    pub serial: u32,
    pub index: u16,
}
impl HasPath for ContextMenuReplyAction {
    const PATH: &'static str = paths::action::CONTEXT_MENU_REPLY;
}

/// `ClassicUO.Game.Data.Direction` — crosses as `u8`.
pub type Direction = u8;
pub mod direction {
    pub const NORTH: super::Direction = 0;
    pub const RIGHT: super::Direction = 1;
    pub const EAST: super::Direction = 2;
    pub const DOWN: super::Direction = 3;
    pub const SOUTH: super::Direction = 4;
    pub const LEFT: super::Direction = 5;
    pub const WEST: super::Direction = 6;
    pub const UP: super::Direction = 7;
    pub const MASK: super::Direction = 7;
    pub const RUNNING: super::Direction = 128;
    pub const NONE: super::Direction = 237;
}

/// `TinyEcs.Bevy.UI.Display` — crosses as `u8`.
pub type Display = u8;
pub mod display {
    pub const FLEX: super::Display = 0;
    pub const NONE: super::Display = 1;
}

/// `cuo:action/double-click`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct DoubleClickAction {
    pub serial: u32,
}
impl HasPath for DoubleClickAction {
    const PATH: &'static str = paths::action::DOUBLE_CLICK;
}

/// `cuo:action/drop`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct DropAction {
    pub serial: u32,
    pub x: u16,
    pub y: u16,
    pub z: i8,
    pub container: u32,
}
impl HasPath for DropAction {
    const PATH: &'static str = paths::action::DROP;
}

/// `cuo:ui/editable-text`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct EditableText {
    pub multiline: bool,
}
impl HasPath for EditableText {
    const PATH: &'static str = paths::ui::EDITABLE_TEXT;
}

/// `cuo:ent/name`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct EntityName {
    pub value: String,
}
impl HasPath for EntityName {
    const PATH: &'static str = paths::ent::NAME;
}

/// `cuo:ent/properties`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct EntityPropertiesDto {
    pub serial: u32,
    pub revision: u32,
    pub name: String,
    pub lines: Vec<OplLineDto>,
}
impl HasPath for EntityPropertiesDto {
    const PATH: &'static str = paths::ent::PROPERTIES;
}

/// `cuo:action/equip`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct EquipAction {
    pub serial: u32,
    pub layer: u8,
    pub container: u32,
}
impl HasPath for EquipAction {
    const PATH: &'static str = paths::action::EQUIP;
}

/// `cuo:ent/equipment`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct EquipmentSlotsDto {
    pub serials: Vec<u32>,
}
impl HasPath for EquipmentSlotsDto {
    const PATH: &'static str = paths::ent::EQUIPMENT;
}

/// `cuo:ent/facing`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Facing {
    /// enum Direction (0=North, 1=Right, 2=East, 3=Down, 4=South, 5=Left, 6=West, 7=Up, 7=Mask, 128=Running, 237=NONE)
    pub value: u8,
}
impl HasPath for Facing {
    const PATH: &'static str = paths::ent::FACING;
}

/// `ClassicUO.Game.Data.Flags` — crosses as `u8`.
pub type Flags = u8;
pub mod flags {
    pub const NONE: super::Flags = 0;
    pub const FROZEN: super::Flags = 1;
    pub const FEMALE: super::Flags = 2;
    pub const POISONED: super::Flags = 4;
    pub const FLYING: super::Flags = 4;
    pub const YELLOW_BAR: super::Flags = 8;
    pub const IGNORE_MOBILES: super::Flags = 16;
    pub const MOVABLE: super::Flags = 32;
    pub const WAR_MODE: super::Flags = 64;
    pub const HIDDEN: super::Flags = 128;
}

/// `TinyEcs.Bevy.UI.FlexDirection` — crosses as `u8`.
pub type FlexDirection = u8;
pub mod flex_direction {
    pub const ROW: super::FlexDirection = 0;
    pub const COLUMN: super::FlexDirection = 1;
}

/// `cuo:ui/focused-input`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct FocusedInput {
    pub entity: u64,
}
impl HasPath for FocusedInput {
    const PATH: &'static str = paths::ui::FOCUSED_INPUT;
}

/// `cuo:game/context`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GameContextDto {
    pub player_serial: u32,
    pub player_name: String,
    pub map: i32,
    pub season: u8,
    pub client_version: u32,
    pub use_old_status_gump: bool,
}
impl HasPath for GameContextDto {
    const PATH: &'static str = paths::game::CONTEXT;
}

/// `cuo:scene/game`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GameScene {}
impl HasPath for GameScene {
    const PATH: &'static str = paths::scene::GAME;
}

/// `cuo:game/state`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GameStateDto {
    pub current: u8,
}
impl HasPath for GameStateDto {
    const PATH: &'static str = paths::game::STATE;
}

/// `cuo:ui/global-z`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GlobalZIndex {
    pub value: i32,
}
impl HasPath for GlobalZIndex {
    const PATH: &'static str = paths::ui::GLOBAL_Z;
}

/// `cuo:player/grabbed-item`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GrabbedItem {
    pub is_active: bool,
    pub serial: u32,
    pub graphic: u16,
    pub hue: u16,
    pub amount: i32,
    pub source_ui_entity: u64,
    pub original_graphic: u16,
    pub original_hue: u16,
    pub original_amount: u16,
    pub original_x: u16,
    pub original_y: u16,
    pub original_z: i8,
    pub original_container: u32,
    pub original_grid_index: u8,
    pub original_from_slot: bool,
    /// enum Layer (0=Invalid, 1=OneHanded, 2=TwoHanded, 3=Shoes, 4=Pants, 5=Shirt, 6=Helmet, 7=Gloves, 8=Ring, 9=Talisman, 10=Necklace, 11=Hair, 12=Waist, 13=Torso, 14=Bracelet, 15=Face, 16=Beard, 17=Tunic, 18=Earrings, 19=Arms, 20=Cloak, 21=Backpack, 22=Robe, 23=Skirt, 24=Legs, 25=Mount, 26=ShopBuyRestock, 27=ShopBuy, 28=ShopSell, 29=Bank)
    pub original_layer: u8,
    pub pending_drop: bool,
    pub drop_target_serial: u32,
    pub failed_drop: bool,
}
impl HasPath for GrabbedItem {
    const PATH: &'static str = paths::player::GRABBED_ITEM;
}

/// `cuo:ent/graphic`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Graphic {
    pub value: u16,
}
impl HasPath for Graphic {
    const PATH: &'static str = paths::ent::GRAPHIC;
}

/// `cuo:gump/grid-container`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GridContainerWindow {
    pub serial: u32,
}
impl HasPath for GridContainerWindow {
    const PATH: &'static str = paths::gump::GRID_CONTAINER;
}

/// `cuo:gump/grid-loot`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GridLootWindow {
    pub corpse_serial: u32,
    pub corpse_entity: u64,
    pub content_sig: i32,
}
impl HasPath for GridLootWindow {
    const PATH: &'static str = paths::gump::GRID_LOOT;
}

/// `cuo:action/gump-close`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GumpCloseAction {
    pub gump_id: u32,
}
impl HasPath for GumpCloseAction {
    const PATH: &'static str = paths::action::GUMP_CLOSE;
}

/// `cuo:action/gump-reply`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GumpReplyAction {
    pub gump_id: u32,
    pub button_id: i32,
    pub switches: Vec<u32>,
    pub text_entries: Vec<GumpTextEntry>,
}
impl HasPath for GumpReplyAction {
    const PATH: &'static str = paths::action::GUMP_REPLY;
}

/// Nested payload type (`ClassicUO.Ecs.GumpTextEntry`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct GumpTextEntry {
    pub id: u16,
    pub text: String,
}

/// `cuo:gump/health-bar`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct HealthBarWindow {
    pub serial: u32,
    pub is_player: bool,
    pub out_of_range: bool,
    pub hp_requested: bool,
    pub was_dead: bool,
    pub in_party: bool,
    pub name_editable: bool,
}
impl HasPath for HealthBarWindow {
    const PATH: &'static str = paths::gump::HEALTH_BAR;
}

/// `cuo:player/hits`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Hits {
    pub value: u16,
    pub max_value: u16,
}
impl HasPath for Hits {
    const PATH: &'static str = paths::player::HITS;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.HostHotkeyDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct HostHotkeyDto {
    pub key: i32,
    pub ctrl: bool,
    pub shift: bool,
    pub alt: bool,
    pub action: String,
}

/// `cuo:input/host-hotkeys`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct HostHotkeysDto {
    pub hotkeys: Vec<HostHotkeyDto>,
}
impl HasPath for HostHotkeysDto {
    const PATH: &'static str = paths::input::HOST_HOTKEYS;
}

/// `cuo:gump/house-design`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct HouseDesignWindow {
    pub content: u64,
    pub serial: u32,
}
impl HasPath for HouseDesignWindow {
    const PATH: &'static str = paths::gump::HOUSE_DESIGN;
}

/// `cuo:ent/hue`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Hue {
    pub value: u16,
}
impl HasPath for Hue {
    const PATH: &'static str = paths::ent::HUE;
}

/// `cuo:ui/interaction` — the payload IS this enum's number.
/// `TinyEcs.Bevy.UI.Interaction` — crosses as `u8`.
pub type Interaction = u8;
pub mod interaction {
    pub const NONE: super::Interaction = 0;
    pub const HOVERED: super::Interaction = 1;
    pub const PRESSED: super::Interaction = 2;
}

/// `cuo:ent/is-container`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct IsContainer {}
impl HasPath for IsContainer {
    const PATH: &'static str = paths::ent::IS_CONTAINER;
}

/// `cuo:ent/is-multi`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct IsMulti {}
impl HasPath for IsMulti {
    const PATH: &'static str = paths::ent::IS_MULTI;
}

/// `cuo:ui/topbar-root`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct IsTopBar {}
impl HasPath for IsTopBar {
    const PATH: &'static str = paths::ui::TOPBAR_ROOT;
}

/// `cuo:ent/is-item`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Items {}
impl HasPath for Items {
    const PATH: &'static str = paths::ent::IS_ITEM;
}

/// `cuo:gump/journal`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct JournalWindow {
    pub special_height: i32,
    pub minimized: bool,
    pub dark_mode: bool,
    pub show_system: bool,
    pub show_objects: bool,
    pub show_client: bool,
    pub show_guild: bool,
    pub built_revision: i32,
    pub style_epoch: i32,
    pub built_style_epoch: i32,
    pub list_entity: u64,
    pub flag_entity: u64,
    pub top_entity: u64,
    pub mid_entity: u64,
    pub bottom_entity: u64,
    pub title_entity: u64,
    pub minimize_entity: u64,
    pub dark_check_entity: u64,
    pub expander_entity: u64,
    pub width: f32,
    pub list_width: f32,
    pub content_height: f32,
}
impl HasPath for JournalWindow {
    const PATH: &'static str = paths::gump::JOURNAL;
}

/// `TinyEcs.Bevy.UI.JustifyContent` — crosses as `u8`.
pub type JustifyContent = u8;
pub mod justify_content {
    pub const START: super::JustifyContent = 0;
    pub const CENTER: super::JustifyContent = 1;
    pub const END: super::JustifyContent = 2;
}

/// `cuo:input/keyboard`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct KeyboardInputDto {
    pub pressed: Vec<i32>,
}
impl HasPath for KeyboardInputDto {
    const PATH: &'static str = paths::input::KEYBOARD;
}

/// `ClassicUO.Game.Data.Layer` — crosses as `u8`.
pub type Layer = u8;
pub mod layer {
    pub const INVALID: super::Layer = 0;
    pub const ONE_HANDED: super::Layer = 1;
    pub const TWO_HANDED: super::Layer = 2;
    pub const SHOES: super::Layer = 3;
    pub const PANTS: super::Layer = 4;
    pub const SHIRT: super::Layer = 5;
    pub const HELMET: super::Layer = 6;
    pub const GLOVES: super::Layer = 7;
    pub const RING: super::Layer = 8;
    pub const TALISMAN: super::Layer = 9;
    pub const NECKLACE: super::Layer = 10;
    pub const HAIR: super::Layer = 11;
    pub const WAIST: super::Layer = 12;
    pub const TORSO: super::Layer = 13;
    pub const BRACELET: super::Layer = 14;
    pub const FACE: super::Layer = 15;
    pub const BEARD: super::Layer = 16;
    pub const TUNIC: super::Layer = 17;
    pub const EARRINGS: super::Layer = 18;
    pub const ARMS: super::Layer = 19;
    pub const CLOAK: super::Layer = 20;
    pub const BACKPACK: super::Layer = 21;
    pub const ROBE: super::Layer = 22;
    pub const SKIRT: super::Layer = 23;
    pub const LEGS: super::Layer = 24;
    pub const MOUNT: super::Layer = 25;
    pub const SHOP_BUY_RESTOCK: super::Layer = 26;
    pub const SHOP_BUY: super::Layer = 27;
    pub const SHOP_SELL: super::Layer = 28;
    pub const BANK: super::Layer = 29;
}

/// `cuo:target/local-result`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct LocalTargetResultEvent {
    pub entity: u64,
    pub serial: u32,
    pub graphic: u16,
    pub x: u16,
    pub y: u16,
    pub z: i8,
    pub cancelled: bool,
}
impl HasPath for LocalTargetResultEvent {
    const PATH: &'static str = paths::target::LOCAL_RESULT;
}

/// Nested payload type (`ClassicUO.Ecs.LoginErrorInfo`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct LoginErrorInfo {
    pub error_message: String,
}

/// `cuo:scene/login-error`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LoginErrorScene {}
impl HasPath for LoginErrorScene {
    const PATH: &'static str = paths::scene::LOGIN_ERROR;
}

/// `cuo:scene/login-error-info`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct LoginErrorsInfoEvent {
    pub error: LoginErrorInfo,
}
impl HasPath for LoginErrorsInfoEvent {
    const PATH: &'static str = paths::scene::LOGIN_ERROR_INFO;
}

/// `cuo:scene/login`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LoginScene {}
impl HasPath for LoginScene {
    const PATH: &'static str = paths::scene::LOGIN;
}

/// `cuo:gump/logout`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LogoutGumpWindow {}
impl HasPath for LogoutGumpWindow {
    const PATH: &'static str = paths::gump::LOGOUT;
}

/// `cuo:player/mana`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Mana {
    pub value: u16,
    pub max_value: u16,
}
impl HasPath for Mana {
    const PATH: &'static str = paths::player::MANA;
}

/// `cuo:gump/map`
/// Presence-only marker: the host always answers `{}` and ignores writes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct MapWindow {}
impl HasPath for MapWindow {
    const PATH: &'static str = paths::gump::MAP;
}

/// `cuo:ui/masked-text`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MaskedText {
    pub value: String,
    pub mask_char: String,
}
impl HasPath for MaskedText {
    const PATH: &'static str = paths::ui::MASKED_TEXT;
}

/// `cuo:gump/menu`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MenuGumpWindow {
    pub serial: u32,
    pub server_menu_id: u16,
    pub is_gray: bool,
    pub responded: bool,
}
impl HasPath for MenuGumpWindow {
    const PATH: &'static str = paths::gump::MENU;
}

/// `cuo:gump/message-box`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageBoxWindow {}
impl HasPath for MessageBoxWindow {
    const PATH: &'static str = paths::gump::MESSAGE_BOX;
}

/// `cuo:gump/minimap`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MiniMapWindow {
    pub use_large_map: bool,
}
impl HasPath for MiniMapWindow {
    const PATH: &'static str = paths::gump::MINIMAP;
}

/// `cuo:ent/animation`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MobAnimation {
    pub index: i32,
    pub frames_count: i32,
    pub interval: i32,
    pub repeat_mode: i32,
    pub repeat_mode_count: i32,
    pub repeat: bool,
    pub is_from_server: bool,
    pub forward_direction: bool,
    pub action: u8,
    pub mount_action: u8,
    /// enum Direction (0=North, 1=Right, 2=East, 3=Down, 4=South, 5=Left, 6=West, 7=Up, 7=Mask, 128=Running, 237=NONE)
    pub direction: u8,
    pub time: f32,
    pub run: bool,
}
impl HasPath for MobAnimation {
    const PATH: &'static str = paths::ent::ANIMATION;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.MobStepDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MobStepDto {
    pub x: i32,
    pub y: i32,
    pub z: i8,
    pub direction: u8,
    pub run: bool,
}

/// `cuo:ent/mob-steps`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MobileStepsDto {
    pub index: i32,
    pub time: f32,
    pub steps: Vec<MobStepDto>,
}
impl HasPath for MobileStepsDto {
    const PATH: &'static str = paths::ent::MOB_STEPS;
}

/// `cuo:ent/is-mobile`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Mobiles {}
impl HasPath for Mobiles {
    const PATH: &'static str = paths::ent::IS_MOBILE;
}

/// `cuo:chat/message`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModChatMessage {
    pub serial: u32,
    pub text: String,
    pub name: String,
    pub hue: u16,
    pub font: u8,
    pub is_unicode: bool,
    pub message_type: u8,
    pub time: f32,
    pub kind: u8,
}
impl HasPath for ModChatMessage {
    const PATH: &'static str = paths::chat::MESSAGE;
}

/// `cuo:ui/clicked`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModClicked {
    pub tick: u8,
}
impl HasPath for ModClicked {
    const PATH: &'static str = paths::ui::CLICKED;
}

/// `cuo:test/counter`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModCounter {
    pub value: i32,
}
impl HasPath for ModCounter {
    const PATH: &'static str = paths::test::COUNTER;
}

/// `cuo:mod/owned`
/// Presence-only marker: the host always answers `{}` and ignores writes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ModEntity {}
impl HasPath for ModEntity {
    const PATH: &'static str = paths::mod_::OWNED;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.ModHotkeyBinding`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModHotkeyBinding {
    pub name: String,
    pub key: i32,
    pub mouse: i32,
    pub ctrl: bool,
    pub shift: bool,
    pub alt: bool,
    pub consume: bool,
}

/// `cuo:input/mod-hotkeys`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModHotkeyBindingsDto {
    pub bindings: Vec<ModHotkeyBinding>,
    pub consume_keys: bool,
}
impl HasPath for ModHotkeyBindingsDto {
    const PATH: &'static str = paths::input::MOD_HOTKEYS;
}

/// `cuo:input/hotkey`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModHotkeyFired {
    pub name: String,
    pub key: i32,
    pub mouse: i32,
    pub ctrl: bool,
    pub shift: bool,
    pub alt: bool,
    pub from_mod: bool,
}
impl HasPath for ModHotkeyFired {
    const PATH: &'static str = paths::input::HOTKEY;
}

/// `cuo:ui/hovered`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModHovered {
    pub tick: u8,
}
impl HasPath for ModHovered {
    const PATH: &'static str = paths::ui::HOVERED;
}

/// `cuo:player/move-request`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModMoveRequest {
    pub direction: u8,
    pub run: bool,
    pub sequence: u8,
}
impl HasPath for ModMoveRequest {
    const PATH: &'static str = paths::player::MOVE_REQUEST;
}

/// `cuo:ui/right-clicked`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModRightClicked {
    pub tick: u8,
    pub x: f32,
    pub y: f32,
}
impl HasPath for ModRightClicked {
    const PATH: &'static str = paths::ui::RIGHT_CLICKED;
}

/// `cuo:mod/state`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ModState {
    pub json: String,
}
impl HasPath for ModState {
    const PATH: &'static str = paths::mod_::STATE;
}

/// `cuo:input/mouse`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct MouseInputDto {
    pub x: f32,
    pub y: f32,
    pub left: bool,
    pub right: bool,
    pub middle: bool,
    pub x1: bool,
    pub x2: bool,
    pub wheel: f32,
}
impl HasPath for MouseInputDto {
    const PATH: &'static str = paths::input::MOUSE;
}

/// `cuo:ent/serial`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct NetworkSerial {
    pub value: u32,
}
impl HasPath for NetworkSerial {
    const PATH: &'static str = paths::ent::SERIAL;
}

/// `cuo:ui/node`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Node {
    /// enum Display (0=Flex, 1=None)
    pub display: u8,
    /// enum PositionType (0=Relative, 1=Absolute)
    pub position_type: u8,
    /// enum Overflow (0=Visible, 1=Clip, 2=Scroll)
    pub overflow: u8,
    /// enum FlexDirection (0=Row, 1=Column)
    pub flex_direction: u8,
    /// enum JustifyContent (0=Start, 1=Center, 2=End)
    pub justify_content: u8,
    /// enum AlignItems (0=Start, 1=Center, 2=End)
    pub align_items: u8,
    pub width: Val,
    pub height: Val,
    pub min_width: Val,
    pub min_height: Val,
    pub max_width: Val,
    pub max_height: Val,
    pub left: Val,
    pub top: Val,
    pub right: Val,
    pub bottom: Val,
    pub padding: UiRect,
    pub border: UiRect,
    pub gap: Val,
    pub aspect_ratio: f32,
}
impl HasPath for Node {
    const PATH: &'static str = paths::ui::NODE;
}

/// `cuo:ent/notoriety`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Notoriety {
    /// enum NotorietyFlag (0=Unknown, 1=Innocent, 2=Ally, 3=Gray, 4=Criminal, 5=Enemy, 6=Murderer, 7=Invulnerable)
    pub value: u8,
}
impl HasPath for Notoriety {
    const PATH: &'static str = paths::ent::NOTORIETY;
}

/// `ClassicUO.Game.Data.NotorietyFlag` — crosses as `u8`.
pub type NotorietyFlag = u8;
pub mod notoriety_flag {
    pub const UNKNOWN: super::NotorietyFlag = 0;
    pub const INNOCENT: super::NotorietyFlag = 1;
    pub const ALLY: super::NotorietyFlag = 2;
    pub const GRAY: super::NotorietyFlag = 3;
    pub const CRIMINAL: super::NotorietyFlag = 4;
    pub const ENEMY: super::NotorietyFlag = 5;
    pub const MURDERER: super::NotorietyFlag = 6;
    pub const INVULNERABLE: super::NotorietyFlag = 7;
}

/// `cuo:scene/login-request`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct OnLoginRequest {
    pub username: String,
    pub password: String,
    pub address: String,
    pub port: u16,
}
impl HasPath for OnLoginRequest {
    const PATH: &'static str = paths::scene::LOGIN_REQUEST;
}

/// `cuo:action/open-door`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct OpenDoorAction {}
impl HasPath for OpenDoorAction {
    const PATH: &'static str = paths::action::OPEN_DOOR;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.OplLineDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct OplLineDto {
    pub cliloc: i32,
    pub args: String,
    pub text: String,
}

/// `cuo:ui/options-window`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct OptionsWindow {}
impl HasPath for OptionsWindow {
    const PATH: &'static str = paths::ui::OPTIONS_WINDOW;
}

/// `TinyEcs.Bevy.UI.Overflow` — crosses as `u8`.
pub type Overflow = u8;
pub mod overflow {
    pub const VISIBLE: super::Overflow = 0;
    pub const CLIP: super::Overflow = 1;
    pub const SCROLL: super::Overflow = 2;
}

/// `cuo:gump/paperdoll`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PaperdollWindow {
    pub serial: u32,
    pub is_player: bool,
    pub can_lift: bool,
}
impl HasPath for PaperdollWindow {
    const PATH: &'static str = paths::gump::PAPERDOLL;
}

/// `cuo:player/party`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PartyDto {
    pub leader: u32,
    pub members: Vec<PartyMemberDto>,
    pub in_party: bool,
    pub can_loot: bool,
}
impl HasPath for PartyDto {
    const PATH: &'static str = paths::player::PARTY;
}

/// `cuo:gump/party-invite`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PartyInviteWindow {
    pub inviter: u32,
}
impl HasPath for PartyInviteWindow {
    const PATH: &'static str = paths::gump::PARTY_INVITE;
}

/// `cuo:gump/party-manifest`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PartyManifestWindow {
    pub can_loot: bool,
}
impl HasPath for PartyManifestWindow {
    const PATH: &'static str = paths::gump::PARTY_MANIFEST;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.PartyMemberDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PartyMemberDto {
    pub serial: u32,
    pub name: String,
}

/// `cuo:action/pickup`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PickupAction {
    pub serial: u32,
    pub amount: u16,
}
impl HasPath for PickupAction {
    const PATH: &'static str = paths::action::PICKUP;
}

/// `cuo:player/player`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Player {}
impl HasPath for Player {
    const PATH: &'static str = paths::player::PLAYER;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.PlayerBuffDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerBuffDto {
    pub type_: i32,
    pub graphic: u16,
    pub expires_at: f32,
    pub text: String,
}

/// `cuo:player/buffs`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerBuffsDto {
    pub buffs: Vec<PlayerBuffDto>,
}
impl HasPath for PlayerBuffsDto {
    const PATH: &'static str = paths::player::BUFFS;
}

/// `cuo:player/data`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerData {
    pub str: u16,
    pub str_max: u16,
    pub dex: u16,
    pub dex_max: u16,
    pub int: u16,
    pub int_max: u16,
    pub stats_cap: i16,
    pub followers: u8,
    pub followers_max: u8,
    pub weight: u16,
    pub weight_max: u16,
    pub gold: u32,
    pub thithing_points: u32,
    pub luck: u16,
    pub damage_min: i16,
    pub damage_max: i16,
    pub physical_res: i16,
    pub fire_res: i16,
    pub cold_res: i16,
    pub poison_res: i16,
    pub energy_res: i16,
    pub is_female: bool,
    /// enum RaceType (1=HUMAN, 2=ELF, 3=GARGOYLE)
    pub race: u8,
    pub max_physical_res: i16,
    pub max_fire_res: i16,
    pub max_cold_res: i16,
    pub max_poison_res: i16,
    pub max_energy_res: i16,
    pub defense_chance_inc: i16,
    pub max_defense_chance_inc: i16,
    pub hit_chance_inc: i16,
    pub swing_speed_inc: i16,
    pub damage_inc: i16,
    pub lower_reagent_cost: i16,
    pub spell_damage_inc: i16,
    pub faster_cast_recovery: i16,
    pub faster_casting: i16,
    pub lower_mana_cost: i16,
}
impl HasPath for PlayerData {
    const PATH: &'static str = paths::player::DATA;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.PlayerSkillDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerSkillDto {
    pub index: i32,
    pub value: u16,
    pub base: u16,
    pub cap: u16,
    pub lock: u8,
}

/// `cuo:player/skills`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerSkillsDto {
    pub has_data: bool,
    pub skills: Vec<PlayerSkillDto>,
}
impl HasPath for PlayerSkillsDto {
    const PATH: &'static str = paths::player::SKILLS;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.PlayerStepDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerStepDto {
    pub sequence: u8,
    pub direction: u8,
    pub x: u16,
    pub y: u16,
    pub z: i8,
}

/// `cuo:player/steps`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PlayerStepsDto {
    pub last_step: f32,
    pub count: i32,
    pub sequence: u8,
    pub resync_sent: bool,
    pub steps: Vec<PlayerStepDto>,
}
impl HasPath for PlayerStepsDto {
    const PATH: &'static str = paths::player::STEPS;
}

/// `TinyEcs.Bevy.UI.PositionType` — crosses as `u8`.
pub type PositionType = u8;
pub mod position_type {
    pub const RELATIVE: super::PositionType = 0;
    pub const ABSOLUTE: super::PositionType = 1;
}

/// `cuo:gump/profile`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ProfileWindow {
    pub serial: u32,
    pub special_height: i32,
    pub width: f32,
    pub mid_entity: u64,
    pub bottom_entity: u64,
    pub expander_entity: u64,
    pub footer_entity: u64,
    pub footer_offset_from_bottom: i32,
}
impl HasPath for ProfileWindow {
    const PATH: &'static str = paths::gump::PROFILE;
}

/// `cuo:chat/prompt`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PromptOpenedEvent {
    pub serial: u32,
    pub prompt_id: u32,
    pub unicode: bool,
    pub text: String,
}
impl HasPath for PromptOpenedEvent {
    const PATH: &'static str = paths::chat::PROMPT;
}

/// `cuo:action/prompt-reply`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct PromptReplyAction {
    pub text: String,
    pub cancel: bool,
}
impl HasPath for PromptReplyAction {
    const PATH: &'static str = paths::action::PROMPT_REPLY;
}

/// `ClassicUO.Game.Data.RaceType` — crosses as `u8`.
pub type RaceType = u8;
pub mod race_type {
    pub const HUMAN: super::RaceType = 1;
    pub const ELF: super::RaceType = 2;
    pub const GARGOYLE: super::RaceType = 3;
}

/// `cuo:gump/racial-book`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RacialBookWindow {
    pub page: i32,
    pub sounded_page: i32,
    pub page_count: i32,
    pub dict_pages: i32,
    pub ability_count: i32,
    /// enum RaceType (1=HUMAN, 2=ELF, 3=GARGOYLE)
    pub race: u8,
    pub dirty: bool,
    pub content: u64,
    pub left: u64,
    pub right: u64,
}
impl HasPath for RacialBookWindow {
    const PATH: &'static str = paths::gump::RACIAL_BOOK;
}

/// `cuo:action/rename`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RenameAction {
    pub serial: u32,
    pub name: String,
}
impl HasPath for RenameAction {
    const PATH: &'static str = paths::action::RENAME;
}

/// `cuo:action/request-context-menu`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RequestContextMenuAction {
    pub serial: u32,
}
impl HasPath for RequestContextMenuAction {
    const PATH: &'static str = paths::action::REQUEST_CONTEXT_MENU;
}

/// `cuo:action/request-properties`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RequestPropertiesAction {
    pub serial: u32,
}
impl HasPath for RequestPropertiesAction {
    const PATH: &'static str = paths::action::REQUEST_PROPERTIES;
}

/// `cuo:action/request-skills`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RequestSkillsAction {
    pub serial: u32,
}
impl HasPath for RequestSkillsAction {
    const PATH: &'static str = paths::action::REQUEST_SKILLS;
}

/// `cuo:action/request-status`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RequestStatusAction {
    pub serial: u32,
}
impl HasPath for RequestStatusAction {
    const PATH: &'static str = paths::action::REQUEST_STATUS;
}

/// `cuo:action/request-target`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct RequestTargetAction {
    pub prompt_text: String,
}
impl HasPath for RequestTargetAction {
    const PATH: &'static str = paths::action::REQUEST_TARGET;
}

/// `cuo:action/say`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SayAction {
    pub text: String,
    pub hue: u16,
}
impl HasPath for SayAction {
    const PATH: &'static str = paths::action::SAY;
}

/// `cuo:ui/scroll`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ScrollPosition {
    pub offset_x: f32,
    pub offset_y: f32,
}
impl HasPath for ScrollPosition {
    const PATH: &'static str = paths::ui::SCROLL;
}

/// `ClassicUO.Ecs.ScrollbarStyle` — crosses as `u8`.
pub type ScrollbarStyle = u8;
pub mod scrollbar_style {
    pub const UO: super::ScrollbarStyle = 0;
    pub const FLAT: super::ScrollbarStyle = 1;
}

/// `cuo:ent/server-flags`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerFlags {
    /// enum Flags (0=None, 1=Frozen, 2=Female, 4=Poisoned, 4=Flying, 8=YellowBar, 16=IgnoreMobiles, 32=Movable, 64=WarMode, 128=Hidden)
    pub value: u8,
}
impl HasPath for ServerFlags {
    const PATH: &'static str = paths::ent::SERVER_FLAGS;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.ServerGumpButtonDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpButtonDto {
    pub id: i32,
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

/// `cuo:gump/server-closed`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpClosedEvent {
    pub serial: u32,
    pub gump_id: u32,
}
impl HasPath for ServerGumpClosedEvent {
    const PATH: &'static str = paths::gump::SERVER_CLOSED;
}

/// `cuo:gump/server`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpDto {
    pub serial: u32,
    pub gump_id: u32,
    pub page: i32,
    pub x: i32,
    pub y: i32,
    pub layout: Vec<String>,
    pub texts: Vec<String>,
    pub buttons: Vec<ServerGumpButtonDto>,
    pub text_entries: Vec<ServerGumpTextEntryDto>,
    pub switches: Vec<ServerGumpSwitchDto>,
}
impl HasPath for ServerGumpDto {
    const PATH: &'static str = paths::gump::SERVER;
}

/// `cuo:gump/server-opened`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpOpenedEvent {
    pub serial: u32,
    pub gump_id: u32,
}
impl HasPath for ServerGumpOpenedEvent {
    const PATH: &'static str = paths::gump::SERVER_OPENED;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.ServerGumpSwitchDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpSwitchDto {
    pub id: u32,
    pub checked: bool,
    pub is_radio: bool,
    pub group: i32,
}

/// Nested payload type (`ClassicUO.Ecs.Modding.ServerGumpTextEntryDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerGumpTextEntryDto {
    pub id: u16,
    pub text: String,
}

/// Nested payload type (`ClassicUO.Ecs.ServerInfo`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerInfo {
    pub index: i32,
    pub name: String,
    pub percent_full: u8,
    pub time_zone: u8,
    pub ip: u32,
}

/// `cuo:scene/server-list`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct ServerSelectionInfoEvent {
    pub servers: Vec<ServerInfo>,
}
impl HasPath for ServerSelectionInfoEvent {
    const PATH: &'static str = paths::scene::SERVER_LIST;
}

/// `cuo:scene/server-selection`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ServerSelectionScene {}
impl HasPath for ServerSelectionScene {
    const PATH: &'static str = paths::scene::SERVER_SELECTION;
}

/// `cuo:action/single-click`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SingleClickAction {
    pub serial: u32,
}
impl HasPath for SingleClickAction {
    const PATH: &'static str = paths::action::SINGLE_CLICK;
}

/// `cuo:gump/skills`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SkillsWindow {
    pub special_height: i32,
    pub minimized: bool,
    pub show_real: bool,
    pub show_caps: bool,
    pub dirty: bool,
    pub width: i32,
    pub list_width: f32,
    pub content_height: f32,
    pub list_entity: u64,
    pub top_entity: u64,
    pub mid_entity: u64,
    pub bottom_entity: u64,
    pub title_entity: u64,
    pub minimize_entity: u64,
    pub expander_entity: u64,
    pub sum_label_entity: u64,
    pub flag_entity: u64,
    pub last_sum: f32,
}
impl HasPath for SkillsWindow {
    const PATH: &'static str = paths::gump::SKILLS;
}

/// `ClassicUO.Ecs.SpellBookType` — crosses as `i32`.
pub type SpellBookType = i32;
pub mod spell_book_type {
    pub const MAGERY: super::SpellBookType = 0;
    pub const NECROMANCY: super::SpellBookType = 1;
    pub const CHIVALRY: super::SpellBookType = 2;
    pub const BUSHIDO: super::SpellBookType = 4;
    pub const NINJITSU: super::SpellBookType = 5;
    pub const SPELLWEAVING: super::SpellBookType = 6;
    pub const MYSTICISM: super::SpellBookType = 7;
    pub const MASTERY: super::SpellBookType = 8;
    pub const UNKNOWN: super::SpellBookType = 255;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.SpellbookDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SpellbookDto {
    pub serial: u32,
    pub book_type: u8,
    pub spells: Vec<i32>,
}

/// `cuo:gump/spellbook`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SpellbookWindow {
    pub serial: u32,
    /// enum SpellBookType (0=Magery, 1=Necromancy, 2=Chivalry, 4=Bushido, 5=Ninjitsu, 6=Spellweaving, 7=Mysticism, 8=Mastery, 255=Unknown)
    pub school: i32,
    pub page: i32,
    pub sounded_page: i32,
    pub page_count: i32,
    pub built_revision: i32,
    pub dirty: bool,
    pub content_entity: u64,
    pub left_corner: u64,
    pub right_corner: u64,
}
impl HasPath for SpellbookWindow {
    const PATH: &'static str = paths::gump::SPELLBOOK;
}

/// `cuo:player/spellbook`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SpellbooksDto {
    pub revision: i32,
    pub books: Vec<SpellbookDto>,
}
impl HasPath for SpellbooksDto {
    const PATH: &'static str = paths::player::SPELLBOOK;
}

/// `cuo:gump/split-menu`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct SplitMenuWindow {
    pub serial: u32,
    pub max_amount: i32,
    pub slider: u64,
    pub text: u64,
    pub ok: u64,
    pub last_slider: i32,
    pub last_text: String,
    pub graphic: u16,
    pub hue: u16,
    pub source_ui_entity: u64,
    pub source_container: u32,
    pub original_graphic: u16,
    pub original_hue: u16,
    pub original_amount: u16,
    pub original_x: u16,
    pub original_y: u16,
    pub original_z: i8,
    pub original_container: u32,
    pub original_grid_index: u8,
    pub original_from_slot: bool,
}
impl HasPath for SplitMenuWindow {
    const PATH: &'static str = paths::gump::SPLIT_MENU;
}

/// `cuo:player/stamina`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Stamina {
    pub value: u16,
    pub max_value: u16,
}
impl HasPath for Stamina {
    const PATH: &'static str = paths::player::STAMINA;
}

/// `cuo:ui/stat-lock-button`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct StatLockButton {
    pub stat: u8,
}
impl HasPath for StatLockButton {
    const PATH: &'static str = paths::ui::STAT_LOCK_BUTTON;
}

/// `cuo:player/stat-locks`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct StatLocks {
    pub str: u8,
    pub dex: u8,
    pub int: u8,
}
impl HasPath for StatLocks {
    const PATH: &'static str = paths::player::STAT_LOCKS;
}

/// `cuo:ui/statusbar-window`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct StatusBarWindow {
    pub minimize_x: f32,
    pub minimize_y: f32,
}
impl HasPath for StatusBarWindow {
    const PATH: &'static str = paths::ui::STATUSBAR_WINDOW;
}

/// `cuo:action/target-cancel`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct TargetCancelAction {}
impl HasPath for TargetCancelAction {
    const PATH: &'static str = paths::action::TARGET_CANCEL;
}

/// `cuo:action/target-location`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TargetLocationAction {
    pub x: u16,
    pub y: u16,
    pub z: i8,
    pub graphic: u16,
}
impl HasPath for TargetLocationAction {
    const PATH: &'static str = paths::action::TARGET_LOCATION;
}

/// `cuo:action/target-object`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TargetObjectAction {
    pub serial: u32,
}
impl HasPath for TargetObjectAction {
    const PATH: &'static str = paths::action::TARGET_OBJECT;
}

/// `cuo:target/state`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TargetingState {
    pub is_targeting: bool,
    pub mode: u8,
    pub local: bool,
    pub cursor_id: u32,
    pub cursor_type: u8,
    pub just_targeted: bool,
    pub multi_id: u16,
    pub multi_offset_x: i16,
    pub multi_offset_y: i16,
    pub multi_offset_z: i16,
    pub multi_hue: u16,
    pub preview_built_id: u16,
    pub has_local_result: bool,
    pub local_serial: u32,
    pub local_graphic: u16,
    pub local_x: u16,
    pub local_y: u16,
    pub local_z: i8,
    pub local_cancelled: bool,
}
impl HasPath for TargetingState {
    const PATH: &'static str = paths::target::STATE;
}

/// `cuo:ui/text`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Text {
    pub value: String,
}
impl HasPath for Text {
    const PATH: &'static str = paths::ui::TEXT;
}

/// `cuo:ui/text-caret`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextCaretDto {
    pub entity: u64,
    pub cursor: i32,
    pub select_start: i32,
    pub select_end: i32,
    pub line: i32,
    pub column: i32,
    pub screen_x: f32,
    pub screen_y: f32,
    pub row_height: f32,
}
impl HasPath for TextCaretDto {
    const PATH: &'static str = paths::ui::TEXT_CARET;
}

/// `cuo:ui/text-clipboard-action`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextClipboardActionDto {
    pub entity: u64,
    pub action: i32,
    pub seq: i32,
}
impl HasPath for TextClipboardActionDto {
    const PATH: &'static str = paths::ui::TEXT_CLIPBOARD_ACTION;
}

/// `cuo:ui/text-color`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextColor {
    pub value: Color,
}
impl HasPath for TextColor {
    const PATH: &'static str = paths::ui::TEXT_COLOR;
}

/// `cuo:ui/text-completion`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextCompletionDto {
    pub entity: u64,
    pub prefix: String,
    pub items: Vec<String>,
}
impl HasPath for TextCompletionDto {
    const PATH: &'static str = paths::ui::TEXT_COMPLETION;
}

/// `cuo:ui/text-completion-pick`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextCompletionPickDto {
    pub entity: u64,
    pub index: i32,
    pub seq: i32,
}
impl HasPath for TextCompletionPickDto {
    const PATH: &'static str = paths::ui::TEXT_COMPLETION_PICK;
}

/// `cuo:ui/text-completion-state`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextCompletionStateDto {
    pub selected: i32,
}
impl HasPath for TextCompletionStateDto {
    const PATH: &'static str = paths::ui::TEXT_COMPLETION_STATE;
}

/// `cuo:ui/text-font`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextFont {
    pub font_id: u16,
    pub size: u16,
}
impl HasPath for TextFont {
    const PATH: &'static str = paths::ui::TEXT_FONT;
}

/// `cuo:ui/text-hue`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextHue {
    pub value: u16,
}
impl HasPath for TextHue {
    const PATH: &'static str = paths::ui::TEXT_HUE;
}

/// `cuo:ui/text-input`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct TextInput {}
impl HasPath for TextInput {
    const PATH: &'static str = paths::ui::TEXT_INPUT;
}

/// Nested payload type (`ClassicUO.Ecs.TextSpan`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextSpan {
    pub start: i32,
    pub length: i32,
    pub color: Color,
}

/// `cuo:ui/text-spans`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextSpans {
    pub spans: Vec<TextSpan>,
}
impl HasPath for TextSpans {
    const PATH: &'static str = paths::ui::TEXT_SPANS;
}

/// `cuo:ui/text-wrap`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TextWrap {
    /// enum TextWrapKind (0=Words, 1=Newlines, 2=None)
    pub kind: u8,
}
impl HasPath for TextWrap {
    const PATH: &'static str = paths::ui::TEXT_WRAP;
}

/// `TinyEcs.Bevy.UI.TextWrapKind` — crosses as `u8`.
pub type TextWrapKind = u8;
pub mod text_wrap_kind {
    pub const WORDS: super::TextWrapKind = 0;
    pub const NEWLINES: super::TextWrapKind = 1;
    pub const NONE: super::TextWrapKind = 2;
}

/// `cuo:engine/time`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Time {
    pub total: f32,
    pub frame: f32,
}
impl HasPath for Time {
    const PATH: &'static str = paths::engine::TIME;
}

/// `cuo:gump/tip-notice`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TipNoticeWindow {
    pub tip_serial: u16,
    pub special_height: i32,
    pub width: f32,
    pub mid_entity: u64,
    pub bottom_entity: u64,
    pub expander_entity: u64,
    pub prev_entity: u64,
    pub next_entity: u64,
}
impl HasPath for TipNoticeWindow {
    const PATH: &'static str = paths::gump::TIP_NOTICE;
}

/// `cuo:action/toggle-war-mode`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ToggleWarModeAction {}
impl HasPath for ToggleWarModeAction {
    const PATH: &'static str = paths::action::TOGGLE_WAR_MODE;
}

/// `cuo:ui/topbar-button`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct TopBarButton {}
impl HasPath for TopBarButton {
    const PATH: &'static str = paths::ui::TOPBAR_BUTTON;
}

/// `cuo:ui/topbar-bg`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct TopBarDragHandle {}
impl HasPath for TopBarDragHandle {
    const PATH: &'static str = paths::ui::TOPBAR_BG;
}

/// `cuo:ui/topbar-full`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct TopBarFull {}
impl HasPath for TopBarFull {
    const PATH: &'static str = paths::ui::TOPBAR_FULL;
}

/// Nested payload type (`ClassicUO.Ecs.Modding.TownInfoDto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TownInfoDto {
    pub index: u8,
    pub name: String,
    pub building: String,
    pub x: u16,
    pub y: u16,
    pub z: i8,
    pub map: u32,
    pub cliloc_description: u32,
}

/// `cuo:gump/trade`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct TradeWindow {
    pub serial: u32,
    pub id1: u32,
    pub id2: u32,
    pub im_accepting: bool,
    pub he_is_accepting: bool,
    pub is_new: bool,
}
impl HasPath for TradeWindow {
    const PATH: &'static str = paths::gump::TRADE;
}

/// `cuo:ui/button`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UOButton {
    pub normal: u16,
    pub pressed: u16,
    pub over: u16,
}
impl HasPath for UOButton {
    const PATH: &'static str = paths::ui::BUTTON;
}

/// `cuo:ui/contains-by-bounds`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiContainsByBounds {}
impl HasPath for UiContainsByBounds {
    const PATH: &'static str = paths::ui::CONTAINS_BY_BOUNDS;
}

/// `cuo:ui/custom`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiCustomDto {
    pub kind: u8,
    pub asset_id: u32,
    pub hue_x: f32,
    pub hue_y: f32,
    pub hue_z: f32,
}
impl HasPath for UiCustomDto {
    const PATH: &'static str = paths::ui::CUSTOM;
}

/// `cuo:ui/hover-tint`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiHoverTint {
    pub normal: Color,
    pub hover: Color,
}
impl HasPath for UiHoverTint {
    const PATH: &'static str = paths::ui::HOVER_TINT;
}

/// `cuo:ui/movable`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiMovable {}
impl HasPath for UiMovable {
    const PATH: &'static str = paths::ui::MOVABLE;
}

/// `cuo:ui/movable-no-drag`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiMovableNoDrag {}
impl HasPath for UiMovableNoDrag {
    const PATH: &'static str = paths::ui::MOVABLE_NO_DRAG;
}

/// `cuo:ui/name`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiName {
    pub value: String,
}
impl HasPath for UiName {
    const PATH: &'static str = paths::ui::NAME;
}

/// `cuo:ui/no-blur`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiNoBlur {}
impl HasPath for UiNoBlur {
    const PATH: &'static str = paths::ui::NO_BLUR;
}

/// `cuo:ui/no-right-click-close`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiNoRightClickClose {}
impl HasPath for UiNoRightClickClose {
    const PATH: &'static str = paths::ui::NO_RIGHT_CLICK_CLOSE;
}

/// `cuo:ui/no-window-drag`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiNoWindowDrag {}
impl HasPath for UiNoWindowDrag {
    const PATH: &'static str = paths::ui::NO_WINDOW_DRAG;
}

/// `cuo:ui/popup`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct UiPopup {}
impl HasPath for UiPopup {
    const PATH: &'static str = paths::ui::POPUP;
}

/// Nested payload type (`TinyEcs.Bevy.UI.UiRect`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiRect {
    pub left: Val,
    pub right: Val,
    pub top: Val,
    pub bottom: Val,
}

/// `cuo:ui/resizable`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiResizable {
    pub min_w: f32,
    pub min_h: f32,
    pub max_w: f32,
    pub max_h: f32,
    pub grip: f32,
}
impl HasPath for UiResizable {
    const PATH: &'static str = paths::ui::RESIZABLE;
}

/// `cuo:ui/scrollbar`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiScrollbar {
    pub width: f32,
    /// enum ScrollbarStyle (0=Uo, 1=Flat)
    pub style: u8,
}
impl HasPath for UiScrollbar {
    const PATH: &'static str = paths::ui::SCROLLBAR;
}

/// `cuo:ui/surface`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiSurfaceDto {
    pub w: f32,
    pub h: f32,
}
impl HasPath for UiSurfaceDto {
    const PATH: &'static str = paths::ui::SURFACE;
}

/// `cuo:ui/tooltip`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UiTooltip {
    pub text: String,
    pub max_width: i32,
}
impl HasPath for UiTooltip {
    const PATH: &'static str = paths::ui::TOOLTIP;
}

/// `cuo:action/use-skill`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct UseSkillAction {
    pub id: i32,
}
impl HasPath for UseSkillAction {
    const PATH: &'static str = paths::action::USE_SKILL;
}

/// Nested payload type (`TinyEcs.Bevy.UI.Val`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct Val {
    /// enum ValType (0=Auto, 1=Px, 2=Percent, 3=Grow)
    pub type_: u8,
    pub value: f32,
    /// Host-computed: written by the host, ignored when a mod sets it.
    pub is_auto: bool,
}

/// `TinyEcs.Bevy.UI.ValType` — crosses as `u8`.
pub type ValType = u8;
pub mod val_type {
    pub const AUTO: super::ValType = 0;
    pub const PX: super::ValType = 1;
    pub const PERCENT: super::ValType = 2;
    pub const GROW: super::ValType = 3;
}

/// `cuo:gump/vendor`
/// Presence-only marker: the host always answers `{}` and ignores writes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct VendorWindow {}
impl HasPath for VendorWindow {
    const PATH: &'static str = paths::gump::VENDOR;
}

/// `cuo:action/walk`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct WalkAction {
    pub direction: u8,
    pub run: bool,
}
impl HasPath for WalkAction {
    const PATH: &'static str = paths::action::WALK;
}

/// `cuo:action/walk-to`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct WalkToAction {
    pub x: u16,
    pub y: u16,
    pub z: i8,
}
impl HasPath for WalkToAction {
    const PATH: &'static str = paths::action::WALK_TO;
}

/// `cuo:gump/worldmap`
/// Zero-size tag: its payload is `{}` in both directions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct WorldMapWindow {}
impl HasPath for WorldMapWindow {
    const PATH: &'static str = paths::gump::WORLDMAP;
}

/// `cuo:ent/world-position`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct WorldPosition {
    pub x: u16,
    pub y: u16,
    pub z: i8,
}
impl HasPath for WorldPosition {
    const PATH: &'static str = paths::ent::WORLD_POSITION;
}

/// `cuo:input/world-single-click`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "PascalCase")]
pub struct WorldSingleClickDto {
    pub serial: u32,
    pub at_ms: u64,
}
impl HasPath for WorldSingleClickDto {
    const PATH: &'static str = paths::input::WORLD_SINGLE_CLICK;
}

/// Typed game actions: ask the HOST to perform a player action (it does the client-side
/// state change AND sends the packet, so nothing desyncs). Fire-and-forget — the command
/// buffer applies it after the callback returns. For anything not listed here, build the
/// bytes yourself and call [`crate::imports::net_send`].
pub mod actions {
    use crate::paths;
    use crate::runtime::CommandBufferBuilder;
    #[allow(unused_imports)]
    use super::*;

    /// `cuo:action/cast-spell` — emits [`super::CastSpellAction`].
    pub fn cast_spell(cmds: &mut CommandBufferBuilder, id: i32) {
        let action = super::CastSpellAction { id };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::CAST_SPELL, 0, &data);
    }

    /// `cuo:action/context-menu-reply` — emits [`super::ContextMenuReplyAction`].
    pub fn context_menu_reply(cmds: &mut CommandBufferBuilder, serial: u32, index: u16) {
        let action = super::ContextMenuReplyAction { serial, index };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::CONTEXT_MENU_REPLY, 0, &data);
    }

    /// `cuo:action/double-click` — emits [`super::DoubleClickAction`].
    pub fn double_click(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::DoubleClickAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::DOUBLE_CLICK, 0, &data);
    }

    /// `cuo:action/drop` — emits [`super::DropAction`].
    pub fn drop(cmds: &mut CommandBufferBuilder, serial: u32, x: u16, y: u16, z: i8, container: u32) {
        let action = super::DropAction { serial, x, y, z, container };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::DROP, 0, &data);
    }

    /// `cuo:action/equip` — emits [`super::EquipAction`].
    pub fn equip(cmds: &mut CommandBufferBuilder, serial: u32, layer: u8, container: u32) {
        let action = super::EquipAction { serial, layer, container };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::EQUIP, 0, &data);
    }

    /// `cuo:action/gump-close` — emits [`super::GumpCloseAction`].
    pub fn gump_close(cmds: &mut CommandBufferBuilder, gump_id: u32) {
        let action = super::GumpCloseAction { gump_id };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::GUMP_CLOSE, 0, &data);
    }

    /// `cuo:action/gump-reply` — emits [`super::GumpReplyAction`].
    pub fn gump_reply(cmds: &mut CommandBufferBuilder, gump_id: u32, button_id: i32, switches: Vec<u32>, text_entries: Vec<GumpTextEntry>) {
        let action = super::GumpReplyAction { gump_id, button_id, switches, text_entries };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::GUMP_REPLY, 0, &data);
    }

    /// `cuo:action/open-door` — emits [`super::OpenDoorAction`].
    pub fn open_door(cmds: &mut CommandBufferBuilder) {
        let action = super::OpenDoorAction {  };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::OPEN_DOOR, 0, &data);
    }

    /// `cuo:action/pickup` — emits [`super::PickupAction`].
    pub fn pickup(cmds: &mut CommandBufferBuilder, serial: u32, amount: u16) {
        let action = super::PickupAction { serial, amount };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::PICKUP, 0, &data);
    }

    /// `cuo:action/prompt-reply` — emits [`super::PromptReplyAction`].
    pub fn prompt_reply(cmds: &mut CommandBufferBuilder, text: &str, cancel: bool) {
        let action = super::PromptReplyAction { text: text.to_string(), cancel };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::PROMPT_REPLY, 0, &data);
    }

    /// `cuo:action/rename` — emits [`super::RenameAction`].
    pub fn rename(cmds: &mut CommandBufferBuilder, serial: u32, name: &str) {
        let action = super::RenameAction { serial, name: name.to_string() };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::RENAME, 0, &data);
    }

    /// `cuo:action/request-context-menu` — emits [`super::RequestContextMenuAction`].
    pub fn request_context_menu(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::RequestContextMenuAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::REQUEST_CONTEXT_MENU, 0, &data);
    }

    /// `cuo:action/request-properties` — emits [`super::RequestPropertiesAction`].
    pub fn request_properties(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::RequestPropertiesAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::REQUEST_PROPERTIES, 0, &data);
    }

    /// `cuo:action/request-skills` — emits [`super::RequestSkillsAction`].
    pub fn request_skills(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::RequestSkillsAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::REQUEST_SKILLS, 0, &data);
    }

    /// `cuo:action/request-status` — emits [`super::RequestStatusAction`].
    pub fn request_status(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::RequestStatusAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::REQUEST_STATUS, 0, &data);
    }

    /// `cuo:action/request-target` — emits [`super::RequestTargetAction`].
    pub fn request_target(cmds: &mut CommandBufferBuilder, prompt_text: &str) {
        let action = super::RequestTargetAction { prompt_text: prompt_text.to_string() };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::REQUEST_TARGET, 0, &data);
    }

    /// `cuo:action/say` — emits [`super::SayAction`].
    pub fn say(cmds: &mut CommandBufferBuilder, text: &str, hue: u16) {
        let action = super::SayAction { text: text.to_string(), hue };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::SAY, 0, &data);
    }

    /// `cuo:action/single-click` — emits [`super::SingleClickAction`].
    pub fn single_click(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::SingleClickAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::SINGLE_CLICK, 0, &data);
    }

    /// `cuo:action/target-cancel` — emits [`super::TargetCancelAction`].
    pub fn target_cancel(cmds: &mut CommandBufferBuilder) {
        let action = super::TargetCancelAction {  };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::TARGET_CANCEL, 0, &data);
    }

    /// `cuo:action/target-location` — emits [`super::TargetLocationAction`].
    pub fn target_location(cmds: &mut CommandBufferBuilder, x: u16, y: u16, z: i8, graphic: u16) {
        let action = super::TargetLocationAction { x, y, z, graphic };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::TARGET_LOCATION, 0, &data);
    }

    /// `cuo:action/target-object` — emits [`super::TargetObjectAction`].
    pub fn target_object(cmds: &mut CommandBufferBuilder, serial: u32) {
        let action = super::TargetObjectAction { serial };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::TARGET_OBJECT, 0, &data);
    }

    /// `cuo:action/toggle-war-mode` — emits [`super::ToggleWarModeAction`].
    pub fn toggle_war_mode(cmds: &mut CommandBufferBuilder) {
        let action = super::ToggleWarModeAction {  };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::TOGGLE_WAR_MODE, 0, &data);
    }

    /// `cuo:action/use-skill` — emits [`super::UseSkillAction`].
    pub fn use_skill(cmds: &mut CommandBufferBuilder, id: i32) {
        let action = super::UseSkillAction { id };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::USE_SKILL, 0, &data);
    }

    /// `cuo:action/walk` — emits [`super::WalkAction`].
    pub fn walk(cmds: &mut CommandBufferBuilder, direction: u8, run: bool) {
        let action = super::WalkAction { direction, run };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::WALK, 0, &data);
    }

    /// `cuo:action/walk-to` — emits [`super::WalkToAction`].
    pub fn walk_to(cmds: &mut CommandBufferBuilder, x: u16, y: u16, z: i8) {
        let action = super::WalkToAction { x, y, z };
        let data = serde_json::to_vec(&action).unwrap_or_default();
        cmds.emit_event(paths::action::WALK_TO, 0, &data);
    }
}

