//! The C# signature table the ClassicUO host uses to bridge wasm32-wasip2 components
//! onto the JSON host functions: every
//! imported function of `host` / `packets` / `assets` / `actions` and every function the
//! world exports, as a tree of `WitType` values the host's generic ComponentValue <->
//! JSON converter walks. `WitType` / `WitFunction` are defined host-side.

use anyhow::{bail, Context, Result};
use std::collections::HashSet;
use std::fmt::Write as _;
use wit_parser::{PackageId, Resolve, Type, TypeDefKind, TypeId, TypeOwner, WorldItem, WorldKey};

const HEADER: &str = "\
// @generated by external/classicuo-mods-sdk/tools/wit-p1-gen from wit/cuo-mod.wit —
// do not edit. Regenerate: make gen-mod-wit-sig (repo root).
// The p2 component bridge's signature table (Modding/CuoComponentImports.cs).
";

/// `exports`: the world's own export functions (the included tinyecs:modding/guest
/// exports are the generic backend's business, not this table's).
pub fn emit(resolve: &Resolve, pkg: PackageId, interfaces: &[&str], world: &str, exports: &[&str]) -> Result<String> {
    let package = &resolve.packages[pkg];
    let pkg_name = format!("{}:{}", package.name.namespace, package.name.name);
    let version = package.name.version.as_ref().map(|v| v.to_string()).unwrap_or_default();

    let mut g = Cs { resolve, fields: String::new(), done: HashSet::new() };
    let mut fns = String::new();
    for name in interfaces {
        let iid = *package.interfaces.get(*name).with_context(|| format!("interface `{name}`"))?;
        let iface = &resolve.interfaces[iid];
        for (fname, f) in &iface.functions {
            let params: Result<Vec<_>> = f.params.iter().map(|p| g.ty(&p.ty)).collect();
            let result = match &f.result {
                Some(t) => g.ty(t)?,
                None => "null".into(),
            };
            writeln!(
                fns,
                "        new(\"{pkg_name}/{name}\", \"{fname}\", [{}], {result}),",
                params?.join(", ")
            )?;
        }
    }

    let wid = *package.worlds.get(world).with_context(|| format!("world `{world}`"))?;
    let mut out_exports = String::new();
    for (key, item) in &resolve.worlds[wid].exports {
        let (WorldKey::Name(fname), WorldItem::Function(f)) = (key, item) else { continue };
        if !exports.contains(&fname.as_str()) {
            continue;
        }
        let params: Result<Vec<_>> = f.params.iter().map(|p| g.ty(&p.ty)).collect();
        let result = match &f.result {
            Some(t) => g.ty(t)?,
            None => "null".into(),
        };
        writeln!(out_exports, "        new(\"\", \"{fname}\", [{}], {result}),", params?.join(", "))?;
    }

    let mut out = String::from(HEADER);
    out.push_str("\nnamespace ClassicUO.Ecs.Modding;\n\n");
    out.push_str("internal static class CuoWitSignatures\n{\n");
    writeln!(out, "    public const string Version = \"{version}\";\n")?;
    out.push_str(&g.fields);
    out.push_str("\n    /// Host imports, in WIT order. Interface = \"<package>/<interface>\" (no version).\n");
    out.push_str("    public static readonly WitFunction[] Imports =\n    [\n");
    out.push_str(&fns);
    out.push_str("    ];\n\n    /// Functions the world exports (beyond tinyecs:modding/guest).\n");
    out.push_str("    public static readonly WitFunction[] Exports =\n    [\n");
    out.push_str(&out_exports);
    out.push_str("    ];\n}\n");
    Ok(out)
}

struct Cs<'a> {
    resolve: &'a Resolve,
    /// One static field per named record / enum / variant, dependencies first.
    fields: String,
    done: HashSet<TypeId>,
}

impl Cs<'_> {
    fn ty(&mut self, t: &Type) -> Result<String> {
        Ok(match t {
            Type::Bool => "WitType.Bool".into(),
            Type::U8 => "WitType.U8".into(),
            Type::U16 => "WitType.U16".into(),
            Type::U32 => "WitType.U32".into(),
            Type::U64 => "WitType.U64".into(),
            Type::S8 => "WitType.S8".into(),
            Type::S16 => "WitType.S16".into(),
            Type::S32 => "WitType.S32".into(),
            Type::S64 => "WitType.S64".into(),
            Type::F32 => "WitType.F32".into(),
            Type::F64 => "WitType.F64".into(),
            Type::Char => "WitType.Char".into(),
            Type::String => "WitType.String".into(),
            Type::ErrorContext => bail!("error-context is not supported"),
            Type::Id(id) => self.id(*id)?,
        })
    }

    fn id(&mut self, id: TypeId) -> Result<String> {
        let td = &self.resolve.types[id];
        match &td.kind {
            TypeDefKind::Type(inner) => return self.ty(inner),
            TypeDefKind::Option(t) => return Ok(format!("WitType.Option({})", self.ty(t)?)),
            TypeDefKind::List(t) => return Ok(format!("WitType.List({})", self.ty(t)?)),
            TypeDefKind::Tuple(tt) => {
                let parts: Result<Vec<_>> = tt.types.iter().map(|t| self.ty(t)).collect();
                return Ok(format!("WitType.Tuple({})", parts?.join(", ")));
            }
            _ => {}
        }

        let name = td.name.as_deref().context("anonymous record / enum / variant")?;
        let iface = match td.owner {
            TypeOwner::Interface(i) => self.resolve.interfaces[i].name.clone().unwrap_or_default(),
            _ => String::new(),
        };
        let field = format!("{}_{}", pascal(&iface), pascal(name));
        if !self.done.insert(id) {
            return Ok(field);
        }
        let init = match &td.kind {
            TypeDefKind::Enum(e) => {
                let cases: Vec<String> = e.cases.iter().map(|c| format!("\"{}\"", c.name)).collect();
                format!("WitType.Enum({})", cases.join(", "))
            }
            TypeDefKind::Record(r) => {
                let mut fs = Vec::new();
                for f in &r.fields {
                    fs.push(format!("(\"{}\", {})", f.name, self.ty(&f.ty)?));
                }
                format!("WitType.Record({})", fs.join(", "))
            }
            TypeDefKind::Variant(v) => {
                let mut cs = Vec::new();
                for c in &v.cases {
                    let p = match &c.ty {
                        Some(t) => self.ty(t)?,
                        None => "null".into(),
                    };
                    cs.push(format!("(\"{}\", {p})", c.name));
                }
                format!("WitType.Variant({})", cs.join(", "))
            }
            other => bail!("unsupported type kind for `{name}`: {other:?}"),
        };
        writeln!(self.fields, "    public static readonly WitType {field} = {init};")?;
        Ok(field)
    }
}

fn pascal(kebab: &str) -> String {
    kebab
        .split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
