//! Typed host calls: the ClassicUO host's generated dispatch for the `host` / `packets` /
//! `assets` / `actions` imports. One typed C# interface (`ICuoHostApi`, implemented by the
//! host) and, per WIT type, the codecs every wire needs:
//!   - shared (native + wasm guest): Encoding.Typed binary (the guest relay: LE fixed ints,
//!     strings / lists u32-length-prefixed, enum / variant case u8 (u16 past 255), option
//!     u8 tag, records / tuples in field order) and the p1 JSON wire (the fallback);
//!   - native only: Cm.ComponentValue lift / lower (the in-process component host).
//! Every function dispatches straight into the interface — no per-call JSON.

use anyhow::{bail, Context, Result};
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use wit_parser::{PackageId, Resolve, Type, TypeDefKind, TypeId, TypeOwner};

const HEADER: &str = "\
// @generated by external/classicuo-mods-sdk/tools/wit-p1-gen from wit/cuo-mod.wit —
// do not edit. Regenerate: make gen-mod-wit-sig (repo root).
";

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord)]
enum T {
    Bool,
    U8,
    U16,
    U32,
    U64,
    S8,
    S16,
    S32,
    S64,
    F32,
    F64,
    Str,
    List(Box<T>),
    Opt(Box<T>),
    Tuple(Vec<T>),
    Named(usize),
}

enum Kind {
    Record(Vec<(String, T)>),
    Enum(Vec<String>),
    Variant(Vec<(String, Option<T>)>),
}

struct Named {
    iface: String,
    name: String,
    kind: Kind,
}

struct Func {
    full: String,
    name: String,
    params: Vec<(String, T)>,
    result: Option<T>,
}

struct Model<'a> {
    resolve: &'a Resolve,
    named: Vec<Named>,
    ids: BTreeMap<TypeId, usize>,
}

impl Model<'_> {
    fn ty(&mut self, t: &Type) -> Result<T> {
        Ok(match t {
            Type::Bool => T::Bool,
            Type::U8 => T::U8,
            Type::U16 => T::U16,
            Type::U32 => T::U32,
            Type::U64 => T::U64,
            Type::S8 => T::S8,
            Type::S16 => T::S16,
            Type::S32 => T::S32,
            Type::S64 => T::S64,
            Type::F32 => T::F32,
            Type::F64 => T::F64,
            Type::String => T::Str,
            Type::Char => bail!("char is not supported in a host call"),
            Type::ErrorContext => bail!("error-context is not supported"),
            Type::Id(id) => self.id(*id)?,
        })
    }

    fn id(&mut self, id: TypeId) -> Result<T> {
        let td = &self.resolve.types[id];
        match &td.kind {
            TypeDefKind::Type(inner) => return self.ty(inner),
            TypeDefKind::Option(t) => return Ok(T::Opt(Box::new(self.ty(t)?))),
            TypeDefKind::List(t) => return Ok(T::List(Box::new(self.ty(t)?))),
            TypeDefKind::Tuple(tt) => return Ok(T::Tuple(tt.types.iter().map(|t| self.ty(t)).collect::<Result<_>>()?)),
            _ => {}
        }
        if let Some(&k) = self.ids.get(&id) {
            return Ok(T::Named(k));
        }
        let name = td.name.clone().context("anonymous record / enum / variant")?;
        let iface = match td.owner {
            TypeOwner::Interface(i) => self.resolve.interfaces[i].name.clone().unwrap_or_default(),
            _ => String::new(),
        };
        let kind = match &td.kind {
            TypeDefKind::Enum(e) => Kind::Enum(e.cases.iter().map(|c| c.name.clone()).collect()),
            TypeDefKind::Record(r) => {
                Kind::Record(r.fields.iter().map(|f| Ok((f.name.clone(), self.ty(&f.ty)?))).collect::<Result<_>>()?)
            }
            TypeDefKind::Variant(v) => Kind::Variant(
                v.cases
                    .iter()
                    .map(|c| Ok((c.name.clone(), c.ty.as_ref().map(|t| self.ty(t)).transpose()?)))
                    .collect::<Result<_>>()?,
            ),
            other => bail!("unsupported type kind for `{name}`: {other:?}"),
        };
        self.named.push(Named { iface, name, kind });
        let k = self.named.len() - 1;
        self.ids.insert(id, k);
        Ok(T::Named(k))
    }

    // ── naming ──

    fn cs(&self, t: &T) -> String {
        match t {
            T::Bool => "bool".into(),
            T::U8 => "byte".into(),
            T::U16 => "ushort".into(),
            T::U32 => "uint".into(),
            T::U64 => "ulong".into(),
            T::S8 => "sbyte".into(),
            T::S16 => "short".into(),
            T::S32 => "int".into(),
            T::S64 => "long".into(),
            T::F32 => "float".into(),
            T::F64 => "double".into(),
            T::Str => "string".into(),
            T::List(e) if **e == T::U8 => "byte[]".into(),
            T::List(e) => format!("{}[]", self.cs(e)),
            T::Opt(e) => format!("{}?", self.cs(e)),
            T::Tuple(ts) => format!("({})", ts.iter().map(|t| self.cs(t)).collect::<Vec<_>>().join(", ")),
            T::Named(k) => {
                let n = &self.named[*k];
                format!("CuoWit.{}.{}", pascal(&n.iface), pascal(&n.name))
            }
        }
    }

    /// The codec-helper suffix of a non-primitive type.
    fn mangle(&self, t: &T) -> String {
        match t {
            T::Bool => "Bool".into(),
            T::U8 => "U8".into(),
            T::U16 => "U16".into(),
            T::U32 => "U32".into(),
            T::U64 => "U64".into(),
            T::S8 => "S8".into(),
            T::S16 => "S16".into(),
            T::S32 => "S32".into(),
            T::S64 => "S64".into(),
            T::F32 => "F32".into(),
            T::F64 => "F64".into(),
            T::Str => "Str".into(),
            T::List(e) if **e == T::U8 => "Bytes".into(),
            T::List(e) => format!("List_{}", self.mangle(e)),
            T::Opt(e) => format!("Opt_{}", self.mangle(e)),
            T::Tuple(ts) => format!("Tup{}_{}", ts.len(), ts.iter().map(|t| self.mangle(t)).collect::<Vec<_>>().join("_")),
            T::Named(k) => {
                let n = &self.named[*k];
                format!("{}_{}", pascal(&n.iface), pascal(&n.name))
            }
        }
    }

    // Every non-primitive type reachable from `t`, dependencies first.
    fn collect(&self, t: &T, seen: &mut HashSet<String>, out: &mut Vec<T>) {
        match t {
            T::List(e) if **e != T::U8 => self.collect(e, seen, out),
            T::Opt(e) => self.collect(e, seen, out),
            T::Tuple(ts) => ts.iter().for_each(|t| self.collect(t, seen, out)),
            T::Named(k) => match &self.named[*k].kind {
                Kind::Record(fs) => fs.iter().for_each(|(_, t)| self.collect(t, seen, out)),
                Kind::Variant(cs) => cs.iter().filter_map(|(_, t)| t.as_ref()).for_each(|t| self.collect(t, seen, out)),
                Kind::Enum(_) => {}
            },
            _ => {}
        }
        if !is_prim(t) && seen.insert(self.mangle(t)) {
            out.push(t.clone());
        }
    }

    // ── binary (Encoding.Typed) ──

    fn bin_read(&self, t: &T) -> String {
        match t {
            T::Bool => "r.Bool()".into(),
            T::U8 => "r.U8()".into(),
            T::U16 => "r.U16()".into(),
            T::U32 => "r.U32()".into(),
            T::U64 => "r.U64()".into(),
            T::S8 => "r.S8()".into(),
            T::S16 => "r.S16()".into(),
            T::S32 => "r.S32()".into(),
            T::S64 => "r.S64()".into(),
            T::F32 => "r.F32()".into(),
            T::F64 => "r.F64()".into(),
            T::Str => "r.Str()".into(),
            T::List(e) if **e == T::U8 => "r.Bytes()".into(),
            _ => format!("ReadBin_{}(ref r)", self.mangle(t)),
        }
    }

    fn bin_write(&self, t: &T, v: &str) -> String {
        match t {
            T::Bool => format!("w.Bool({v})"),
            T::U8 => format!("w.U8({v})"),
            T::U16 => format!("w.U16({v})"),
            T::U32 => format!("w.U32({v})"),
            T::U64 => format!("w.U64({v})"),
            T::S8 => format!("w.S8({v})"),
            T::S16 => format!("w.S16({v})"),
            T::S32 => format!("w.S32({v})"),
            T::S64 => format!("w.S64({v})"),
            T::F32 => format!("w.F32({v})"),
            T::F64 => format!("w.F64({v})"),
            T::Str => format!("w.Str({v})"),
            T::List(e) if **e == T::U8 => format!("w.Bytes({v})"),
            _ => format!("WriteBin_{}(w, {v})", self.mangle(t)),
        }
    }

    // ── p1 JSON (docs/p1-wire.md) ──

    fn json_read(&self, t: &T, e: &str) -> String {
        match t {
            T::Bool => format!("{e}.GetBoolean()"),
            T::U8 => format!("{e}.GetByte()"),
            T::U16 => format!("{e}.GetUInt16()"),
            T::U32 => format!("{e}.GetUInt32()"),
            T::U64 => format!("CuoModArgs.U64({e})"),
            T::S8 => format!("{e}.GetSByte()"),
            T::S16 => format!("{e}.GetInt16()"),
            T::S32 => format!("{e}.GetInt32()"),
            T::S64 => format!("CuoModArgs.S64({e})"),
            T::F32 => format!("{e}.GetSingle()"),
            T::F64 => format!("{e}.GetDouble()"),
            T::Str => format!("({e}.GetString() ?? string.Empty)"),
            T::List(x) if **x == T::U8 => format!("CuoModArgs.Base64({e})"),
            _ => format!("ReadJson_{}({e})", self.mangle(t)),
        }
    }

    fn json_write(&self, t: &T, v: &str) -> String {
        match t {
            T::Bool => format!("w.WriteBooleanValue({v})"),
            T::U64 => format!("CuoModArgs.WriteU64(w, {v})"),
            T::S64 => format!("CuoModArgs.WriteS64(w, {v})"),
            T::U8 | T::U16 | T::U32 | T::S8 | T::S16 | T::S32 | T::F32 | T::F64 => format!("w.WriteNumberValue({v})"),
            T::Str => format!("w.WriteStringValue({v})"),
            T::List(e) if **e == T::U8 => format!("w.WriteBase64StringValue({v})"),
            _ => format!("WriteJson_{}(w, {v})", self.mangle(t)),
        }
    }

    // ── Cm.ComponentValue (native component host) ──

    fn lift(&self, t: &T, v: &str) -> String {
        match t {
            T::Bool => format!("{v}.ToBoolean()"),
            T::U8 => format!("{v}.ToByte()"),
            T::U16 => format!("{v}.ToUInt16()"),
            T::U32 => format!("{v}.ToUInt32()"),
            T::U64 => format!("{v}.ToUInt64()"),
            T::S8 => format!("{v}.ToSByte()"),
            T::S16 => format!("{v}.ToInt16()"),
            T::S32 => format!("{v}.ToInt32()"),
            T::S64 => format!("{v}.ToInt64()"),
            T::F32 => format!("{v}.ToFloat()"),
            T::F64 => format!("{v}.ToDouble()"),
            T::Str => format!("Encoding.UTF8.GetString({v}.ToUtf8Span())"),
            T::List(e) if **e == T::U8 => format!("CuoComponentImports.ReadBytes({v})"),
            _ => format!("Lift_{}({v})", self.mangle(t)),
        }
    }

    fn lower(&self, t: &T, v: &str) -> String {
        match t {
            T::Bool => format!("Cm.ComponentValue.CreateBoolean({v})"),
            T::U8 => format!("Cm.ComponentValue.CreateByte({v})"),
            T::U16 => format!("Cm.ComponentValue.CreateUInt16({v})"),
            T::U32 => format!("Cm.ComponentValue.CreateUInt32({v})"),
            T::U64 => format!("Cm.ComponentValue.CreateUInt64({v})"),
            T::S8 => format!("Cm.ComponentValue.CreateSByte({v})"),
            T::S16 => format!("Cm.ComponentValue.CreateInt16({v})"),
            T::S32 => format!("Cm.ComponentValue.CreateInt32({v})"),
            T::S64 => format!("Cm.ComponentValue.CreateInt64({v})"),
            T::F32 => format!("Cm.ComponentValue.CreateFloat({v})"),
            T::F64 => format!("Cm.ComponentValue.CreateDouble({v})"),
            T::Str => format!("Cm.ComponentValue.CreateString({v} ?? string.Empty, externallyOwned: true)"),
            T::List(e) if **e == T::U8 => format!("CuoComponentImports.ByteList({v})"),
            _ => format!("Lower_{}({v})", self.mangle(t)),
        }
    }

    // ── helper bodies ──

    fn helpers_shared(&self, t: &T, out: &mut String) -> Result<()> {
        let m = self.mangle(t);
        let cs = self.cs(t);
        match t {
            T::List(e) => {
                let ec = self.cs(e);
                writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n    {{")?;
                writeln!(out, "        var n = r.Count();\n        var a = n == 0 ? Array.Empty<{ec}>() : new {};", array_new(&ec, "n"))?;
                writeln!(out, "        for (var i = 0; i < n; i++)\n            a[i] = {};\n        return a;\n    }}\n", self.bin_read(e))?;
                writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v)\n    {{")?;
                writeln!(out, "        v ??= Array.Empty<{ec}>();\n        w.Count(v.Length);")?;
                writeln!(out, "        foreach (var x in v)\n            {};\n    }}\n", self.bin_write(e, "x"))?;
                writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e)\n    {{")?;
                writeln!(out, "        if (e.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)\n            return Array.Empty<{ec}>();")?;
                writeln!(out, "        var a = new {};", array_new(&ec, "e.GetArrayLength()"))?;
                writeln!(out, "        for (var i = 0; i < a.Length; i++)\n            a[i] = {};\n        return a;\n    }}\n", self.json_read(e, "e[i]"))?;
                writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v)\n    {{")?;
                writeln!(out, "        w.WriteStartArray();\n        foreach (var x in v ?? Array.Empty<{ec}>())\n            {};\n        w.WriteEndArray();\n    }}\n", self.json_write(e, "x"))?;
            }
            T::Opt(e) => {
                writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n        => r.Tag() ? {} : null;\n", self.bin_read(e))?;
                writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v)\n    {{")?;
                writeln!(out, "        if (v is {{ }} x)\n        {{\n            w.U8(1);\n            {};\n        }}\n        else\n            w.U8(0);\n    }}\n", self.bin_write(e, "x"))?;
                writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e)\n        => e.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined ? null : {};\n", self.json_read(e, "e"))?;
                writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v)\n    {{")?;
                writeln!(out, "        if (v is {{ }} x)\n            {};\n        else\n            w.WriteNullValue();\n    }}\n", self.json_write(e, "x"))?;
            }
            T::Tuple(ts) => {
                let reads: Vec<String> = ts.iter().map(|t| self.bin_read(t)).collect();
                writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n    {{")?;
                for (i, rd) in reads.iter().enumerate() {
                    writeln!(out, "        var i{i} = {rd};")?;
                }
                writeln!(out, "        return ({});\n    }}\n", (0..ts.len()).map(|i| format!("i{i}")).collect::<Vec<_>>().join(", "))?;
                writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v)\n    {{")?;
                for (i, t) in ts.iter().enumerate() {
                    writeln!(out, "        {};", self.bin_write(t, &format!("v.Item{}", i + 1)))?;
                }
                writeln!(out, "    }}\n")?;
                let jr: Vec<String> = ts.iter().enumerate().map(|(i, t)| self.json_read(t, &format!("e[{i}]"))).collect();
                writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e)\n        => ({});\n", jr.join(", "))?;
                writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v)\n    {{\n        w.WriteStartArray();")?;
                for (i, t) in ts.iter().enumerate() {
                    writeln!(out, "        {};", self.json_write(t, &format!("v.Item{}", i + 1)))?;
                }
                writeln!(out, "        w.WriteEndArray();\n    }}\n")?;
            }
            T::Named(k) => {
                let n = &self.named[*k];
                match &n.kind {
                    Kind::Record(fs) => {
                        writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n    {{")?;
                        for (i, (_, ft)) in fs.iter().enumerate() {
                            writeln!(out, "        var f{i} = {};", self.bin_read(ft))?;
                        }
                        writeln!(out, "        return new {cs}({});\n    }}\n", (0..fs.len()).map(|i| format!("f{i}")).collect::<Vec<_>>().join(", "))?;
                        writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v)\n    {{")?;
                        for (f, ft) in fs {
                            writeln!(out, "        {};", self.bin_write(ft, &format!("v.{}", pascal(f))))?;
                        }
                        writeln!(out, "    }}\n")?;
                        let jr: Vec<String> =
                            fs.iter().map(|(f, ft)| self.json_read(ft, &format!("CuoModArgs.Field(e, \"{f}\"u8)"))).collect();
                        writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e)\n        => new {cs}({});\n", jr.join(", "))?;
                        writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v)\n    {{\n        w.WriteStartObject();")?;
                        for (f, ft) in fs {
                            writeln!(out, "        w.WritePropertyName(\"{f}\"u8);\n        {};", self.json_write(ft, &format!("v.{}", pascal(f))))?;
                        }
                        writeln!(out, "        w.WriteEndObject();\n    }}\n")?;
                    }
                    Kind::Enum(cases) => {
                        let wide = cases.len() > 255;
                        let (rd, wr) = if wide { ("r.U16()", "w.U16((ushort)v)") } else { ("r.U8()", "w.U8((byte)v)") };
                        writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n    {{")?;
                        writeln!(out, "        var k = {rd};\n        return k < {} ? ({cs})k : throw CuoBinReader.BadCase(\"{}\", k);\n    }}\n", cases.len(), n.name)?;
                        writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v) => {wr};\n")?;
                        writeln!(out, "    private static readonly string[] Cases_{m} = [{}];\n", cases.iter().map(|c| format!("\"{c}\"")).collect::<Vec<_>>().join(", "))?;
                        writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e) => ({cs})CuoModArgs.Enum(e, Cases_{m});\n")?;
                        writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v) => w.WriteStringValue(Cases_{m}[(int)v]);\n")?;
                    }
                    Kind::Variant(cases) => {
                        let wide = cases.len() > 255;
                        writeln!(out, "    internal static {cs} ReadBin_{m}(ref CuoBinReader r)\n    {{")?;
                        writeln!(out, "        var k = {};\n        switch (k)\n        {{", if wide { "r.U16()" } else { "r.U8()" })?;
                        for (i, (c, pt)) in cases.iter().enumerate() {
                            let tag = format!("{cs}.Tag.{}", pascal(c));
                            match pt {
                                Some(pt) => writeln!(out, "            case {i}: return new {cs} {{ Case = {tag}, {} = {} }};", pascal(c), self.bin_read(pt))?,
                                None => writeln!(out, "            case {i}: return new {cs} {{ Case = {tag} }};")?,
                            }
                        }
                        writeln!(out, "            default: throw CuoBinReader.BadCase(\"{}\", k);\n        }}\n    }}\n", n.name)?;
                        writeln!(out, "    internal static void WriteBin_{m}(CuoBinWriter w, {cs} v)\n    {{")?;
                        writeln!(out, "        {};\n        switch (v.Case)\n        {{", if wide { "w.U16((ushort)v.Case)" } else { "w.U8((byte)v.Case)" })?;
                        for (c, pt) in cases {
                            if let Some(pt) = pt {
                                writeln!(out, "            case {cs}.Tag.{}: {}; break;", pascal(c), self.bin_write(pt, &format!("v.{}", pascal(c))))?;
                            }
                        }
                        writeln!(out, "        }}\n    }}\n")?;
                        writeln!(out, "    internal static {cs} ReadJson_{m}(JsonElement e)\n    {{")?;
                        writeln!(out, "        var (name, p) = CuoModArgs.VariantCase(e);")?;
                        for (c, pt) in cases {
                            let tag = format!("{cs}.Tag.{}", pascal(c));
                            match pt {
                                Some(pt) => writeln!(out, "        if (name == \"{c}\") return new {cs} {{ Case = {tag}, {} = {} }};", pascal(c), self.json_read(pt, "p"))?,
                                None => writeln!(out, "        if (name == \"{c}\") return new {cs} {{ Case = {tag} }};")?,
                            }
                        }
                        writeln!(out, "        throw new FormatException($\"unknown {} case '{{name}}'\");\n    }}\n", n.name)?;
                        writeln!(out, "    internal static void WriteJson_{m}(Utf8JsonWriter w, {cs} v)\n    {{\n        w.WriteStartObject();\n        switch (v.Case)\n        {{")?;
                        for (c, pt) in cases {
                            let body = match pt {
                                Some(pt) => self.json_write(pt, &format!("v.{}", pascal(c))),
                                None => "w.WriteNullValue()".into(),
                            };
                            writeln!(out, "            case {cs}.Tag.{}: w.WritePropertyName(\"{c}\"u8); {body}; break;", pascal(c))?;
                        }
                        writeln!(out, "        }}\n        w.WriteEndObject();\n    }}\n")?;
                    }
                }
            }
            _ => {}
        }
        Ok(())
    }

    fn helpers_cm(&self, t: &T, out: &mut String) -> Result<()> {
        let m = self.mangle(t);
        let cs = self.cs(t);
        match t {
            T::List(e) => {
                let ec = self.cs(e);
                writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n    {{")?;
                writeln!(out, "        var l = v.ToListBuilder();\n        var a = l.Length == 0 ? Array.Empty<{ec}>() : new {};", array_new(&ec, "l.Length"))?;
                writeln!(out, "        for (var i = 0; i < a.Length; i++)\n            a[i] = {};\n        return a;\n    }}\n", self.lift(e, "l[i]"))?;
                writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v)\n    {{")?;
                writeln!(out, "        v ??= Array.Empty<{ec}>();\n        var l = new Cm.ListBuilder(v.Length);")?;
                writeln!(out, "        for (var i = 0; i < v.Length; i++)\n            l[i] = {};\n        return new Cm.ComponentValue(l, externallyOwned: true);\n    }}\n", self.lower(e, "v[i]"))?;
            }
            T::Opt(e) => {
                writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n        => v.ToOption() is {{ }} x ? {} : null;\n", self.lift(e, "x"))?;
                writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v)\n        => Cm.ComponentValue.CreateOption(v is {{ }} x ? {} : null);\n", self.lower(e, "x"))?;
            }
            T::Tuple(ts) => {
                writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n    {{\n        var copy = v;\n        var items = copy.ToTuple();")?;
                let parts: Vec<String> = ts.iter().enumerate().map(|(i, t)| self.lift(t, &format!("items[{i}]"))).collect();
                writeln!(out, "        return ({});\n    }}\n", parts.join(", "))?;
                writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v)\n    {{")?;
                writeln!(out, "        Span<Cm.ComponentValue> items = stackalloc Cm.ComponentValue[{}];", ts.len())?;
                for (i, t) in ts.iter().enumerate() {
                    writeln!(out, "        items[{i}] = {};", self.lower(t, &format!("v.Item{}", i + 1)))?;
                }
                writeln!(out, "        return Cm.ComponentValue.CreateTuple(items);\n    }}\n")?;
            }
            T::Named(k) => {
                let n = &self.named[*k];
                match &n.kind {
                    Kind::Record(fs) => {
                        writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n    {{\n        var r = v.ToRecordBuilder();")?;
                        let parts: Vec<String> = fs.iter().enumerate().map(|(i, (_, t))| self.lift(t, &format!("r.Get({i})"))).collect();
                        writeln!(out, "        return new {cs}({});\n    }}\n", parts.join(", "))?;
                        writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v)\n    {{")?;
                        writeln!(out, "        var r = new Cm.RecordBuilder({}, disposeNames: false);", fs.len())?;
                        for (i, (f, t)) in fs.iter().enumerate() {
                            writeln!(out, "        r.Set({i}, new Cm.ByteVector(\"{f}\"u8), {});", self.lower(t, &format!("v.{}", pascal(f))))?;
                        }
                        writeln!(out, "        return Cm.ComponentValue.CreateRecord(r, externallyOwned: true);\n    }}\n")?;
                    }
                    Kind::Enum(cases) => {
                        writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n    {{\n        var s = CuoComponentImports.RawName(v).Span;")?;
                        for (i, c) in cases.iter().enumerate() {
                            writeln!(out, "        if (s.SequenceEqual(\"{c}\"u8)) return ({cs}){i};")?;
                        }
                        writeln!(out, "        throw new ModCallException($\"unknown {} case '{{Encoding.UTF8.GetString(s)}}'\");\n    }}\n", n.name)?;
                        writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v) => (int)v switch\n    {{")?;
                        for (i, c) in cases.iter().enumerate() {
                            writeln!(out, "        {i} => CuoComponentImports.RawEnum(new Cm.ByteVector(\"{c}\"u8)),")?;
                        }
                        writeln!(out, "        _ => throw new ModCallException($\"{} value {{v}} out of range\"),\n    }};\n", n.name)?;
                    }
                    Kind::Variant(cases) => {
                        writeln!(out, "    internal static {cs} Lift_{m}(in Cm.ComponentValue v)\n    {{")?;
                        writeln!(out, "        var (disc, payload) = v.ToVariantRaw();\n        var s = disc.Span;")?;
                        for (c, pt) in cases {
                            let tag = format!("{cs}.Tag.{}", pascal(c));
                            match pt {
                                Some(pt) => writeln!(
                                    out,
                                    "        if (s.SequenceEqual(\"{c}\"u8)) return new {cs} {{ Case = {tag}, {} = {} }};",
                                    pascal(c),
                                    self.lift(pt, "payload!.Value")
                                )?,
                                None => writeln!(out, "        if (s.SequenceEqual(\"{c}\"u8)) return new {cs} {{ Case = {tag} }};")?,
                            }
                        }
                        writeln!(out, "        throw new ModCallException($\"unknown {} case '{{Encoding.UTF8.GetString(s)}}'\");\n    }}\n", n.name)?;
                        writeln!(out, "    internal static Cm.ComponentValue Lower_{m}({cs} v) => v.Case switch\n    {{")?;
                        for (c, pt) in cases {
                            let p = match pt {
                                Some(pt) => self.lower(pt, &format!("v.{}", pascal(c))),
                                None => "null".into(),
                            };
                            writeln!(
                                out,
                                "        {cs}.Tag.{} => Cm.ComponentValue.CreateVariant(Cm.ByteVector.Constant(\"{c}\"), {p}, copyDiscriminant: true),",
                                pascal(c)
                            )?;
                        }
                        writeln!(out, "        _ => throw new ModCallException($\"{} case {{v.Case}} out of range\"),\n    }};\n", n.name)?;
                    }
                }
            }
            _ => {}
        }
        Ok(())
    }
}

fn is_prim(t: &T) -> bool {
    !matches!(t, T::List(e) if **e != T::U8) && !matches!(t, T::Opt(_) | T::Tuple(_) | T::Named(_))
}

// `X[len]` for `new`, for an element type that may itself be an array
// (`byte[]` -> `byte[len][]`).
fn array_new(elem: &str, len: &str) -> String {
    match elem.find('[') {
        Some(i) if !elem.starts_with('(') => format!("{}[{len}]{}", &elem[..i], &elem[i..]),
        _ => format!("{elem}[{len}]"),
    }
}

const KEYWORDS: &[&str] = &[
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
    "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
    "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
    "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected",
    "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
    "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
    "using", "virtual", "void", "volatile", "while",
];

fn camel(kebab: &str) -> String {
    let p = pascal(kebab);
    let mut c = p.chars();
    let s = match c.next() {
        Some(f) => f.to_ascii_lowercase().to_string() + c.as_str(),
        None => String::new(),
    };
    if KEYWORDS.contains(&s.as_str()) {
        format!("@{s}")
    } else {
        s
    }
}

pub fn pascal(kebab: &str) -> String {
    kebab
        .split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Returns (shared file, native Cm file).
pub fn emit(resolve: &Resolve, pkg: PackageId, interfaces: &[&str]) -> Result<(String, String)> {
    let package = &resolve.packages[pkg];
    let pkg_name = format!("{}:{}", package.name.namespace, package.name.name);
    let mut m = Model { resolve, named: Vec::new(), ids: BTreeMap::new() };
    let mut fns = Vec::new();
    for name in interfaces {
        let iid = *package.interfaces.get(*name).with_context(|| format!("interface `{name}`"))?;
        for (fname, f) in &resolve.interfaces[iid].functions {
            let params = f.params.iter().map(|p| Ok((p.name.clone(), m.ty(&p.ty)?))).collect::<Result<Vec<_>>>()?;
            let result = f.result.as_ref().map(|t| m.ty(t)).transpose()?;
            fns.push(Func { full: format!("{pkg_name}/{name}#{fname}"), name: fname.clone(), params, result });
        }
    }

    // Every helper type, dependencies first.
    let mut seen = HashSet::new();
    let mut order = Vec::new();
    for f in &fns {
        for (_, t) in &f.params {
            m.collect(t, &mut seen, &mut order);
        }
        if let Some(t) = &f.result {
            m.collect(t, &mut seen, &mut order);
        }
    }

    let sig = |f: &Func| -> String {
        let ret = f.result.as_ref().map_or("void".to_string(), |t| m.cs(t));
        let ps: Vec<String> = f.params.iter().map(|(n, t)| format!("{} {}", m.cs(t), camel(n))).collect();
        let mut all = vec!["ModHostContext mod".to_string()];
        all.extend(ps);
        format!("{ret} {}({})", pascal(&f.name), all.join(", "))
    };
    let call_args = |f: &Func| -> String {
        let mut a = vec!["mod".to_string()];
        a.extend((0..f.params.len()).map(|i| format!("a{i}")));
        a.join(", ")
    };

    // ── shared ──
    let mut s = String::from(HEADER);
    s.push_str(
        "// Typed host calls (host / packets / assets / actions): the interface the host implements,\n\
         // the WIT types, and the Encoding.Typed binary + p1 JSON dispatch onto it (the native\n\
         // component host's Cm.ComponentValue twin is CuoHostCallsCm.g.cs).\n\n\
         #nullable enable\n\nusing System;\nusing System.Text.Json;\nusing TinyEcs.Bevy.Modding;\n\n\
         namespace ClassicUO.Ecs.Modding.Api;\n\n",
    );

    // types
    s.push_str("/// The WIT types of the host-call interfaces, one nested class per interface.\ninternal static class CuoWit\n{\n");
    let mut ifaces: Vec<&str> = m.named.iter().map(|n| n.iface.as_str()).collect();
    ifaces.dedup();
    let mut seen_iface = HashSet::new();
    for iface in ifaces {
        if !seen_iface.insert(iface) {
            continue;
        }
        writeln!(s, "    internal static class {}\n    {{", pascal(iface))?;
        for n in m.named.iter().filter(|n| n.iface == iface) {
            let tn = pascal(&n.name);
            match &n.kind {
                Kind::Record(fs) => {
                    let ps: Vec<String> = fs.iter().map(|(f, t)| format!("{} {}", m.cs(t), pascal(f))).collect();
                    writeln!(s, "        internal readonly record struct {tn}({});\n", ps.join(", "))?;
                }
                Kind::Enum(cases) => {
                    let under = if cases.len() > 255 { "ushort" } else { "byte" };
                    let cs: Vec<String> = cases.iter().map(|c| pascal(c)).collect();
                    writeln!(s, "        internal enum {tn} : {under} {{ {} }}\n", cs.join(", "))?;
                }
                Kind::Variant(cases) => {
                    let under = if cases.len() > 255 { "ushort" } else { "byte" };
                    writeln!(s, "        internal struct {tn}\n        {{")?;
                    let cs: Vec<String> = cases.iter().map(|(c, _)| pascal(c)).collect();
                    writeln!(s, "            internal enum Tag : {under} {{ {} }}\n            public Tag Case;", cs.join(", "))?;
                    for (c, pt) in cases {
                        if let Some(pt) = pt {
                            writeln!(s, "            public {} {};", m.cs(pt), pascal(c))?;
                        }
                    }
                    writeln!(s, "        }}\n")?;
                }
            }
        }
        s.truncate(s.trim_end().len());
        s.push_str("\n    }\n\n");
    }
    s.truncate(s.trim_end().len());
    s.push_str("\n}\n\n");

    // interface
    s.push_str("/// The host functions, typed. `mod` = the calling mod.\ninternal interface ICuoHostApi\n{\n");
    for f in &fns {
        writeln!(s, "    {};", sig(f))?;
    }
    s.push_str("}\n\n");

    // tracing decorator
    s.push_str(
        "/// Forwards every call to `inner` and reports it as p1 JSON (name, args array, result or\n\
         /// null) — tests and diagnostics.\n\
         internal sealed class CuoHostApiTrace(ICuoHostApi inner, Action<string, string, string?> sink) : ICuoHostApi\n{\n\
         \x20   private readonly System.Buffers.ArrayBufferWriter<byte> _buf = new(256);\n\n\
         \x20   private string Json(Action<Utf8JsonWriter> write)\n    {\n\
         \x20       _buf.ResetWrittenCount();\n\
         \x20       using (var w = new Utf8JsonWriter(_buf))\n            write(w);\n\
         \x20       return System.Text.Encoding.UTF8.GetString(_buf.WrittenSpan);\n    }\n\n",
    );
    for f in &fns {
        // p0..pn: a WIT param named `w` would shadow the JSON writer.
        let names: Vec<String> = (0..f.params.len()).map(|i| format!("p{i}")).collect();
        let ret = f.result.as_ref().map_or("void".to_string(), |t| m.cs(t));
        let mut ps = vec!["ModHostContext mod".to_string()];
        ps.extend(f.params.iter().zip(&names).map(|((_, t), n)| format!("{} {n}", m.cs(t))));
        writeln!(s, "    public {ret} {}({})\n    {{", pascal(&f.name), ps.join(", "))?;
        let mut fwd = vec!["mod".to_string()];
        fwd.extend(names.iter().cloned());
        let args_json: Vec<String> = f.params.iter().zip(&names).map(|((_, t), n)| format!("{};", qualify(&m.json_write(t, n)))).collect();
        let lambda = format!("w => {{ w.WriteStartArray(); {} w.WriteEndArray(); }}", args_json.join(" "));
        match &f.result {
            Some(t) => {
                writeln!(s, "        var result = inner.{}({});", pascal(&f.name), fwd.join(", "))?;
                let rw = qualify(&m.json_write(t, "result"));
                writeln!(s, "        sink(\"{}\", Json({lambda}), Json(w => {rw}));\n        return result;", f.full)?;
            }
            None => {
                writeln!(s, "        inner.{}({});", pascal(&f.name), fwd.join(", "))?;
                writeln!(s, "        sink(\"{}\", Json({lambda}), null);", f.full)?;
            }
        }
        s.push_str("    }\n\n");
    }
    s.truncate(s.trim_end().len());
    s.push_str("\n}\n\n");

    // dispatch
    s.push_str("internal static partial class CuoHostCalls\n{\n");
    s.push_str("    /// Every host function, \"<package>/<interface>#<function>\"; the index is its id here.\n");
    s.push_str("    public static readonly string[] Names =\n    [\n");
    for f in &fns {
        writeln!(s, "        \"{}\",", f.full)?;
    }
    s.push_str("    ];\n\n");

    s.push_str(
        "    /// Runs function `fn` with its Encoding.Typed args from `r`; its result (if any) is\n\
         \x20   /// written to `w`. Throws on malformed args (the caller traps the mod).\n\
         \x20   public static void InvokeBin(int fn, ICuoHostApi api, ModHostContext mod, ref CuoBinReader r, CuoBinWriter w)\n    {\n\
         \x20       switch (fn)\n        {\n",
    );
    for (i, f) in fns.iter().enumerate() {
        writeln!(s, "            case {i}:\n            {{")?;
        for (k, (_, t)) in f.params.iter().enumerate() {
            writeln!(s, "                var a{k} = {};", m.bin_read(t))?;
        }
        writeln!(s, "                r.End();")?;
        match &f.result {
            Some(t) => {
                writeln!(s, "                var result = api.{}({});", pascal(&f.name), call_args(f))?;
                writeln!(s, "                {};", m.bin_write(t, "result"))?;
            }
            None => writeln!(s, "                api.{}({});", pascal(&f.name), call_args(f))?,
        }
        writeln!(s, "                return;\n            }}")?;
    }
    s.push_str("            default:\n                throw new ModCallException($\"host call: unknown function id {fn}\");\n        }\n    }\n\n");

    s.push_str("    /// The p1 JSON wire (fallback): one ModHostFunctions entry per function.\n");
    s.push_str("    public static void Register(ModHostFunctions fns, ICuoHostApi api)\n    {\n");
    for f in &fns {
        writeln!(s, "        fns.Add(\"{}\", (mod, a, w) =>\n        {{", f.full)?;
        for (k, (_, t)) in f.params.iter().enumerate() {
            writeln!(s, "            var a{k} = {};", m.json_read(t, &format!("CuoModArgs.Arg(a, {k})")))?;
        }
        match &f.result {
            Some(t) => {
                writeln!(s, "            var result = api.{}({});", pascal(&f.name), call_args(f))?;
                writeln!(s, "            {};", m.json_write(t, "result"))?;
            }
            None => writeln!(s, "            api.{}({});", pascal(&f.name), call_args(f))?,
        }
        s.push_str("        });\n");
    }
    s.push_str("    }\n\n");

    // test transcoders
    s.push_str("    /// Encoding.Typed args -> the p1 JSON args array (tests: the decoder side of the golden bytes).\n");
    s.push_str("    public static void ArgsBinToJson(int fn, ref CuoBinReader r, Utf8JsonWriter w)\n    {\n        w.WriteStartArray();\n        switch (fn)\n        {\n");
    for (i, f) in fns.iter().enumerate() {
        writeln!(s, "            case {i}:")?;
        for (_, t) in &f.params {
            writeln!(s, "                {};", m.json_write(t, &m.bin_read(t)))?;
        }
        writeln!(s, "                break;")?;
    }
    s.push_str("            default:\n                throw new ModCallException($\"host call: unknown function id {fn}\");\n        }\n        r.End();\n        w.WriteEndArray();\n    }\n\n");

    s.push_str("    /// p1 JSON args array -> Encoding.Typed args.\n");
    s.push_str("    public static void ArgsJsonToBin(int fn, JsonElement a, CuoBinWriter w)\n    {\n        switch (fn)\n        {\n");
    for (i, f) in fns.iter().enumerate() {
        writeln!(s, "            case {i}:")?;
        for (k, (_, t)) in f.params.iter().enumerate() {
            writeln!(s, "                {};", m.bin_write(t, &m.json_read(t, &format!("CuoModArgs.Arg(a, {k})"))))?;
        }
        writeln!(s, "                break;")?;
    }
    s.push_str("            default:\n                throw new ModCallException($\"host call: unknown function id {fn}\");\n        }\n    }\n\n");

    s.push_str("    /// p1 JSON result -> Encoding.Typed result (false: the function has none).\n");
    s.push_str("    public static bool ResultJsonToBin(int fn, JsonElement e, CuoBinWriter w)\n    {\n        switch (fn)\n        {\n");
    for (i, f) in fns.iter().enumerate() {
        match &f.result {
            Some(t) => writeln!(s, "            case {i}: {}; return true;", m.bin_write(t, &m.json_read(t, "e")))?,
            None => writeln!(s, "            case {i}: return false;")?,
        }
    }
    s.push_str("            default:\n                throw new ModCallException($\"host call: unknown function id {fn}\");\n        }\n    }\n\n");

    for t in &order {
        m.helpers_shared(t, &mut s)?;
    }
    s.truncate(s.trim_end().len());
    s.push_str("\n}\n");

    // ── native Cm ──
    let mut c = String::from(HEADER);
    c.push_str(
        "// Typed host calls on the in-process component host: WIT values (Cm.ComponentValue) ->\n\
         // the typed ICuoHostApi call -> the WIT result, no JSON (CuoComponentImports.cs).\n\n\
         #nullable enable\nextern alias WasmtimeCm;\n\nusing System;\nusing System.Text;\nusing TinyEcs.Bevy.Modding;\n\
         using Cm = WasmtimeCm::Wasmtime;\n\nnamespace ClassicUO.Ecs.Modding.Api;\n\n\
         internal static unsafe partial class CuoHostCalls\n{\n",
    );
    c.push_str(
        "    /// Runs function `fn` with the guest's WIT args; its result (if any) goes to results[0].\n\
         \x20   public static void InvokeCm(int fn, ICuoHostApi api, ModHostContext mod, Cm.ComponentCallResults args, Cm.ComponentValue* results)\n    {\n\
         \x20       switch (fn)\n        {\n",
    );
    for (i, f) in fns.iter().enumerate() {
        writeln!(c, "            case {i}:\n            {{")?;
        for (k, (_, t)) in f.params.iter().enumerate() {
            writeln!(c, "                var a{k} = {};", m.lift(t, &format!("args[{k}]")))?;
        }
        match &f.result {
            Some(t) => {
                writeln!(c, "                var result = api.{}({});", pascal(&f.name), call_args(f))?;
                writeln!(c, "                results[0] = {};", m.lower(t, "result"))?;
            }
            None => writeln!(c, "                api.{}({});", pascal(&f.name), call_args(f))?,
        }
        writeln!(c, "                return;\n            }}")?;
    }
    c.push_str("            default:\n                throw new ModCallException($\"host call: unknown function id {fn}\");\n        }\n    }\n\n");
    for t in &order {
        m.helpers_cm(t, &mut c)?;
    }
    c.truncate(c.trim_end().len());
    c.push_str("\n}\n");
    Ok((s, c))
}

// A codec helper call from outside CuoHostCalls.
fn qualify(expr: &str) -> String {
    if expr.starts_with("WriteJson_") {
        format!("CuoHostCalls.{expr}")
    } else {
        expr.to_string()
    }
}
