//! wit-p1-gen — reads wit/cuo-mod.wit and writes
//!   rust/src/p1/cuo.rs     the cuo:mod host / packets / assets / actions interfaces for
//!                          the wasm32-wasip1 target: same names and signatures as
//!                          wit-bindgen's, bodies JSON-encode the args (docs/p1-wire.md)
//!                          and go through `env.mod_call`.
//!   rust/src/sigcheck.rs   compiled under BOTH features: every function as a typed fn
//!                          pointer, every record / enum / variant destructured, so a
//!                          drift between this output and wit-bindgen's fails to build.
//!
//! Usage (from the SDK root): cargo run --manifest-path tools/wit-p1-gen/Cargo.toml -- wit rust/src
//! An optional third argument also writes the ClassicUO host's C# signature table
//! there (csharp.rs) — the p2 component bridge.

mod csharp;

use anyhow::{bail, Context, Result};
use std::fmt::Write as _;
use wit_parser::{Docs, InterfaceId, Resolve, Type, TypeDefKind, TypeId, TypeOwner};

const INTERFACES: &[&str] = &["host", "packets", "assets", "actions"];

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 3 && args.len() != 4 {
        bail!("usage: wit-p1-gen <wit-dir> <rust-src-dir> [<csharp-signature-file>]");
    }
    let mut resolve = Resolve::default();
    let (pkg, _) = resolve.push_dir(&args[1]).context("parsing WIT")?;
    let package = &resolve.packages[pkg];
    let pkg_name = format!("{}:{}", package.name.namespace, package.name.name);

    let mut cuo = String::new();
    let mut check = String::new();
    cuo.push_str(HEADER_CUO);
    check.push_str(HEADER_CHECK);

    for name in INTERFACES {
        let iid = *package
            .interfaces
            .get(*name)
            .with_context(|| format!("interface `{name}` not in {pkg_name}"))?;
        let g = Gen { resolve: &resolve, iid, module: snake(name) };
        g.interface(&pkg_name, name, &mut cuo, &mut check)?;
    }

    let out = std::path::Path::new(&args[2]);
    std::fs::write(out.join("p1").join("cuo.rs"), cuo)?;
    std::fs::write(out.join("sigcheck.rs"), check)?;
    if let Some(cs) = args.get(3) {
        std::fs::write(cs, csharp::emit(&resolve, pkg, INTERFACES, "mod", &["on-packet"])?)?;
    }
    Ok(())
}


const HEADER_CUO: &str = "\
// @generated by tools/wit-p1-gen from wit/cuo-mod.wit — do not edit; run `make gen-p1`.
//! The cuo:modding host functions for the wasm32-wasip1 target. Names, types and
//! signatures match what wit-bindgen generates for the wasm32-wasip2 target, so mod
//! code is identical on both; each call is JSON over `env.mod_call` (docs/p1-wire.md).
#![allow(clippy::all, dead_code, unused_imports, non_camel_case_types)]
";

const HEADER_CHECK: &str = "\
// @generated by tools/wit-p1-gen from wit/cuo-mod.wit — do not edit; run `make gen-p1`.
//! Compiled under both `p1` and `p2`: fails to build when the generated p1 bindings and
//! wit-bindgen's disagree on a name, a field or a signature.
#![allow(dead_code, unused_variables, clippy::all)]
use crate::{actions, assets, host, packets};
";

struct Gen<'a> {
    resolve: &'a Resolve,
    iid: InterfaceId,
    module: String,
}

impl Gen<'_> {
    fn interface(&self, pkg: &str, name: &str, cuo: &mut String, check: &mut String) -> Result<()> {
        let iface = &self.resolve.interfaces[self.iid];
        let m = &self.module;
        docs(cuo, &iface.docs, "");
        writeln!(cuo, "pub mod {m} {{")?;
        writeln!(cuo, "    use crate::p1::call::{{FromWit, ToWit, Value}};")?;

        for (_, &tid) in &iface.types {
            self.typedef(tid, cuo, check)?;
        }

        writeln!(check, "fn fns_{m}() {{")?;
        for (fname, f) in &iface.functions {
            docs(cuo, &f.docs, "    ");
            let mut params = Vec::new();
            let mut ptys = Vec::new();
            for p in &f.params {
                params.push(format!("{}: {}", ident(&p.name), self.param_ty(&p.ty, "")?));
                ptys.push(self.param_ty(&p.ty, &format!("{m}::"))?);
            }
            let (ret, ret_check) = match &f.result {
                Some(t) => (
                    format!(" -> {}", self.owned_ty(t, "")?),
                    format!(" -> {}", self.owned_ty(t, &format!("{m}::"))?),
                ),
                None => (String::new(), String::new()),
            };
            writeln!(cuo, "    pub fn {}({}){} {{", snake(fname), params.join(", "), ret)?;
            let args: Vec<String> =
                f.params.iter().map(|p| format!("ToWit::to_wit(&{})", ident(&p.name))).collect();
            writeln!(
                cuo,
                "        crate::p1::call::call(\"{pkg}/{name}#{fname}\", ::std::vec![{}])",
                args.join(", ")
            )?;
            writeln!(cuo, "    }}")?;
            writeln!(
                check,
                "    let _: fn({}){} = {m}::{};",
                ptys.join(", "),
                ret_check,
                snake(fname)
            )?;
        }
        writeln!(check, "}}")?;
        writeln!(cuo, "}}")?;
        Ok(())
    }

    fn typedef(&self, tid: TypeId, cuo: &mut String, check: &mut String) -> Result<()> {
        let td = &self.resolve.types[tid];
        let name = pascal(td.name.as_deref().context("anonymous interface type")?);
        let m = &self.module;
        let fname = format!("{m}_{}", snake(td.name.as_deref().unwrap()));
        docs(cuo, &td.docs, "    ");
        match &td.kind {
            TypeDefKind::Type(t) => {
                writeln!(cuo, "    pub type {name} = {};", self.owned_ty(t, "")?)?;
            }
            TypeDefKind::Enum(e) => {
                writeln!(cuo, "    #[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]")?;
                writeln!(cuo, "    pub enum {name} {{")?;
                for c in &e.cases {
                    docs(cuo, &c.docs, "        ");
                    writeln!(cuo, "        {},", pascal(&c.name))?;
                }
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl ToWit for {name} {{")?;
                writeln!(cuo, "        fn to_wit(&self) -> Value {{")?;
                writeln!(cuo, "            Value::String(match self {{")?;
                for c in &e.cases {
                    writeln!(cuo, "                Self::{} => \"{}\",", pascal(&c.name), c.name)?;
                }
                writeln!(cuo, "            }}.into())")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl FromWit for {name} {{")?;
                writeln!(cuo, "        fn from_wit(v: &Value) -> Option<Self> {{")?;
                writeln!(cuo, "            Some(match v.as_str()? {{")?;
                for c in &e.cases {
                    writeln!(cuo, "                \"{}\" => Self::{},", c.name, pascal(&c.name))?;
                }
                writeln!(cuo, "                _ => return None,")?;
                writeln!(cuo, "            }})")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;

                writeln!(check, "fn enum_{fname}(v: {m}::{name}) {{")?;
                writeln!(check, "    match v {{")?;
                for c in &e.cases {
                    writeln!(check, "        {m}::{name}::{} => {{}}", pascal(&c.name))?;
                }
                writeln!(check, "    }}")?;
                writeln!(check, "}}")?;
            }
            TypeDefKind::Record(r) => {
                let copy = r.fields.iter().all(|f| self.is_copy(&f.ty));
                writeln!(cuo, "    #[derive(Clone, {}Debug)]", if copy { "Copy, " } else { "" })?;
                writeln!(cuo, "    pub struct {name} {{")?;
                for f in &r.fields {
                    docs(cuo, &f.docs, "        ");
                    writeln!(cuo, "        pub {}: {},", ident(&f.name), self.owned_ty(&f.ty, "")?)?;
                }
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl ToWit for {name} {{")?;
                writeln!(cuo, "        fn to_wit(&self) -> Value {{")?;
                writeln!(cuo, "            let mut o = crate::p1::call::Map::new();")?;
                for f in &r.fields {
                    writeln!(
                        cuo,
                        "            o.insert(\"{}\".into(), self.{}.to_wit());",
                        f.name,
                        ident(&f.name)
                    )?;
                }
                writeln!(cuo, "            Value::Object(o)")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl FromWit for {name} {{")?;
                writeln!(cuo, "        fn from_wit(v: &Value) -> Option<Self> {{")?;
                writeln!(cuo, "            Some(Self {{")?;
                for f in &r.fields {
                    writeln!(
                        cuo,
                        "                {}: FromWit::from_wit(crate::p1::call::field(v, \"{}\"))?,",
                        ident(&f.name),
                        f.name
                    )?;
                }
                writeln!(cuo, "            }})")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;

                let fields: Vec<String> = r.fields.iter().map(|f| ident(&f.name)).collect();
                writeln!(check, "fn rec_{fname}(v: {m}::{name}) {{")?;
                writeln!(check, "    let {m}::{name} {{ {} }} = v;", fields.join(", "))?;
                for f in &r.fields {
                    writeln!(
                        check,
                        "    let _: {} = {};",
                        self.owned_ty(&f.ty, &format!("{m}::"))?,
                        ident(&f.name)
                    )?;
                }
                writeln!(check, "}}")?;
            }
            TypeDefKind::Variant(v) => {
                let copy = v.cases.iter().all(|c| c.ty.as_ref().map_or(true, |t| self.is_copy(t)));
                writeln!(cuo, "    #[derive(Clone, {}Debug)]", if copy { "Copy, " } else { "" })?;
                writeln!(cuo, "    pub enum {name} {{")?;
                for c in &v.cases {
                    docs(cuo, &c.docs, "        ");
                    match &c.ty {
                        Some(t) => writeln!(cuo, "        {}({}),", pascal(&c.name), self.owned_ty(t, "")?)?,
                        None => writeln!(cuo, "        {},", pascal(&c.name))?,
                    }
                }
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl ToWit for {name} {{")?;
                writeln!(cuo, "        fn to_wit(&self) -> Value {{")?;
                writeln!(cuo, "            let (k, v) = match self {{")?;
                for c in &v.cases {
                    match &c.ty {
                        Some(_) => writeln!(
                            cuo,
                            "                Self::{}(p) => (\"{}\", p.to_wit()),",
                            pascal(&c.name),
                            c.name
                        )?,
                        None => writeln!(
                            cuo,
                            "                Self::{} => (\"{}\", Value::Null),",
                            pascal(&c.name),
                            c.name
                        )?,
                    }
                }
                writeln!(cuo, "            }};")?;
                writeln!(cuo, "            crate::p1::call::variant(k, v)")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;
                writeln!(cuo, "    impl FromWit for {name} {{")?;
                writeln!(cuo, "        fn from_wit(v: &Value) -> Option<Self> {{")?;
                writeln!(cuo, "            let (k, p) = crate::p1::call::case(v)?;")?;
                writeln!(cuo, "            Some(match k {{")?;
                for c in &v.cases {
                    match &c.ty {
                        Some(_) => writeln!(
                            cuo,
                            "                \"{}\" => Self::{}(FromWit::from_wit(p)?),",
                            c.name,
                            pascal(&c.name)
                        )?,
                        None => writeln!(cuo, "                \"{}\" => Self::{},", c.name, pascal(&c.name))?,
                    }
                }
                writeln!(cuo, "                _ => return None,")?;
                writeln!(cuo, "            }})")?;
                writeln!(cuo, "        }}")?;
                writeln!(cuo, "    }}")?;

                writeln!(check, "fn variant_{fname}(v: {m}::{name}) {{")?;
                writeln!(check, "    match v {{")?;
                for c in &v.cases {
                    match &c.ty {
                        Some(t) => writeln!(
                            check,
                            "        {m}::{name}::{}(p) => {{ let _: {} = p; }}",
                            pascal(&c.name),
                            self.owned_ty(t, &format!("{m}::"))?
                        )?,
                        None => writeln!(check, "        {m}::{name}::{} => {{}}", pascal(&c.name))?,
                    }
                }
                writeln!(check, "    }}")?;
                writeln!(check, "}}")?;
            }
            other => bail!("unsupported type kind for `{name}`: {other:?}"),
        }
        Ok(())
    }

    /// An owned Rust type (fields, results, list elements). `prefix` qualifies this
    /// interface's own named types (`assets::` in sigcheck.rs, empty in cuo.rs).
    fn owned_ty(&self, t: &Type, prefix: &str) -> Result<String> {
        Ok(match t {
            Type::Bool => "bool".into(),
            Type::U8 => "u8".into(),
            Type::U16 => "u16".into(),
            Type::U32 => "u32".into(),
            Type::U64 => "u64".into(),
            Type::S8 => "i8".into(),
            Type::S16 => "i16".into(),
            Type::S32 => "i32".into(),
            Type::S64 => "i64".into(),
            Type::F32 => "f32".into(),
            Type::F64 => "f64".into(),
            Type::Char => "char".into(),
            Type::String => "String".into(),
            Type::ErrorContext => bail!("error-context is not supported"),
            Type::Id(id) => {
                let td = &self.resolve.types[*id];
                match (&td.name, td.owner) {
                    (Some(n), TypeOwner::Interface(owner)) if owner == self.iid => {
                        format!("{prefix}{}", pascal(n))
                    }
                    // A type `use`d from another interface (tinyecs ecs.entity): only
                    // aliases cross, spelled as what they alias.
                    (Some(n), _) => match &td.kind {
                        TypeDefKind::Type(inner) => self.owned_ty(inner, prefix)?,
                        _ => bail!("foreign non-alias type `{n}`"),
                    },
                    (None, _) => match &td.kind {
                        TypeDefKind::Option(t) => format!("Option<{}>", self.owned_ty(t, prefix)?),
                        TypeDefKind::List(t) => format!("Vec<{}>", self.owned_ty(t, prefix)?),
                        TypeDefKind::Tuple(tt) => {
                            let parts: Result<Vec<_>> =
                                tt.types.iter().map(|t| self.owned_ty(t, prefix)).collect();
                            format!("({},)", parts?.join(", "))
                        }
                        other => bail!("unsupported anonymous type {other:?}"),
                    },
                }
            }
        })
    }

    /// A parameter type, as wit-bindgen's import side spells it: strings and lists are
    /// borrowed, everything else (all Copy in this WIT) is by value.
    fn param_ty(&self, t: &Type, prefix: &str) -> Result<String> {
        if let Type::String = t {
            return Ok("&str".into());
        }
        if let Type::Id(id) = t {
            let td = &self.resolve.types[*id];
            if td.name.is_none() {
                if let TypeDefKind::List(e) = &td.kind {
                    return Ok(format!("&[{}]", self.owned_ty(e, prefix)?));
                }
            }
        }
        if !self.is_copy(t) {
            bail!("non-Copy aggregate parameter: wit-bindgen borrows these; teach the generator");
        }
        self.owned_ty(t, prefix)
    }

    fn is_copy(&self, t: &Type) -> bool {
        match t {
            Type::String | Type::ErrorContext => false,
            Type::Id(id) => match &self.resolve.types[*id].kind {
                TypeDefKind::Type(t) | TypeDefKind::Option(t) => self.is_copy(t),
                TypeDefKind::List(_) => false,
                TypeDefKind::Tuple(tt) => tt.types.iter().all(|t| self.is_copy(t)),
                TypeDefKind::Record(r) => r.fields.iter().all(|f| self.is_copy(&f.ty)),
                TypeDefKind::Variant(v) => {
                    v.cases.iter().all(|c| c.ty.as_ref().map_or(true, |t| self.is_copy(t)))
                }
                TypeDefKind::Enum(_) => true,
                _ => false,
            },
            _ => true,
        }
    }
}

fn docs(out: &mut String, d: &Docs, indent: &str) {
    if let Some(c) = &d.contents {
        for line in c.lines() {
            let _ = writeln!(out, "{indent}///{}{line}", if line.is_empty() { "" } else { " " });
        }
    }
}

fn pascal(kebab: &str) -> String {
    kebab
        .split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake(kebab: &str) -> String {
    kebab.replace('-', "_")
}

/// wit-bindgen's `to_rust_ident`: snake_case, keywords get a trailing `_`.
fn ident(kebab: &str) -> String {
    let s = snake(kebab);
    const KW: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
        "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
        "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
        "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final",
        "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
    ];
    if KW.contains(&s.as_str()) {
        s + "_"
    } else {
        s
    }
}
