// <auto-generated> by tools/wit-p1-gen (wit-cs-gen) from wit/cuo-mod.wit — do not edit; run `make gen-cs`.
// The cuo:modding host functions for C# mods (wasm32-wasip1): each call is JSON over
// `env.mod_call` (docs/p1-wire.md).
#nullable enable
#pragma warning disable CS1591
using System.Text.Json;

namespace CuoModSdk;

public static partial class Host
{

    /// <summary>
    /// Where `storage-get` / `storage-set` keep the mod's blob.
    /// </summary>
    public enum Scope
    {
        /// <summary>
        /// One blob for the mod, shared by every character.
        /// </summary>
        Global,
        /// <summary>
        /// One blob per character (empty until a character is logged in).
        /// </summary>
        Character,
    }

    internal static void Write(Utf8JsonWriter w, Scope v) => w.WriteStringValue(v switch
    {
        Scope.Global => "global",
        Scope.Character => "character",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Scope ReadScope(JsonElement e) => e.GetString() switch
    {
        "global" => Scope.Global,
        "character" => Scope.Character,
        var s => throw Wit.Bad("Scope", s),
    };

    /// <summary>
    /// Writes a line to the client log, prefixed with the mod name.
    /// </summary>
    public static void Log(string message)
    {
        var w = Wit.Begin();
        w.WriteStringValue(message);
        Wit.Call("cuo:modding/host#log");
    }

    /// <summary>
    /// Pixel width of `text` in a UO font.
    /// </summary>
    public static uint MeasureText(ushort font, string text)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(font);
        w.WriteStringValue(text);
        var r = Wit.Call("cuo:modding/host#measure-text");
        return r.GetUInt32();
    }

    /// <summary>
    /// The entity of a UO serial (an item or mobile the client knows); none when
    /// unknown.
    /// </summary>
    public static ulong? ResolveSerial(uint serial)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(serial);
        var r = Wit.Call("cuo:modding/host#resolve-serial");
        return (Wit.IsNull(r) ? default(ulong?) : (ulong?)Wit.ReadUInt64(r));
    }

    /// <summary>
    /// The mod's stored blob ("" when nothing was stored).
    /// </summary>
    public static string StorageGet(Scope scope)
    {
        var w = Wit.Begin();
        Write(w, scope);
        var r = Wit.Call("cuo:modding/host#storage-get");
        return (r.GetString() ?? "");
    }

    /// <summary>
    /// Replaces the mod's stored blob. Written to disk immediately.
    /// </summary>
    public static void StorageSet(Scope scope, string value)
    {
        var w = Wit.Begin();
        Write(w, scope);
        w.WriteStringValue(value);
        Wit.Call("cuo:modding/host#storage-set");
    }
}

/// <summary>
/// Raw UO packets, both ways. A packet is the full wire bytes, id first. Prefer
/// world data and `actions` when they cover what you need: they keep the client's
/// own state in step.
/// </summary>
public static partial class Packets
{

    public enum Direction
    {
        /// <summary>
        /// Server to client.
        /// </summary>
        Incoming,
        /// <summary>
        /// Client to server.
        /// </summary>
        Outgoing,
    }

    internal static void Write(Utf8JsonWriter w, Direction v) => w.WriteStringValue(v switch
    {
        Direction.Incoming => "incoming",
        Direction.Outgoing => "outgoing",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Direction ReadDirection(JsonElement e) => e.GetString() switch
    {
        "incoming" => Direction.Incoming,
        "outgoing" => Direction.Outgoing,
        var s => throw Wit.Bad("Direction", s),
    };

    /// <summary>
    /// What `on-packet` decides.
    /// </summary>
    public abstract record Verdict
    {
        private Verdict() { }
        /// <summary>
        /// Let it through unchanged.
        /// </summary>
        public sealed record Pass : Verdict;
        /// <summary>
        /// Drop it: the client never handles / sends it.
        /// </summary>
        public sealed record Block : Verdict;
        /// <summary>
        /// Let these bytes through instead.
        /// </summary>
        public sealed record Replace(byte[] Value) : Verdict;
    }

    internal static void Write(Utf8JsonWriter w, Verdict v)
    {
        w.WriteStartObject();
        switch (v)
        {
            case Verdict.Pass:
                w.WritePropertyName("pass");
                w.WriteNullValue();
                break;
            case Verdict.Block:
                w.WritePropertyName("block");
                w.WriteNullValue();
                break;
            case Verdict.Replace c:
                w.WritePropertyName("replace");
                w.WriteBase64StringValue(c.Value);
                break;
            default:
                throw new System.ArgumentOutOfRangeException(nameof(v));
        }
        w.WriteEndObject();
    }

    internal static Verdict ReadVerdict(JsonElement e)
    {
        var (k, p) = Wit.Case(e);
        return k switch
        {
            "pass" => new Verdict.Pass(),
            "block" => new Verdict.Block(),
            "replace" => new Verdict.Replace(Wit.ReadBytes(p)),
            _ => throw Wit.Bad("Verdict", k),
        };
    }

    /// <summary>
    /// Asks for `on-packet` calls for these packet ids in one direction. Call it in
    /// `setup`; a mod that never calls it gets no packets. Calling again adds ids.
    /// </summary>
    public static void Intercept(Direction dir, System.ReadOnlySpan<byte> ids)
    {
        var w = Wit.Begin();
        Write(w, dir);
        w.WriteBase64StringValue(ids);
        Wit.Call("cuo:modding/packets#intercept");
    }

    /// <summary>
    /// Sends a packet to the server, as if the client had sent it.
    /// </summary>
    public static void SendToServer(System.ReadOnlySpan<byte> packet)
    {
        var w = Wit.Begin();
        w.WriteBase64StringValue(packet);
        Wit.Call("cuo:modding/packets#send-to-server");
    }

    /// <summary>
    /// Feeds a packet to the client, as if the server had sent it.
    /// </summary>
    public static void SendToClient(System.ReadOnlySpan<byte> packet)
    {
        var w = Wit.Begin();
        w.WriteBase64StringValue(packet);
        Wit.Call("cuo:modding/packets#send-to-client");
    }
}

/// <summary>
/// The client's UO data files, read-only. Images come back decoded from the files
/// (not from the GPU), so they work before anything was drawn.
///
/// Conventions: pixels are RGBA8, straight alpha, row-major, `width * height * 4`
/// bytes. Colours are u32 0xAARRGGBB. A `hue` argument is the wire value: 0 = none,
/// 0x8000 bit = partial hue (only grey pixels recoloured).
/// </summary>
public static partial class Assets
{

    public enum ImageKind
    {
        /// <summary>
        /// Land tile art, id 0..0x3FFF (44x44 diamond).
        /// </summary>
        Land,
        /// <summary>
        /// Item / static art, by graphic.
        /// </summary>
        Art,
        /// <summary>
        /// Gump image.
        /// </summary>
        Gump,
        /// <summary>
        /// Land texture (64x64 or 128x128), by tiledata texmap id.
        /// </summary>
        Texmap,
        /// <summary>
        /// Light shape, 0..99.
        /// </summary>
        Light,
    }

    internal static void Write(Utf8JsonWriter w, ImageKind v) => w.WriteStringValue(v switch
    {
        ImageKind.Land => "land",
        ImageKind.Art => "art",
        ImageKind.Gump => "gump",
        ImageKind.Texmap => "texmap",
        ImageKind.Light => "light",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static ImageKind ReadImageKind(JsonElement e) => e.GetString() switch
    {
        "land" => ImageKind.Land,
        "art" => ImageKind.Art,
        "gump" => ImageKind.Gump,
        "texmap" => ImageKind.Texmap,
        "light" => ImageKind.Light,
        var s => throw Wit.Bad("ImageKind", s),
    };

    public struct Size
    {
        public uint Width;
        public uint Height;
    }

    internal static void Write(Utf8JsonWriter w, Size v)
    {
        w.WriteStartObject();
        w.WritePropertyName("width");
        w.WriteNumberValue(v.Width);
        w.WritePropertyName("height");
        w.WriteNumberValue(v.Height);
        w.WriteEndObject();
    }

    internal static Size ReadSize(JsonElement e) => new()
    {
        Width = Wit.Field(e, "width").GetUInt32(),
        Height = Wit.Field(e, "height").GetUInt32(),
    };

    public struct Image
    {
        public uint Width;
        public uint Height;
        public byte[] Rgba;
    }

    internal static void Write(Utf8JsonWriter w, Image v)
    {
        w.WriteStartObject();
        w.WritePropertyName("width");
        w.WriteNumberValue(v.Width);
        w.WritePropertyName("height");
        w.WriteNumberValue(v.Height);
        w.WritePropertyName("rgba");
        w.WriteBase64StringValue(v.Rgba);
        w.WriteEndObject();
    }

    internal static Image ReadImage(JsonElement e) => new()
    {
        Width = Wit.Field(e, "width").GetUInt32(),
        Height = Wit.Field(e, "height").GetUInt32(),
        Rgba = Wit.ReadBytes(Wit.Field(e, "rgba")),
    };

    /// <summary>
    /// Which mobile animation to read. `direction` is 0..7 (the host mirrors the
    /// ones UO stores flipped); `action` is the UO action group.
    /// </summary>
    public struct AnimKey
    {
        public ushort Body;
        public byte Action;
        public byte Direction;
    }

    internal static void Write(Utf8JsonWriter w, AnimKey v)
    {
        w.WriteStartObject();
        w.WritePropertyName("body");
        w.WriteNumberValue(v.Body);
        w.WritePropertyName("action");
        w.WriteNumberValue(v.Action);
        w.WritePropertyName("direction");
        w.WriteNumberValue(v.Direction);
        w.WriteEndObject();
    }

    internal static AnimKey ReadAnimKey(JsonElement e) => new()
    {
        Body = Wit.Field(e, "body").GetUInt16(),
        Action = Wit.Field(e, "action").GetByte(),
        Direction = Wit.Field(e, "direction").GetByte(),
    };

    public struct FrameInfo
    {
        public uint Width;
        public uint Height;
        /// <summary>
        /// Draw offset: the frame's anchor point relative to its top-left.
        /// </summary>
        public int CenterX;
        public int CenterY;
    }

    internal static void Write(Utf8JsonWriter w, FrameInfo v)
    {
        w.WriteStartObject();
        w.WritePropertyName("width");
        w.WriteNumberValue(v.Width);
        w.WritePropertyName("height");
        w.WriteNumberValue(v.Height);
        w.WritePropertyName("center-x");
        w.WriteNumberValue(v.CenterX);
        w.WritePropertyName("center-y");
        w.WriteNumberValue(v.CenterY);
        w.WriteEndObject();
    }

    internal static FrameInfo ReadFrameInfo(JsonElement e) => new()
    {
        Width = Wit.Field(e, "width").GetUInt32(),
        Height = Wit.Field(e, "height").GetUInt32(),
        CenterX = Wit.Field(e, "center-x").GetInt32(),
        CenterY = Wit.Field(e, "center-y").GetInt32(),
    };

    public struct StaticInfo
    {
        public string Name;
        public ulong Flags;
        public byte Weight;
        public byte Layer;
        public int Count;
        public ushort AnimId;
        public ushort Hue;
        public ushort LightIndex;
        public byte Height;
    }

    internal static void Write(Utf8JsonWriter w, StaticInfo v)
    {
        w.WriteStartObject();
        w.WritePropertyName("name");
        w.WriteStringValue(v.Name);
        w.WritePropertyName("flags");
        Wit.WriteInt64String(w, v.Flags);
        w.WritePropertyName("weight");
        w.WriteNumberValue(v.Weight);
        w.WritePropertyName("layer");
        w.WriteNumberValue(v.Layer);
        w.WritePropertyName("count");
        w.WriteNumberValue(v.Count);
        w.WritePropertyName("anim-id");
        w.WriteNumberValue(v.AnimId);
        w.WritePropertyName("hue");
        w.WriteNumberValue(v.Hue);
        w.WritePropertyName("light-index");
        w.WriteNumberValue(v.LightIndex);
        w.WritePropertyName("height");
        w.WriteNumberValue(v.Height);
        w.WriteEndObject();
    }

    internal static StaticInfo ReadStaticInfo(JsonElement e) => new()
    {
        Name = (Wit.Field(e, "name").GetString() ?? ""),
        Flags = Wit.ReadUInt64(Wit.Field(e, "flags")),
        Weight = Wit.Field(e, "weight").GetByte(),
        Layer = Wit.Field(e, "layer").GetByte(),
        Count = Wit.Field(e, "count").GetInt32(),
        AnimId = Wit.Field(e, "anim-id").GetUInt16(),
        Hue = Wit.Field(e, "hue").GetUInt16(),
        LightIndex = Wit.Field(e, "light-index").GetUInt16(),
        Height = Wit.Field(e, "height").GetByte(),
    };

    public struct LandInfo
    {
        public string Name;
        public ulong Flags;
        public ushort Texmap;
    }

    internal static void Write(Utf8JsonWriter w, LandInfo v)
    {
        w.WriteStartObject();
        w.WritePropertyName("name");
        w.WriteStringValue(v.Name);
        w.WritePropertyName("flags");
        Wit.WriteInt64String(w, v.Flags);
        w.WritePropertyName("texmap");
        w.WriteNumberValue(v.Texmap);
        w.WriteEndObject();
    }

    internal static LandInfo ReadLandInfo(JsonElement e) => new()
    {
        Name = (Wit.Field(e, "name").GetString() ?? ""),
        Flags = Wit.ReadUInt64(Wit.Field(e, "flags")),
        Texmap = Wit.Field(e, "texmap").GetUInt16(),
    };

    /// <summary>
    /// Map file data only (no items, no house customisation). `map` is the facet
    /// index.
    /// </summary>
    public struct LandCell
    {
        public ushort Graphic;
        public sbyte Z;
    }

    internal static void Write(Utf8JsonWriter w, LandCell v)
    {
        w.WriteStartObject();
        w.WritePropertyName("graphic");
        w.WriteNumberValue(v.Graphic);
        w.WritePropertyName("z");
        w.WriteNumberValue(v.Z);
        w.WriteEndObject();
    }

    internal static LandCell ReadLandCell(JsonElement e) => new()
    {
        Graphic = Wit.Field(e, "graphic").GetUInt16(),
        Z = Wit.Field(e, "z").GetSByte(),
    };

    public struct StaticCell
    {
        public ushort Graphic;
        public sbyte Z;
        public ushort Hue;
    }

    internal static void Write(Utf8JsonWriter w, StaticCell v)
    {
        w.WriteStartObject();
        w.WritePropertyName("graphic");
        w.WriteNumberValue(v.Graphic);
        w.WritePropertyName("z");
        w.WriteNumberValue(v.Z);
        w.WritePropertyName("hue");
        w.WriteNumberValue(v.Hue);
        w.WriteEndObject();
    }

    internal static StaticCell ReadStaticCell(JsonElement e) => new()
    {
        Graphic = Wit.Field(e, "graphic").GetUInt16(),
        Z = Wit.Field(e, "z").GetSByte(),
        Hue = Wit.Field(e, "hue").GetUInt16(),
    };

    /// <summary>
    /// The pieces of a multi (house, boat), offsets relative to its centre.
    /// </summary>
    public struct MultiPart
    {
        public ushort Graphic;
        public short X;
        public short Y;
        public short Z;
    }

    internal static void Write(Utf8JsonWriter w, MultiPart v)
    {
        w.WriteStartObject();
        w.WritePropertyName("graphic");
        w.WriteNumberValue(v.Graphic);
        w.WritePropertyName("x");
        w.WriteNumberValue(v.X);
        w.WritePropertyName("y");
        w.WriteNumberValue(v.Y);
        w.WritePropertyName("z");
        w.WriteNumberValue(v.Z);
        w.WriteEndObject();
    }

    internal static MultiPart ReadMultiPart(JsonElement e) => new()
    {
        Graphic = Wit.Field(e, "graphic").GetUInt16(),
        X = Wit.Field(e, "x").GetInt16(),
        Y = Wit.Field(e, "y").GetInt16(),
        Z = Wit.Field(e, "z").GetInt16(),
    };

    public struct Skill
    {
        public ushort Index;
        public string Name;
        public bool HasAction;
    }

    internal static void Write(Utf8JsonWriter w, Skill v)
    {
        w.WriteStartObject();
        w.WritePropertyName("index");
        w.WriteNumberValue(v.Index);
        w.WritePropertyName("name");
        w.WriteStringValue(v.Name);
        w.WritePropertyName("has-action");
        w.WriteBooleanValue(v.HasAction);
        w.WriteEndObject();
    }

    internal static Skill ReadSkill(JsonElement e) => new()
    {
        Index = Wit.Field(e, "index").GetUInt16(),
        Name = (Wit.Field(e, "name").GetString() ?? ""),
        HasAction = Wit.Field(e, "has-action").GetBoolean(),
    };

    /// <summary>
    /// Width and height; none when the id is missing.
    /// </summary>
    public static Size? ImageSize(ImageKind kind, uint id)
    {
        var w = Wit.Begin();
        Write(w, kind);
        w.WriteNumberValue(id);
        var r = Wit.Call("cuo:modding/assets#image-size");
        return (Wit.IsNull(r) ? default(Size?) : (Size?)ReadSize(r));
    }

    /// <summary>
    /// Decoded pixels with `hue` applied; none when the id is missing.
    /// </summary>
    public static Image? ImagePixels(ImageKind kind, uint id, ushort hue)
    {
        var w = Wit.Begin();
        Write(w, kind);
        w.WriteNumberValue(id);
        w.WriteNumberValue(hue);
        var r = Wit.Call("cuo:modding/assets#image-pixels");
        return (Wit.IsNull(r) ? default(Image?) : (Image?)ReadImage(r));
    }

    /// <summary>
    /// Number of frames; none when the body has no such animation.
    /// </summary>
    public static uint? AnimFrames(AnimKey key)
    {
        var w = Wit.Begin();
        Write(w, key);
        var r = Wit.Call("cuo:modding/assets#anim-frames");
        return (Wit.IsNull(r) ? default(uint?) : (uint?)r.GetUInt32());
    }

    /// <summary>
    /// Size and anchor of one frame.
    /// </summary>
    public static FrameInfo? AnimFrame(AnimKey key, uint frame)
    {
        var w = Wit.Begin();
        Write(w, key);
        w.WriteNumberValue(frame);
        var r = Wit.Call("cuo:modding/assets#anim-frame");
        return (Wit.IsNull(r) ? default(FrameInfo?) : (FrameInfo?)ReadFrameInfo(r));
    }

    /// <summary>
    /// Decoded pixels of one frame (already mirrored), with `hue` applied.
    /// </summary>
    public static Image? AnimPixels(AnimKey key, uint frame, ushort hue)
    {
        var w = Wit.Begin();
        Write(w, key);
        w.WriteNumberValue(frame);
        w.WriteNumberValue(hue);
        var r = Wit.Call("cuo:modding/assets#anim-pixels");
        return (Wit.IsNull(r) ? default(Image?) : (Image?)ReadImage(r));
    }

    /// <summary>
    /// The tiledata row of an item / static graphic.
    /// </summary>
    public static StaticInfo? StaticTile(ushort graphic)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(graphic);
        var r = Wit.Call("cuo:modding/assets#static-tile");
        return (Wit.IsNull(r) ? default(StaticInfo?) : (StaticInfo?)ReadStaticInfo(r));
    }

    /// <summary>
    /// The tiledata row of a land tile.
    /// </summary>
    public static LandInfo? LandTile(ushort id)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(id);
        var r = Wit.Call("cuo:modding/assets#land-tile");
        return (Wit.IsNull(r) ? default(LandInfo?) : (LandInfo?)ReadLandInfo(r));
    }

    /// <summary>
    /// The 32-colour ramp of a hue (1-based, as on the wire), dark to light.
    /// </summary>
    public static uint[]? HueRamp(ushort hue)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(hue);
        var r = Wit.Call("cuo:modding/assets#hue-ramp");
        return (Wit.IsNull(r) ? default(uint[]?) : (uint[]?)Wit.ReadList(r, static x0 => x0.GetUInt32()));
    }

    /// <summary>
    /// A cliloc by id with its `~n_ARG~` slots filled from `args`; empty when
    /// unknown.
    /// </summary>
    public static string Cliloc(uint id, System.ReadOnlySpan<string> args)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(id);
        w.WriteStartArray();
        foreach (var x0 in args)
        {
            w.WriteStringValue(x0);
        }
        w.WriteEndArray();
        var r = Wit.Call("cuo:modding/assets#cliloc");
        return (r.GetString() ?? "");
    }

    public static Size? MapSize(byte map)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(map);
        var r = Wit.Call("cuo:modding/assets#map-size");
        return (Wit.IsNull(r) ? default(Size?) : (Size?)ReadSize(r));
    }

    public static LandCell? MapLand(byte map, ushort x, ushort y)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(map);
        w.WriteNumberValue(x);
        w.WriteNumberValue(y);
        var r = Wit.Call("cuo:modding/assets#map-land");
        return (Wit.IsNull(r) ? default(LandCell?) : (LandCell?)ReadLandCell(r));
    }

    public static StaticCell[] MapStatics(byte map, ushort x, ushort y)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(map);
        w.WriteNumberValue(x);
        w.WriteNumberValue(y);
        var r = Wit.Call("cuo:modding/assets#map-statics");
        return Wit.ReadList(r, static x0 => ReadStaticCell(x0));
    }

    public static MultiPart[] Multi(ushort id)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(id);
        var r = Wit.Call("cuo:modding/assets#multi");
        return Wit.ReadList(r, static x0 => ReadMultiPart(x0));
    }

    public static Skill[] Skills()
    {
        var w = Wit.Begin();
        var r = Wit.Call("cuo:modding/assets#skills");
        return Wit.ReadList(r, static x0 => ReadSkill(x0));
    }
}

/// <summary>
/// What the player can do. Each call goes through the client's own code path (the
/// same one a click or hotkey uses), so the client's state — held item, last target,
/// last object, war mode, the target queue — stays in step with the server. Calls
/// are fire-and-forget; the outcome shows up as world data and events.
///
/// Only primitives are here. Combinations (move every item of a type, target self,
/// bandage self, ...) are SDK helpers built on these.
/// </summary>
public static partial class Actions
{

    public enum Direction
    {
        North,
        NorthEast,
        East,
        SouthEast,
        South,
        SouthWest,
        West,
        NorthWest,
    }

    internal static void Write(Utf8JsonWriter w, Direction v) => w.WriteStringValue(v switch
    {
        Direction.North => "north",
        Direction.NorthEast => "north-east",
        Direction.East => "east",
        Direction.SouthEast => "south-east",
        Direction.South => "south",
        Direction.SouthWest => "south-west",
        Direction.West => "west",
        Direction.NorthWest => "north-west",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Direction ReadDirection(JsonElement e) => e.GetString() switch
    {
        "north" => Direction.North,
        "north-east" => Direction.NorthEast,
        "east" => Direction.East,
        "south-east" => Direction.SouthEast,
        "south" => Direction.South,
        "south-west" => Direction.SouthWest,
        "west" => Direction.West,
        "north-west" => Direction.NorthWest,
        var s => throw Wit.Bad("Direction", s),
    };

    public enum SpeechKind
    {
        Regular,
        Emote,
        Whisper,
        Yell,
        Guild,
        Alliance,
    }

    internal static void Write(Utf8JsonWriter w, SpeechKind v) => w.WriteStringValue(v switch
    {
        SpeechKind.Regular => "regular",
        SpeechKind.Emote => "emote",
        SpeechKind.Whisper => "whisper",
        SpeechKind.Yell => "yell",
        SpeechKind.Guild => "guild",
        SpeechKind.Alliance => "alliance",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static SpeechKind ReadSpeechKind(JsonElement e) => e.GetString() switch
    {
        "regular" => SpeechKind.Regular,
        "emote" => SpeechKind.Emote,
        "whisper" => SpeechKind.Whisper,
        "yell" => SpeechKind.Yell,
        "guild" => SpeechKind.Guild,
        "alliance" => SpeechKind.Alliance,
        var s => throw Wit.Bad("SpeechKind", s),
    };

    public enum LockState
    {
        Up,
        Down,
        Locked,
    }

    internal static void Write(Utf8JsonWriter w, LockState v) => w.WriteStringValue(v switch
    {
        LockState.Up => "up",
        LockState.Down => "down",
        LockState.Locked => "locked",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static LockState ReadLockState(JsonElement e) => e.GetString() switch
    {
        "up" => LockState.Up,
        "down" => LockState.Down,
        "locked" => LockState.Locked,
        var s => throw Wit.Bad("LockState", s),
    };

    public enum Stat
    {
        Str,
        Dex,
        Int,
    }

    internal static void Write(Utf8JsonWriter w, Stat v) => w.WriteStringValue(v switch
    {
        Stat.Str => "str",
        Stat.Dex => "dex",
        Stat.Int => "int",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Stat ReadStat(JsonElement e) => e.GetString() switch
    {
        "str" => Stat.Str,
        "dex" => Stat.Dex,
        "int" => Stat.Int,
        var s => throw Wit.Bad("Stat", s),
    };

    public enum Virtue
    {
        Honor,
        Sacrifice,
        Valor,
    }

    internal static void Write(Utf8JsonWriter w, Virtue v) => w.WriteStringValue(v switch
    {
        Virtue.Honor => "honor",
        Virtue.Sacrifice => "sacrifice",
        Virtue.Valor => "valor",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Virtue ReadVirtue(JsonElement e) => e.GetString() switch
    {
        "honor" => Virtue.Honor,
        "sacrifice" => Virtue.Sacrifice,
        "valor" => Virtue.Valor,
        var s => throw Wit.Bad("Virtue", s),
    };

    public enum Ability
    {
        Primary,
        Secondary,
    }

    internal static void Write(Utf8JsonWriter w, Ability v) => w.WriteStringValue(v switch
    {
        Ability.Primary => "primary",
        Ability.Secondary => "secondary",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Ability ReadAbility(JsonElement e) => e.GetString() switch
    {
        "primary" => Ability.Primary,
        "secondary" => Ability.Secondary,
        var s => throw Wit.Bad("Ability", s),
    };

    public enum Window
    {
        Paperdoll,
        Status,
        Journal,
        Skills,
        Backpack,
        WorldMap,
        Minimap,
        Options,
        Buffs,
        CombatBook,
        Party,
        Guild,
        Quest,
        Logout,
    }

    internal static void Write(Utf8JsonWriter w, Window v) => w.WriteStringValue(v switch
    {
        Window.Paperdoll => "paperdoll",
        Window.Status => "status",
        Window.Journal => "journal",
        Window.Skills => "skills",
        Window.Backpack => "backpack",
        Window.WorldMap => "world-map",
        Window.Minimap => "minimap",
        Window.Options => "options",
        Window.Buffs => "buffs",
        Window.CombatBook => "combat-book",
        Window.Party => "party",
        Window.Guild => "guild",
        Window.Quest => "quest",
        Window.Logout => "logout",
        _ => throw new System.ArgumentOutOfRangeException(nameof(v)),
    });

    internal static Window ReadWindow(JsonElement e) => e.GetString() switch
    {
        "paperdoll" => Window.Paperdoll,
        "status" => Window.Status,
        "journal" => Window.Journal,
        "skills" => Window.Skills,
        "backpack" => Window.Backpack,
        "world-map" => Window.WorldMap,
        "minimap" => Window.Minimap,
        "options" => Window.Options,
        "buffs" => Window.Buffs,
        "combat-book" => Window.CombatBook,
        "party" => Window.Party,
        "guild" => Window.Guild,
        "quest" => Window.Quest,
        "logout" => Window.Logout,
        var s => throw Wit.Bad("Window", s),
    };

    public struct Point
    {
        public ushort X;
        public ushort Y;
        public sbyte Z;
    }

    internal static void Write(Utf8JsonWriter w, Point v)
    {
        w.WriteStartObject();
        w.WritePropertyName("x");
        w.WriteNumberValue(v.X);
        w.WritePropertyName("y");
        w.WriteNumberValue(v.Y);
        w.WritePropertyName("z");
        w.WriteNumberValue(v.Z);
        w.WriteEndObject();
    }

    internal static Point ReadPoint(JsonElement e) => new()
    {
        X = Wit.Field(e, "x").GetUInt16(),
        Y = Wit.Field(e, "y").GetUInt16(),
        Z = Wit.Field(e, "z").GetSByte(),
    };

    public abstract record Destination
    {
        private Destination() { }
        /// <summary>
        /// Into a container; the server picks the slot.
        /// </summary>
        public sealed record Container(uint Value) : Destination;
        /// <summary>
        /// Into a container at a slot (x, y).
        /// </summary>
        public sealed record ContainerAt((uint, ushort, ushort) Value) : Destination;
        /// <summary>
        /// On the ground.
        /// </summary>
        public sealed record Ground(Point Value) : Destination;
    }

    internal static void Write(Utf8JsonWriter w, Destination v)
    {
        w.WriteStartObject();
        switch (v)
        {
            case Destination.Container c:
                w.WritePropertyName("container");
                w.WriteNumberValue(c.Value);
                break;
            case Destination.ContainerAt c:
                w.WritePropertyName("container-at");
                w.WriteStartArray();
                w.WriteNumberValue(c.Value.Item1);
                w.WriteNumberValue(c.Value.Item2);
                w.WriteNumberValue(c.Value.Item3);
                w.WriteEndArray();
                break;
            case Destination.Ground c:
                w.WritePropertyName("ground");
                Write(w, c.Value);
                break;
            default:
                throw new System.ArgumentOutOfRangeException(nameof(v));
        }
        w.WriteEndObject();
    }

    internal static Destination ReadDestination(JsonElement e)
    {
        var (k, p) = Wit.Case(e);
        return k switch
        {
            "container" => new Destination.Container(p.GetUInt32()),
            "container-at" => new Destination.ContainerAt((p[0].GetUInt32(), p[1].GetUInt16(), p[2].GetUInt16())),
            "ground" => new Destination.Ground(ReadPoint(p)),
            _ => throw Wit.Bad("Destination", k),
        };
    }

    /// <summary>
    /// ── items ──
    /// </summary>
    public static void DoubleClick(uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#double-click");
    }

    public static void SingleClick(uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#single-click");
    }

    /// <summary>
    /// Picks the item up onto the cursor (amount 0 = whole stack).
    /// </summary>
    public static void PickUp(uint item, ushort amount)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(item);
        w.WriteNumberValue(amount);
        Wit.Call("cuo:modding/actions#pick-up");
    }

    /// <summary>
    /// Drops the item held on the cursor.
    /// </summary>
    public static void Drop(Destination to)
    {
        var w = Wit.Begin();
        Write(w, to);
        Wit.Call("cuo:modding/actions#drop");
    }

    /// <summary>
    /// Equips the item held on the cursor.
    /// </summary>
    public static void Equip(byte layer, uint mobile)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(layer);
        w.WriteNumberValue(mobile);
        Wit.Call("cuo:modding/actions#equip");
    }

    /// <summary>
    /// Pick up + drop in one step, without touching the cursor.
    /// </summary>
    public static void MoveItem(uint item, ushort amount, Destination to)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(item);
        w.WriteNumberValue(amount);
        Write(w, to);
        Wit.Call("cuo:modding/actions#move-item");
    }

    /// <summary>
    /// Pick up + equip in one step.
    /// </summary>
    public static void Wear(uint item, byte layer, uint mobile)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(item);
        w.WriteNumberValue(layer);
        w.WriteNumberValue(mobile);
        Wit.Call("cuo:modding/actions#wear");
    }

    /// <summary>
    /// Uses `item` on `target` (bandages, keys, ...).
    /// </summary>
    public static void UseItemOn(uint item, uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(item);
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#use-item-on");
    }

    public static void EquipLastWeapon()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#equip-last-weapon");
    }

    public static void Rename(uint mobile, string name)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(mobile);
        w.WriteStringValue(name);
        Wit.Call("cuo:modding/actions#rename");
    }

    public static void RequestProperties(uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#request-properties");
    }

    public static void CloseContainer(uint container)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(container);
        Wit.Call("cuo:modding/actions#close-container");
    }

    /// <summary>
    /// ── movement ──
    /// </summary>
    public static void Walk(Direction dir, bool run)
    {
        var w = Wit.Begin();
        Write(w, dir);
        w.WriteBooleanValue(run);
        Wit.Call("cuo:modding/actions#walk");
    }

    /// <summary>
    /// Pathfinds to a tile.
    /// </summary>
    public static void WalkTo(Point at)
    {
        var w = Wit.Begin();
        Write(w, at);
        Wit.Call("cuo:modding/actions#walk-to");
    }

    public static void CancelWalkTo()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#cancel-walk-to");
    }

    public static void OpenDoor()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#open-door");
    }

    public static void Resync()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#resync");
    }

    /// <summary>
    /// ── combat ──
    /// </summary>
    public static void SetWarMode(bool on)
    {
        var w = Wit.Begin();
        w.WriteBooleanValue(on);
        Wit.Call("cuo:modding/actions#set-war-mode");
    }

    public static void Attack(uint mobile)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(mobile);
        Wit.Call("cuo:modding/actions#attack");
    }

    /// <summary>
    /// Toggles the weapon's special ability.
    /// </summary>
    public static void UseAbility(Ability which)
    {
        var w = Wit.Begin();
        Write(w, which);
        Wit.Call("cuo:modding/actions#use-ability");
    }

    public static void ClearAbility()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#clear-ability");
    }

    public static void ToggleFlying()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#toggle-flying");
    }

    /// <summary>
    /// ── targeting ──
    /// Answers the open target cursor, or queues the answer for the next one.
    /// </summary>
    public static void TargetObject(uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#target-object");
    }

    public static void TargetLocation(Point at, ushort graphic)
    {
        var w = Wit.Begin();
        Write(w, at);
        w.WriteNumberValue(graphic);
        Wit.Call("cuo:modding/actions#target-location");
    }

    public static void TargetCancel()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#target-cancel");
    }

    public static void ClearTargetQueue()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#clear-target-queue");
    }

    /// <summary>
    /// Shows a client-side target cursor; the pick arrives as `cuo:target/local-result`.
    /// </summary>
    public static void RequestTarget(string prompt)
    {
        var w = Wit.Begin();
        w.WriteStringValue(prompt);
        Wit.Call("cuo:modding/actions#request-target");
    }

    /// <summary>
    /// ── spells, skills, virtues ──
    /// </summary>
    public static void CastSpell(ushort id)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(id);
        Wit.Call("cuo:modding/actions#cast-spell");
    }

    public static void OpenSpellbook(byte kind)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(kind);
        Wit.Call("cuo:modding/actions#open-spellbook");
    }

    public static void UseSkill(ushort index)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(index);
        Wit.Call("cuo:modding/actions#use-skill");
    }

    public static void SetSkillLock(ushort index, LockState state)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(index);
        Write(w, state);
        Wit.Call("cuo:modding/actions#set-skill-lock");
    }

    public static void SetStatLock(Stat which, LockState state)
    {
        var w = Wit.Begin();
        Write(w, which);
        Write(w, state);
        Wit.Call("cuo:modding/actions#set-stat-lock");
    }

    public static void InvokeVirtue(Virtue which)
    {
        var w = Wit.Begin();
        Write(w, which);
        Wit.Call("cuo:modding/actions#invoke-virtue");
    }

    /// <summary>
    /// "bow" or "salute".
    /// </summary>
    public static void EmoteAction(string name)
    {
        var w = Wit.Begin();
        w.WriteStringValue(name);
        Wit.Call("cuo:modding/actions#emote-action");
    }

    /// <summary>
    /// ── speech ──
    /// </summary>
    public static void Say(string text, SpeechKind kind, ushort? hue)
    {
        var w = Wit.Begin();
        w.WriteStringValue(text);
        Write(w, kind);
        if (hue is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#say");
    }

    /// <summary>
    /// To the whole party, or one member.
    /// </summary>
    public static void PartySay(string text, uint? to)
    {
        var w = Wit.Begin();
        w.WriteStringValue(text);
        if (to is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#party-say");
    }

    /// <summary>
    /// ── gumps, menus, prompts ──
    /// </summary>
    public static void GumpReply(uint gump, int button, System.ReadOnlySpan<uint> switches, System.ReadOnlySpan<(ushort, string)> texts)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(gump);
        w.WriteNumberValue(button);
        w.WriteStartArray();
        foreach (var x0 in switches)
        {
            w.WriteNumberValue(x0);
        }
        w.WriteEndArray();
        w.WriteStartArray();
        foreach (var x0 in texts)
        {
            w.WriteStartArray();
            w.WriteNumberValue(x0.Item1);
            w.WriteStringValue(x0.Item2);
            w.WriteEndArray();
        }
        w.WriteEndArray();
        Wit.Call("cuo:modding/actions#gump-reply");
    }

    public static void GumpClose(uint gump)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(gump);
        Wit.Call("cuo:modding/actions#gump-close");
    }

    public static void RequestContextMenu(uint target)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        Wit.Call("cuo:modding/actions#request-context-menu");
    }

    public static void ContextMenuReply(uint target, ushort index)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(target);
        w.WriteNumberValue(index);
        Wit.Call("cuo:modding/actions#context-menu-reply");
    }

    public static void PromptReply(string text)
    {
        var w = Wit.Begin();
        w.WriteStringValue(text);
        Wit.Call("cuo:modding/actions#prompt-reply");
    }

    public static void PromptCancel()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#prompt-cancel");
    }

    public static void MenuReply(uint menu, ushort menuId, ushort index, ushort graphic, ushort hue)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(menu);
        w.WriteNumberValue(menuId);
        w.WriteNumberValue(index);
        w.WriteNumberValue(graphic);
        w.WriteNumberValue(hue);
        Wit.Call("cuo:modding/actions#menu-reply");
    }

    public static void TextEntryReply(uint dialog, byte parentId, byte button, string text, bool ok)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(dialog);
        w.WriteNumberValue(parentId);
        w.WriteNumberValue(button);
        w.WriteStringValue(text);
        w.WriteBooleanValue(ok);
        Wit.Call("cuo:modding/actions#text-entry-reply");
    }

    public static void DyeReply(uint tub, ushort graphic, ushort hue)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(tub);
        w.WriteNumberValue(graphic);
        w.WriteNumberValue(hue);
        Wit.Call("cuo:modding/actions#dye-reply");
    }

    public static void HelpRequest()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#help-request");
    }

    /// <summary>
    /// ── party ──
    /// The server answers with a target cursor.
    /// </summary>
    public static void PartyInvite()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#party-invite");
    }

    /// <summary>
    /// None = pick by target.
    /// </summary>
    public static void PartyRemove(uint? member)
    {
        var w = Wit.Begin();
        if (member is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#party-remove");
    }

    public static void PartyAccept(uint leader)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(leader);
        Wit.Call("cuo:modding/actions#party-accept");
    }

    public static void PartyDecline(uint leader)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(leader);
        Wit.Call("cuo:modding/actions#party-decline");
    }

    public static void PartySetLoot(bool shareable)
    {
        var w = Wit.Begin();
        w.WriteBooleanValue(shareable);
        Wit.Call("cuo:modding/actions#party-set-loot");
    }

    /// <summary>
    /// ── trade, vendors ──
    /// </summary>
    public static void TradeAccept(uint container, bool accepted)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(container);
        w.WriteBooleanValue(accepted);
        Wit.Call("cuo:modding/actions#trade-accept");
    }

    public static void TradeCancel(uint container)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(container);
        Wit.Call("cuo:modding/actions#trade-cancel");
    }

    public static void TradeSetGold(uint container, uint gold, uint platinum)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(container);
        w.WriteNumberValue(gold);
        w.WriteNumberValue(platinum);
        Wit.Call("cuo:modding/actions#trade-set-gold");
    }

    public static void VendorBuy(uint vendor, System.ReadOnlySpan<(uint, ushort)> items)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(vendor);
        w.WriteStartArray();
        foreach (var x0 in items)
        {
            w.WriteStartArray();
            w.WriteNumberValue(x0.Item1);
            w.WriteNumberValue(x0.Item2);
            w.WriteEndArray();
        }
        w.WriteEndArray();
        Wit.Call("cuo:modding/actions#vendor-buy");
    }

    public static void VendorSell(uint vendor, System.ReadOnlySpan<(uint, ushort)> items)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(vendor);
        w.WriteStartArray();
        foreach (var x0 in items)
        {
            w.WriteStartArray();
            w.WriteNumberValue(x0.Item1);
            w.WriteNumberValue(x0.Item2);
            w.WriteEndArray();
        }
        w.WriteEndArray();
        Wit.Call("cuo:modding/actions#vendor-sell");
    }

    /// <summary>
    /// ── requests, client ──
    /// None = yourself.
    /// </summary>
    public static void RequestStatus(uint? mobile)
    {
        var w = Wit.Begin();
        if (mobile is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#request-status");
    }

    public static void RequestSkills(uint? mobile)
    {
        var w = Wit.Begin();
        if (mobile is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#request-skills");
    }

    /// <summary>
    /// `target` picks whose paperdoll / status; none = yours.
    /// </summary>
    public static void OpenWindow(Window w_, uint? target)
    {
        var w = Wit.Begin();
        Write(w, w_);
        if (target is { } x0)
        {
            w.WriteNumberValue(x0);
        }
        else
            w.WriteNullValue();
        Wit.Call("cuo:modding/actions#open-window");
    }

    public static void CloseWindow(Window w_)
    {
        var w = Wit.Begin();
        Write(w, w_);
        Wit.Call("cuo:modding/actions#close-window");
    }

    public static void SetViewRange(byte range)
    {
        var w = Wit.Begin();
        w.WriteNumberValue(range);
        Wit.Call("cuo:modding/actions#set-view-range");
    }

    public static void Logout()
    {
        var w = Wit.Begin();
        Wit.Call("cuo:modding/actions#logout");
    }
}
