using System.Text;

namespace CuoModSdk;

/// <summary>
/// The build-time half of the export contract. Every system a mod declares in
/// <c>setup</c> is an export of the mod's own world, named like the system, so the set
/// of systems has to be known when the component is linked — but it is whatever the
/// mod's <see cref="Mod.Setup"/> registers (lambdas, custom <see cref="ISystemParam{TSelf}"/>
/// types, helpers that register for you). So the build RUNS it: ModSdk.targets first
/// builds the mod as a plain net10.0 exe whose Main calls <see cref="Main"/>, which runs
/// Setup against a describing <see cref="ModBuilder"/> (no host involved) and writes
/// <list type="bullet">
/// <item>the export glue (C#): <c>setup</c> plus one <c>[UnmanagedCallersOnly]</c> export
/// per system, lowering its canonical-ABI arguments and dispatching to the system by
/// registration index;</item>
/// <item>the mod's world (WIT, the component type wasm-component-ld encodes): one
/// <c>export</c> per system with its param types, <c>include cuo:modding/mod</c>.</item>
/// </list>
/// The real build then compiles the glue in. At load, <see cref="ModRuntime.Setup"/>
/// checks the mod registered the same systems again.
/// </summary>
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
public static class ModDescribe
{
    // Canonical ABI: more flat params than this spill to memory (not lowered here).
    const int MaxFlatParams = 16;

    /// <summary>args: glue.cs out, world.wit out, the SDK's flattened cuo:modding WIT, mod type, world name.</summary>
    public static int Main(Mod mod, string[] args)
    {
        if (args.Length != 5)
        {
            Console.Error.WriteLine("usage: <exports.g.cs> <world.wit> <sdk component-type wit> <mod type> <world name>");
            return 2;
        }
        List<Entry> entries;
        try
        {
            var m = new ModBuilder(new ModHost());
            mod.Setup(m);
            m.Finish();
            entries = m.Entries;
            foreach (var e in entries)
            {
                // A typed observer spills to memory past the limit (Glue reads the args area).
                if (e.Trigger?.Typed != null)
                    continue;
                var flat = (e.Trigger == null ? 0 : 3) + e.Params.Count;
                if (flat > MaxFlatParams)
                    throw new InvalidOperationException($"{e.Signature()}: {flat} canonical-ABI params, at most {MaxFlatParams} are supported — split the system");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"error CUOMOD1: describing the mod's systems failed: {ex.GetType().Name}: {ex.Message}");
            Console.Error.WriteLine("  (the build runs the mod's Setup on the build machine to learn its exports: Setup and the mod's constructor must only register systems, no host calls)");
            return 1;
        }
        var world = WorldName(args[4]);
        Write(args[0], Glue(entries, args[3]));
        Write(args[1], Wit(entries, world, File.ReadAllText(args[2])));
        Console.WriteLine($"cuo-mod: {entries.Count} system export(s): {string.Join(", ", entries.Select(e => e.Name))}");
        return 0;
    }

    // Keeps the timestamp (and so the incremental build) when nothing changed.
    static void Write(string path, string text)
    {
        if (File.Exists(path) && File.ReadAllText(path) == text)
            return;
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, text);
    }

    static string WorldName(string targetName)
    {
        try
        {
            return Entry.ExportName(targetName);
        }
        catch (ArgumentException)
        {
            return "this-mod";
        }
    }

    static string Glue(List<Entry> entries, string modType)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> by CuoModSdk.ModDescribe (ModSdk.targets): the component's exports.");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using CuoModRuntime = global::CuoModSdk.ModRuntime;");
        sb.AppendLine();
        sb.AppendLine("internal static unsafe class CuoModExports");
        sb.AppendLine("{");
        sb.AppendLine("    static readonly string[] Exported =");
        sb.AppendLine("    [");
        foreach (var e in entries)
            sb.AppendLine($"        \"{e.Signature()}\",");
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    // setup: func(app: app)");
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"setup\")]");
        sb.AppendLine($"    static void Setup(int app) => CuoModRuntime.Setup(app, new global::{modType}(), Exported);");
        for (var i = 0; i < entries.Count; i++)
        {
            var e = entries[i];
            var n = e.Params.Count;
            var ps = string.Concat(Enumerable.Range(0, n).Select(k => $", int p{k}"));
            var handles = n == 0 ? "null, 0" : "h, " + n;
            var stack = n == 0 ? "" : $"int* h = stackalloc int[{n}] {{ {string.Join(", ", Enumerable.Range(0, n).Select(k => "p" + k))} }}; ";
            sb.AppendLine();
            sb.AppendLine($"    // {e.Signature()}");
            sb.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"{e.Name}\")]");
            if (e.Trigger == null)
                sb.AppendLine($"    static void E{i}({ps.TrimStart(',', ' ')}) {{ {stack}CuoModRuntime.RunSystem({i}, {handles}); }}");
            else if (e.IsPacket)
            {
                sb.AppendLine($"    static nint E{i}(int direction, nint packet, int packetLen{ps}) {{ {stack}return CuoModRuntime.RunPacket({i}, direction, packet, packetLen, {handles}); }}");
                sb.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"cabi_post_{e.Name}\")]");
                sb.AppendLine($"    static void Post{i}(nint ret) => CuoModRuntime.PostPacket(ret);");
            }
            else if (e.Trigger.Typed is { } typed)
                TypedObserver(sb, i, typed, n);
            else
                sb.AppendLine($"    static void E{i}(long entity, nint value, int valueLen{ps}) {{ {stack}CuoModRuntime.RunObserver({i}, entity, value, valueLen, {handles}); }}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    // A typed observer: func(entity: entity, value: <record>, p0..) — the record's flat core
    // params are stored back into a stack record; past 16 flat params the host passes one
    // pointer to the args tuple (entity @0, record, handles), which the guest frees.
    static void TypedObserver(StringBuilder sb, int i, TypedTrigger typed, int n)
    {
        var flat = typed.Record == null ? 0 : typed.Flat.Length;
        var handles = n == 0 ? "null, 0" : "h, " + n;
        if (1 + flat + n <= MaxFlatParams)
        {
            var ps = new List<string> { "long entity" };
            ps.AddRange(Enumerable.Range(0, flat).Select(k => $"{typed.Flat[k].Core} f{k}"));
            ps.AddRange(Enumerable.Range(0, n).Select(k => $"int p{k}"));
            sb.Append($"    static void E{i}({string.Join(", ", ps)}) {{ ");
            var rec = "0";
            if (typed.Record != null)
            {
                sb.Append($"var r = stackalloc ulong[{(typed.Size + 7) / 8}]; var rec = (byte*)r; ");
                for (var k = 0; k < flat; k++)
                    sb.Append($"*({typed.Flat[k].Store}*)(rec + {typed.Flat[k].Offset}) = ({typed.Flat[k].Store})f{k}; ");
                rec = "(nint)rec";
            }
            if (n > 0)
                sb.Append($"int* h = stackalloc int[{n}] {{ {string.Join(", ", Enumerable.Range(0, n).Select(k => "p" + k))} }}; ");
            sb.AppendLine($"CuoModRuntime.RunObserverTyped({i}, entity, {rec}, {handles}, 0); }}");
            return;
        }
        // Spilled: (entity u64 @0, record @align, handles i32...).
        var off = 8;
        var recOff = 0;
        if (typed.Record != null)
        {
            recOff = (off + typed.Align - 1) / typed.Align * typed.Align;
            off = recOff + typed.Size;
        }
        var hs = new List<string>();
        for (var k = 0; k < n; k++)
        {
            off = (off + 3) / 4 * 4;
            hs.Add($"*(int*)(a + {off})");
            off += 4;
        }
        sb.Append($"    static void E{i}(nint args) {{ var a = (byte*)args; ");
        if (n > 0)
            sb.Append($"int* h = stackalloc int[{n}] {{ {string.Join(", ", hs)} }}; ");
        var r = typed.Record != null ? $"(nint)(a + {recOff})" : "0";
        sb.AppendLine($"CuoModRuntime.RunObserverTyped({i}, *(long*)a, {r}, {handles}, args); }}");
    }

    static string Wit(List<Entry> entries, string world, string sdkWit)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> by CuoModSdk.ModDescribe (ModSdk.targets): this mod's world, one export per system.");
        sb.AppendLine($"package cuo-mod:{world};");
        sb.AppendLine();
        sb.AppendLine($"world {world} {{");
        sb.AppendLine("    use tinyecs:modding/ecs@0.1.0.{commands, query, res, events, entity, trigger-data, packet-direction, verdict};");
        var records = entries.Select(e => e.Trigger?.Typed?.Record).OfType<string>().Distinct().ToList();
        if (records.Count > 0)
            sb.AppendLine($"    use cuo:modding/types@0.1.0.{{{string.Join(", ", records)}}};");
        sb.AppendLine();
        foreach (var e in entries)
        {
            var args = new List<string>();
            if (e.IsPacket)
            {
                args.Add("direction: packet-direction");
                args.Add("packet: list<u8>");
            }
            else if (e.Trigger?.Typed is { } typed)
            {
                args.Add("entity: entity");
                if (typed.Record != null)
                    args.Add("value: " + typed.Record);
            }
            else if (e.Trigger != null)
                args.Add("trigger: trigger-data");
            for (var k = 0; k < e.Params.Count; k++)
                args.Add($"p{k}: {Entry.WitType(e.Params[k].Kind)}");
            sb.AppendLine($"    export {e.Name}: func({string.Join(", ", args)}){(e.IsPacket ? " -> verdict" : "")};");
        }
        sb.AppendLine();
        sb.AppendLine("    include cuo:modding/mod@0.1.0;");
        sb.AppendLine("}");
        sb.AppendLine();
        // The SDK's flattened contract (wit-bindgen's component-type WIT: cuo:modding as the
        // file's package, tinyecs:modding nested), re-nested under this file's package.
        var opened = false;
        foreach (var line in sdkWit.Replace("\r\n", "\n").Split('\n'))
        {
            if (!opened && line.StartsWith("package ") && line.TrimEnd().EndsWith(';'))
            {
                sb.AppendLine(line.TrimEnd()[..^1] + " {");
                opened = true;
                continue;
            }
            if (opened && line.StartsWith("package "))
            {
                sb.AppendLine("}");
                opened = false;
            }
            sb.AppendLine(line);
        }
        if (opened)
            sb.AppendLine("}");
        return sb.ToString();
    }
}
