// <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk

namespace CuoModSdk;

/// <summary>
/// Registry type-path constants, mirrored from
/// <c>src/ClassicUO.Ecs/Modding/CuoModdingRegistry.cs</c>. A mod normally names the
/// generated payload type instead (<c>Query&lt;Data&lt;Hits&gt;&gt;</c>); these are the
/// canonical strings behind them, for diagnostics and host-side lookups.
/// <para>Naming: <c>cuo:&lt;module&gt;/&lt;leaf&gt;</c> becomes
/// <c>Paths.&lt;Module&gt;.&lt;Leaf&gt;</c>, both PascalCase with <c>-</c> dropped
/// (<c>cuo:player/stat-locks</c> → <c>Paths.Player.StatLocks</c>). A leaf that would
/// repeat its class name gets a <c>Path</c> suffix — C# forbids the collision
/// (<c>cuo:player/player</c> → <c>Paths.Player.PlayerPath</c>).</para>
/// </summary>
public static class Paths
{
    public static class Action
    {
        /// <summary><c>cuo:action/cast-spell</c> — event.</summary>
        public const string CastSpell = "cuo:action/cast-spell";
        /// <summary><c>cuo:action/context-menu-reply</c> — event.</summary>
        public const string ContextMenuReply = "cuo:action/context-menu-reply";
        /// <summary><c>cuo:action/double-click</c> — event.</summary>
        public const string DoubleClick = "cuo:action/double-click";
        /// <summary><c>cuo:action/drop</c> — event.</summary>
        public const string Drop = "cuo:action/drop";
        /// <summary><c>cuo:action/equip</c> — event.</summary>
        public const string Equip = "cuo:action/equip";
        /// <summary><c>cuo:action/gump-close</c> — event.</summary>
        public const string GumpClose = "cuo:action/gump-close";
        /// <summary><c>cuo:action/gump-reply</c> — event.</summary>
        public const string GumpReply = "cuo:action/gump-reply";
        /// <summary><c>cuo:action/open-door</c> — event.</summary>
        public const string OpenDoor = "cuo:action/open-door";
        /// <summary><c>cuo:action/pickup</c> — event.</summary>
        public const string Pickup = "cuo:action/pickup";
        /// <summary><c>cuo:action/prompt-reply</c> — event.</summary>
        public const string PromptReply = "cuo:action/prompt-reply";
        /// <summary><c>cuo:action/rename</c> — event.</summary>
        public const string Rename = "cuo:action/rename";
        /// <summary><c>cuo:action/request-context-menu</c> — event.</summary>
        public const string RequestContextMenu = "cuo:action/request-context-menu";
        /// <summary><c>cuo:action/request-properties</c> — event.</summary>
        public const string RequestProperties = "cuo:action/request-properties";
        /// <summary><c>cuo:action/request-skills</c> — event.</summary>
        public const string RequestSkills = "cuo:action/request-skills";
        /// <summary><c>cuo:action/request-status</c> — event.</summary>
        public const string RequestStatus = "cuo:action/request-status";
        /// <summary><c>cuo:action/request-target</c> — event.</summary>
        public const string RequestTarget = "cuo:action/request-target";
        /// <summary><c>cuo:action/say</c> — event.</summary>
        public const string Say = "cuo:action/say";
        /// <summary><c>cuo:action/single-click</c> — event.</summary>
        public const string SingleClick = "cuo:action/single-click";
        /// <summary><c>cuo:action/target-cancel</c> — event.</summary>
        public const string TargetCancel = "cuo:action/target-cancel";
        /// <summary><c>cuo:action/target-location</c> — event.</summary>
        public const string TargetLocation = "cuo:action/target-location";
        /// <summary><c>cuo:action/target-object</c> — event.</summary>
        public const string TargetObject = "cuo:action/target-object";
        /// <summary><c>cuo:action/toggle-war-mode</c> — event.</summary>
        public const string ToggleWarMode = "cuo:action/toggle-war-mode";
        /// <summary><c>cuo:action/use-skill</c> — event.</summary>
        public const string UseSkill = "cuo:action/use-skill";
        /// <summary><c>cuo:action/walk</c> — event.</summary>
        public const string Walk = "cuo:action/walk";
        /// <summary><c>cuo:action/walk-to</c> — event.</summary>
        public const string WalkTo = "cuo:action/walk-to";
    }

    public static class Chat
    {
        /// <summary><c>cuo:chat/message</c> — event.</summary>
        public const string Message = "cuo:chat/message";
        /// <summary><c>cuo:chat/prompt</c> — event.</summary>
        public const string Prompt = "cuo:chat/prompt";
    }

    public static class Engine
    {
        /// <summary><c>cuo:engine/time</c> — resource.</summary>
        public const string Time = "cuo:engine/time";
    }

    public static class Ent
    {
        /// <summary><c>cuo:ent/amount</c> — component.</summary>
        public const string Amount = "cuo:ent/amount";
        /// <summary><c>cuo:ent/animation</c> — component.</summary>
        public const string Animation = "cuo:ent/animation";
        /// <summary><c>cuo:ent/contained-into</c> — component.</summary>
        public const string ContainedInto = "cuo:ent/contained-into";
        /// <summary><c>cuo:ent/container</c> — component.</summary>
        public const string Container = "cuo:ent/container";
        /// <summary><c>cuo:ent/equipment</c> — component.</summary>
        public const string Equipment = "cuo:ent/equipment";
        /// <summary><c>cuo:ent/facing</c> — component.</summary>
        public const string Facing = "cuo:ent/facing";
        /// <summary><c>cuo:ent/graphic</c> — component.</summary>
        public const string Graphic = "cuo:ent/graphic";
        /// <summary><c>cuo:ent/hue</c> — component.</summary>
        public const string Hue = "cuo:ent/hue";
        /// <summary><c>cuo:ent/is-container</c> — component.</summary>
        public const string IsContainer = "cuo:ent/is-container";
        /// <summary><c>cuo:ent/is-item</c> — component.</summary>
        public const string IsItem = "cuo:ent/is-item";
        /// <summary><c>cuo:ent/is-mobile</c> — component.</summary>
        public const string IsMobile = "cuo:ent/is-mobile";
        /// <summary><c>cuo:ent/is-multi</c> — component.</summary>
        public const string IsMulti = "cuo:ent/is-multi";
        /// <summary><c>cuo:ent/mob-steps</c> — component.</summary>
        public const string MobSteps = "cuo:ent/mob-steps";
        /// <summary><c>cuo:ent/name</c> — component.</summary>
        public const string Name = "cuo:ent/name";
        /// <summary><c>cuo:ent/notoriety</c> — component.</summary>
        public const string Notoriety = "cuo:ent/notoriety";
        /// <summary><c>cuo:ent/properties</c> — component.</summary>
        public const string Properties = "cuo:ent/properties";
        /// <summary><c>cuo:ent/serial</c> — component.</summary>
        public const string Serial = "cuo:ent/serial";
        /// <summary><c>cuo:ent/server-flags</c> — component.</summary>
        public const string ServerFlags = "cuo:ent/server-flags";
        /// <summary><c>cuo:ent/slot-position</c> — component.</summary>
        public const string SlotPosition = "cuo:ent/slot-position";
        /// <summary><c>cuo:ent/world-position</c> — component.</summary>
        public const string WorldPosition = "cuo:ent/world-position";
    }

    public static class Game
    {
        /// <summary><c>cuo:game/context</c> — resource.</summary>
        public const string Context = "cuo:game/context";
        /// <summary><c>cuo:game/state</c> — resource.</summary>
        public const string State = "cuo:game/state";
    }

    public static class Gump
    {
        /// <summary><c>cuo:gump/book</c> — component (presence-only).</summary>
        public const string Book = "cuo:gump/book";
        /// <summary><c>cuo:gump/buff</c> — component.</summary>
        public const string Buff = "cuo:gump/buff";
        /// <summary><c>cuo:gump/bulletin-board</c> — component (presence-only).</summary>
        public const string BulletinBoard = "cuo:gump/bulletin-board";
        /// <summary><c>cuo:gump/combat-book</c> — component.</summary>
        public const string CombatBook = "cuo:gump/combat-book";
        /// <summary><c>cuo:gump/container</c> — component.</summary>
        public const string Container = "cuo:gump/container";
        /// <summary><c>cuo:gump/container-closed</c> — event.</summary>
        public const string ContainerClosed = "cuo:gump/container-closed";
        /// <summary><c>cuo:gump/container-opened</c> — event.</summary>
        public const string ContainerOpened = "cuo:gump/container-opened";
        /// <summary><c>cuo:gump/context-menu</c> — event.</summary>
        public const string ContextMenu = "cuo:gump/context-menu";
        /// <summary><c>cuo:gump/grid-container</c> — component.</summary>
        public const string GridContainer = "cuo:gump/grid-container";
        /// <summary><c>cuo:gump/grid-loot</c> — component.</summary>
        public const string GridLoot = "cuo:gump/grid-loot";
        /// <summary><c>cuo:gump/health-bar</c> — component.</summary>
        public const string HealthBar = "cuo:gump/health-bar";
        /// <summary><c>cuo:gump/house-design</c> — component.</summary>
        public const string HouseDesign = "cuo:gump/house-design";
        /// <summary><c>cuo:gump/journal</c> — component.</summary>
        public const string Journal = "cuo:gump/journal";
        /// <summary><c>cuo:gump/logout</c> — component.</summary>
        public const string Logout = "cuo:gump/logout";
        /// <summary><c>cuo:gump/map</c> — component (presence-only).</summary>
        public const string Map = "cuo:gump/map";
        /// <summary><c>cuo:gump/menu</c> — component.</summary>
        public const string Menu = "cuo:gump/menu";
        /// <summary><c>cuo:gump/message-box</c> — component.</summary>
        public const string MessageBox = "cuo:gump/message-box";
        /// <summary><c>cuo:gump/minimap</c> — component.</summary>
        public const string Minimap = "cuo:gump/minimap";
        /// <summary><c>cuo:gump/paperdoll</c> — component.</summary>
        public const string Paperdoll = "cuo:gump/paperdoll";
        /// <summary><c>cuo:gump/party-invite</c> — component.</summary>
        public const string PartyInvite = "cuo:gump/party-invite";
        /// <summary><c>cuo:gump/party-manifest</c> — component.</summary>
        public const string PartyManifest = "cuo:gump/party-manifest";
        /// <summary><c>cuo:gump/profile</c> — component.</summary>
        public const string Profile = "cuo:gump/profile";
        /// <summary><c>cuo:gump/racial-book</c> — component.</summary>
        public const string RacialBook = "cuo:gump/racial-book";
        /// <summary><c>cuo:gump/server</c> — component.</summary>
        public const string Server = "cuo:gump/server";
        /// <summary><c>cuo:gump/server-closed</c> — event.</summary>
        public const string ServerClosed = "cuo:gump/server-closed";
        /// <summary><c>cuo:gump/server-opened</c> — event.</summary>
        public const string ServerOpened = "cuo:gump/server-opened";
        /// <summary><c>cuo:gump/skills</c> — component.</summary>
        public const string Skills = "cuo:gump/skills";
        /// <summary><c>cuo:gump/spellbook</c> — component.</summary>
        public const string Spellbook = "cuo:gump/spellbook";
        /// <summary><c>cuo:gump/split-menu</c> — component.</summary>
        public const string SplitMenu = "cuo:gump/split-menu";
        /// <summary><c>cuo:gump/tip-notice</c> — component.</summary>
        public const string TipNotice = "cuo:gump/tip-notice";
        /// <summary><c>cuo:gump/trade</c> — component.</summary>
        public const string Trade = "cuo:gump/trade";
        /// <summary><c>cuo:gump/vendor</c> — component (presence-only).</summary>
        public const string Vendor = "cuo:gump/vendor";
        /// <summary><c>cuo:gump/worldmap</c> — component.</summary>
        public const string Worldmap = "cuo:gump/worldmap";
    }

    public static class Input
    {
        /// <summary><c>cuo:input/host-hotkeys</c> — resource.</summary>
        public const string HostHotkeys = "cuo:input/host-hotkeys";
        /// <summary><c>cuo:input/hotkey</c> — event.</summary>
        public const string Hotkey = "cuo:input/hotkey";
        /// <summary><c>cuo:input/keyboard</c> — resource.</summary>
        public const string Keyboard = "cuo:input/keyboard";
        /// <summary><c>cuo:input/mod-hotkeys</c> — resource.</summary>
        public const string ModHotkeys = "cuo:input/mod-hotkeys";
        /// <summary><c>cuo:input/mouse</c> — resource.</summary>
        public const string Mouse = "cuo:input/mouse";
        /// <summary><c>cuo:input/world-single-click</c> — resource.</summary>
        public const string WorldSingleClick = "cuo:input/world-single-click";
    }

    public static class Mod
    {
        /// <summary><c>cuo:mod/owned</c> — component (presence-only).</summary>
        public const string Owned = "cuo:mod/owned";
        /// <summary><c>cuo:mod/state</c> — component.</summary>
        public const string State = "cuo:mod/state";
    }

    public static class Player
    {
        /// <summary><c>cuo:player/buffs</c> — resource.</summary>
        public const string Buffs = "cuo:player/buffs";
        /// <summary><c>cuo:player/data</c> — component.</summary>
        public const string Data = "cuo:player/data";
        /// <summary><c>cuo:player/grabbed-item</c> — resource.</summary>
        public const string GrabbedItem = "cuo:player/grabbed-item";
        /// <summary><c>cuo:player/hits</c> — component.</summary>
        public const string Hits = "cuo:player/hits";
        /// <summary><c>cuo:player/mana</c> — component.</summary>
        public const string Mana = "cuo:player/mana";
        /// <summary><c>cuo:player/move-request</c> — event.</summary>
        public const string MoveRequest = "cuo:player/move-request";
        /// <summary><c>cuo:player/party</c> — resource.</summary>
        public const string Party = "cuo:player/party";
        /// <summary><c>cuo:player/player</c> — component.</summary>
        public const string PlayerPath = "cuo:player/player";
        /// <summary><c>cuo:player/skills</c> — resource.</summary>
        public const string Skills = "cuo:player/skills";
        /// <summary><c>cuo:player/spellbook</c> — resource.</summary>
        public const string Spellbook = "cuo:player/spellbook";
        /// <summary><c>cuo:player/stamina</c> — component.</summary>
        public const string Stamina = "cuo:player/stamina";
        /// <summary><c>cuo:player/stat-locks</c> — component.</summary>
        public const string StatLocks = "cuo:player/stat-locks";
        /// <summary><c>cuo:player/steps</c> — resource.</summary>
        public const string Steps = "cuo:player/steps";
    }

    public static class Scene
    {
        /// <summary><c>cuo:scene/character-creation</c> — component.</summary>
        public const string CharacterCreation = "cuo:scene/character-creation";
        /// <summary><c>cuo:scene/character-list</c> — event.</summary>
        public const string CharacterList = "cuo:scene/character-list";
        /// <summary><c>cuo:scene/character-selection</c> — component.</summary>
        public const string CharacterSelection = "cuo:scene/character-selection";
        /// <summary><c>cuo:scene/game</c> — component.</summary>
        public const string Game = "cuo:scene/game";
        /// <summary><c>cuo:scene/login</c> — component.</summary>
        public const string Login = "cuo:scene/login";
        /// <summary><c>cuo:scene/login-error</c> — component.</summary>
        public const string LoginError = "cuo:scene/login-error";
        /// <summary><c>cuo:scene/login-error-info</c> — event.</summary>
        public const string LoginErrorInfo = "cuo:scene/login-error-info";
        /// <summary><c>cuo:scene/login-request</c> — event.</summary>
        public const string LoginRequest = "cuo:scene/login-request";
        /// <summary><c>cuo:scene/server-list</c> — event.</summary>
        public const string ServerList = "cuo:scene/server-list";
        /// <summary><c>cuo:scene/server-selection</c> — component.</summary>
        public const string ServerSelection = "cuo:scene/server-selection";
    }

    public static class Target
    {
        /// <summary><c>cuo:target/local-result</c> — event.</summary>
        public const string LocalResult = "cuo:target/local-result";
        /// <summary><c>cuo:target/state</c> — resource.</summary>
        public const string State = "cuo:target/state";
    }

    public static class Test
    {
        /// <summary><c>cuo:test/counter</c> — component.</summary>
        public const string Counter = "cuo:test/counter";
    }

    public static class Ui
    {
        /// <summary><c>cuo:ui/bg-color</c> — component.</summary>
        public const string BgColor = "cuo:ui/bg-color";
        /// <summary><c>cuo:ui/border-radius</c> — component.</summary>
        public const string BorderRadius = "cuo:ui/border-radius";
        /// <summary><c>cuo:ui/button</c> — component.</summary>
        public const string Button = "cuo:ui/button";
        /// <summary><c>cuo:ui/clicked</c> — component.</summary>
        public const string Clicked = "cuo:ui/clicked";
        /// <summary><c>cuo:ui/contains-by-bounds</c> — component.</summary>
        public const string ContainsByBounds = "cuo:ui/contains-by-bounds";
        /// <summary><c>cuo:ui/custom</c> — component.</summary>
        public const string Custom = "cuo:ui/custom";
        /// <summary><c>cuo:ui/editable-text</c> — component.</summary>
        public const string EditableText = "cuo:ui/editable-text";
        /// <summary><c>cuo:ui/focused-input</c> — resource.</summary>
        public const string FocusedInput = "cuo:ui/focused-input";
        /// <summary><c>cuo:ui/global-z</c> — component.</summary>
        public const string GlobalZ = "cuo:ui/global-z";
        /// <summary><c>cuo:ui/hover-tint</c> — component.</summary>
        public const string HoverTint = "cuo:ui/hover-tint";
        /// <summary><c>cuo:ui/hovered</c> — component.</summary>
        public const string Hovered = "cuo:ui/hovered";
        /// <summary><c>cuo:ui/interaction</c> — component.</summary>
        public const string Interaction = "cuo:ui/interaction";
        /// <summary><c>cuo:ui/masked-text</c> — component.</summary>
        public const string MaskedText = "cuo:ui/masked-text";
        /// <summary><c>cuo:ui/movable</c> — component.</summary>
        public const string Movable = "cuo:ui/movable";
        /// <summary><c>cuo:ui/movable-no-drag</c> — component.</summary>
        public const string MovableNoDrag = "cuo:ui/movable-no-drag";
        /// <summary><c>cuo:ui/name</c> — component.</summary>
        public const string Name = "cuo:ui/name";
        /// <summary><c>cuo:ui/no-blur</c> — component.</summary>
        public const string NoBlur = "cuo:ui/no-blur";
        /// <summary><c>cuo:ui/no-right-click-close</c> — component.</summary>
        public const string NoRightClickClose = "cuo:ui/no-right-click-close";
        /// <summary><c>cuo:ui/no-window-drag</c> — component.</summary>
        public const string NoWindowDrag = "cuo:ui/no-window-drag";
        /// <summary><c>cuo:ui/node</c> — component.</summary>
        public const string Node = "cuo:ui/node";
        /// <summary><c>cuo:ui/options-window</c> — component.</summary>
        public const string OptionsWindow = "cuo:ui/options-window";
        /// <summary><c>cuo:ui/popup</c> — component.</summary>
        public const string Popup = "cuo:ui/popup";
        /// <summary><c>cuo:ui/right-clicked</c> — component.</summary>
        public const string RightClicked = "cuo:ui/right-clicked";
        /// <summary><c>cuo:ui/scroll</c> — component.</summary>
        public const string Scroll = "cuo:ui/scroll";
        /// <summary><c>cuo:ui/scrollbar</c> — component.</summary>
        public const string Scrollbar = "cuo:ui/scrollbar";
        /// <summary><c>cuo:ui/stat-lock-button</c> — component.</summary>
        public const string StatLockButton = "cuo:ui/stat-lock-button";
        /// <summary><c>cuo:ui/statusbar-window</c> — component.</summary>
        public const string StatusbarWindow = "cuo:ui/statusbar-window";
        /// <summary><c>cuo:ui/surface</c> — resource.</summary>
        public const string Surface = "cuo:ui/surface";
        /// <summary><c>cuo:ui/text</c> — component.</summary>
        public const string Text = "cuo:ui/text";
        /// <summary><c>cuo:ui/text-caret</c> — resource.</summary>
        public const string TextCaret = "cuo:ui/text-caret";
        /// <summary><c>cuo:ui/text-clipboard-action</c> — resource.</summary>
        public const string TextClipboardAction = "cuo:ui/text-clipboard-action";
        /// <summary><c>cuo:ui/text-color</c> — component.</summary>
        public const string TextColor = "cuo:ui/text-color";
        /// <summary><c>cuo:ui/text-completion</c> — resource.</summary>
        public const string TextCompletion = "cuo:ui/text-completion";
        /// <summary><c>cuo:ui/text-completion-pick</c> — resource.</summary>
        public const string TextCompletionPick = "cuo:ui/text-completion-pick";
        /// <summary><c>cuo:ui/text-completion-state</c> — resource.</summary>
        public const string TextCompletionState = "cuo:ui/text-completion-state";
        /// <summary><c>cuo:ui/text-font</c> — component.</summary>
        public const string TextFont = "cuo:ui/text-font";
        /// <summary><c>cuo:ui/text-input</c> — component.</summary>
        public const string TextInput = "cuo:ui/text-input";
        /// <summary><c>cuo:ui/text-spans</c> — component.</summary>
        public const string TextSpans = "cuo:ui/text-spans";
        /// <summary><c>cuo:ui/text-wrap</c> — component.</summary>
        public const string TextWrap = "cuo:ui/text-wrap";
        /// <summary><c>cuo:ui/tooltip</c> — component.</summary>
        public const string Tooltip = "cuo:ui/tooltip";
        /// <summary><c>cuo:ui/topbar-bg</c> — component.</summary>
        public const string TopbarBg = "cuo:ui/topbar-bg";
        /// <summary><c>cuo:ui/topbar-button</c> — component.</summary>
        public const string TopbarButton = "cuo:ui/topbar-button";
        /// <summary><c>cuo:ui/topbar-full</c> — component.</summary>
        public const string TopbarFull = "cuo:ui/topbar-full";
        /// <summary><c>cuo:ui/topbar-root</c> — component.</summary>
        public const string TopbarRoot = "cuo:ui/topbar-root";
    }
}
