// <auto-generated> by tools/mod-typegen — do not edit; run make gen-mod-sdk

using System.Text.Json.Serialization;

// Own namespace; mods opt in with `using CuoModSdk.Types;`. Every shape is emitted
// `partial` so the hand-written SDK can hang constructors off it (see Types.Ui.cs,
// which owns Node.Abs / Val.Px / Color.Rgba) without a second, drifting type.
namespace CuoModSdk.Types;

// Payload types for every registered type-path: the exact JSON the host writes and
// reads through System.Text.Json (IncludeFields = true, no naming policy, enums as
// numbers). Host value types stay structs here so a default instance serializes to
// the host's default, not to nulls.

/// <remarks><c>TinyEcs.Bevy.UI.AlignItems</c> — crosses the boundary as a number.</remarks>
public enum AlignItems : byte
{
    Start = 0,
    Center = 1,
    End = 2,
}

/// <summary><c>cuo:ent/amount</c></summary>
public partial struct Amount
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/amount";

    [JsonPropertyName("Value")] public int Value;
}

/// <summary><c>cuo:ui/bg-color</c></summary>
public partial struct BackgroundColor
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/bg-color";

    [JsonPropertyName("Value")] public Color Value;
}

/// <summary><c>cuo:gump/book</c>
/// <para>Presence-only marker: the host always answers <c>{}</c> and ignores writes.</para>
/// </summary>
public partial struct BookWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/book";
}

/// <summary><c>cuo:ui/border-radius</c></summary>
public partial struct BorderRadius
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/border-radius";

    [JsonPropertyName("TopLeft")] public float TopLeft;
    [JsonPropertyName("TopRight")] public float TopRight;
    [JsonPropertyName("BottomLeft")] public float BottomLeft;
    [JsonPropertyName("BottomRight")] public float BottomRight;
}

/// <summary><c>cuo:gump/buff</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct BuffGumpUI
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/buff";
}

/// <summary><c>cuo:gump/bulletin-board</c>
/// <para>Presence-only marker: the host always answers <c>{}</c> and ignores writes.</para>
/// </summary>
public partial struct BulletinBoardWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/bulletin-board";
}

/// <summary><c>cuo:action/cast-spell</c></summary>
public partial struct CastSpellAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/cast-spell";

    [JsonPropertyName("Id")] public int Id;
}

/// <summary><c>cuo:scene/character-creation</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct CharCreationScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/character-creation";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.CharInfoDto</c>).</summary>
public partial struct CharInfoDto
{
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Index")] public uint Index;
}

/// <summary><c>cuo:scene/character-list</c></summary>
public partial struct CharacterSelectionDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/character-list";

    [JsonPropertyName("Characters")] public CharInfoDto[] Characters;
    [JsonPropertyName("Towns")] public TownInfoDto[] Towns;
}

/// <summary><c>cuo:scene/character-selection</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct CharacterSelectionScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/character-selection";
}

/// <summary>Nested payload type (<c>Clay.Color</c>).</summary>
public partial struct Color
{
    [JsonPropertyName("R")] public float R;
    [JsonPropertyName("G")] public float G;
    [JsonPropertyName("B")] public float B;
    [JsonPropertyName("A")] public float A;
    /// <remarks>Host-computed: written by the host, ignored when a mod sets it.</remarks>
    [JsonPropertyName("IsVisible")] public bool IsVisible;
}

/// <summary><c>cuo:gump/combat-book</c></summary>
public partial struct CombatBookWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/combat-book";

    [JsonPropertyName("Page")] public int Page;
    [JsonPropertyName("SoundedPage")] public int SoundedPage;
    [JsonPropertyName("PageCount")] public int PageCount;
    [JsonPropertyName("DictPages")] public int DictPages;
    [JsonPropertyName("AbilityCount")] public int AbilityCount;
    [JsonPropertyName("Dirty")] public bool Dirty;
    [JsonPropertyName("Content")] public ulong Content;
    [JsonPropertyName("Left")] public ulong Left;
    [JsonPropertyName("Right")] public ulong Right;
}

/// <summary><c>cuo:ent/container</c></summary>
public partial struct ContainedInDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/container";

    [JsonPropertyName("Container")] public uint Container;
}

/// <summary><c>cuo:ent/contained-into</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct ContainedInto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/contained-into";
}

/// <summary><c>cuo:gump/container-closed</c></summary>
public partial struct ContainerClosedEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/container-closed";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("UserInitiated")] public bool UserInitiated;
}

/// <summary><c>cuo:gump/container-opened</c></summary>
public partial struct ContainerOpenedEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/container-opened";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Graphic")] public ushort Graphic;
}

/// <summary><c>cuo:ent/slot-position</c></summary>
public partial struct ContainerSlotPosition
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/slot-position";

    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("GridIndex")] public byte GridIndex;
}

/// <summary><c>cuo:gump/container</c></summary>
public partial struct ContainerWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/container";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.ContextMenuEntry</c>).</summary>
public partial struct ContextMenuEntry
{
    [JsonPropertyName("Index")] public ushort Index;
    [JsonPropertyName("Cliloc")] public int Cliloc;
    [JsonPropertyName("Text")] public string Text;
    [JsonPropertyName("Flags")] public ushort Flags;
    [JsonPropertyName("Hue")] public ushort Hue;
}

/// <summary><c>cuo:gump/context-menu</c></summary>
public partial struct ContextMenuEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/context-menu";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Entries")] public ContextMenuEntry[] Entries;
}

/// <summary><c>cuo:action/context-menu-reply</c></summary>
public partial struct ContextMenuReplyAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/context-menu-reply";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Index")] public ushort Index;
}

/// <remarks><c>ClassicUO.Game.Data.Direction</c> — crosses the boundary as a number.</remarks>
public enum Direction : byte
{
    North = 0,
    Right = 1,
    East = 2,
    Down = 3,
    South = 4,
    Left = 5,
    West = 6,
    Up = 7,
    Mask = 7,
    Running = 128,
    NONE = 237,
}

/// <remarks><c>TinyEcs.Bevy.UI.Display</c> — crosses the boundary as a number.</remarks>
public enum Display : byte
{
    Flex = 0,
    None = 1,
}

/// <summary><c>cuo:action/double-click</c></summary>
public partial struct DoubleClickAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/double-click";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:action/drop</c></summary>
public partial struct DropAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/drop";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
    [JsonPropertyName("Container")] public uint Container;
}

/// <summary><c>cuo:ui/editable-text</c></summary>
public partial struct EditableText
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/editable-text";

    [JsonPropertyName("Multiline")] public bool Multiline;
}

/// <summary><c>cuo:ent/name</c></summary>
public partial struct EntityName
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/name";

    [JsonPropertyName("Value")] public string Value;
}

/// <summary><c>cuo:ent/properties</c></summary>
public partial struct EntityPropertiesDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/properties";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Revision")] public uint Revision;
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Lines")] public OplLineDto[] Lines;
}

/// <summary><c>cuo:action/equip</c></summary>
public partial struct EquipAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/equip";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Layer")] public byte Layer;
    [JsonPropertyName("Container")] public uint Container;
}

/// <summary><c>cuo:ent/equipment</c></summary>
public partial struct EquipmentSlotsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/equipment";

    [JsonPropertyName("Serials")] public uint[] Serials;
}

/// <summary><c>cuo:ent/facing</c></summary>
public partial struct Facing
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/facing";

    /// <summary>enum Direction (0=North, 1=Right, 2=East, 3=Down, 4=South, 5=Left, 6=West, 7=Up, 7=Mask, 128=Running, 237=NONE)</summary>
    [JsonPropertyName("Value")] public Direction Value;
}

/// <remarks><c>ClassicUO.Game.Data.Flags</c> — crosses the boundary as a number.</remarks>
public enum Flags : byte
{
    None = 0,
    Frozen = 1,
    Female = 2,
    Poisoned = 4,
    Flying = 4,
    YellowBar = 8,
    IgnoreMobiles = 16,
    Movable = 32,
    WarMode = 64,
    Hidden = 128,
}

/// <remarks><c>TinyEcs.Bevy.UI.FlexDirection</c> — crosses the boundary as a number.</remarks>
public enum FlexDirection : byte
{
    Row = 0,
    Column = 1,
}

/// <summary><c>cuo:ui/focused-input</c></summary>
public sealed partial class FocusedInput
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/focused-input";

    [JsonPropertyName("Entity")] public ulong Entity;
}

/// <summary><c>cuo:game/context</c></summary>
public partial struct GameContextDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:game/context";

    [JsonPropertyName("PlayerSerial")] public uint PlayerSerial;
    [JsonPropertyName("PlayerName")] public string PlayerName;
    [JsonPropertyName("Map")] public int Map;
    [JsonPropertyName("Season")] public byte Season;
    [JsonPropertyName("ClientVersion")] public uint ClientVersion;
    [JsonPropertyName("UseOldStatusGump")] public bool UseOldStatusGump;
}

/// <summary><c>cuo:scene/game</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct GameScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/game";
}

/// <summary><c>cuo:game/state</c></summary>
public partial struct GameStateDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:game/state";

    [JsonPropertyName("Current")] public byte Current;
}

/// <summary><c>cuo:ui/global-z</c></summary>
public partial struct GlobalZIndex
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/global-z";

    [JsonPropertyName("Value")] public int Value;
}

/// <summary><c>cuo:player/grabbed-item</c></summary>
public sealed partial class GrabbedItem
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/grabbed-item";

    [JsonPropertyName("IsActive")] public bool IsActive;
    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Graphic")] public ushort Graphic;
    [JsonPropertyName("Hue")] public ushort Hue;
    [JsonPropertyName("Amount")] public int Amount;
    [JsonPropertyName("SourceUiEntity")] public ulong SourceUiEntity;
    [JsonPropertyName("OriginalGraphic")] public ushort OriginalGraphic;
    [JsonPropertyName("OriginalHue")] public ushort OriginalHue;
    [JsonPropertyName("OriginalAmount")] public ushort OriginalAmount;
    [JsonPropertyName("OriginalX")] public ushort OriginalX;
    [JsonPropertyName("OriginalY")] public ushort OriginalY;
    [JsonPropertyName("OriginalZ")] public sbyte OriginalZ;
    [JsonPropertyName("OriginalContainer")] public uint OriginalContainer;
    [JsonPropertyName("OriginalGridIndex")] public byte OriginalGridIndex;
    [JsonPropertyName("OriginalFromSlot")] public bool OriginalFromSlot;
    /// <summary>enum Layer (0=Invalid, 1=OneHanded, 2=TwoHanded, 3=Shoes, 4=Pants, 5=Shirt, 6=Helmet, 7=Gloves, 8=Ring, 9=Talisman, 10=Necklace, 11=Hair, 12=Waist, 13=Torso, 14=Bracelet, 15=Face, 16=Beard, 17=Tunic, 18=Earrings, 19=Arms, 20=Cloak, 21=Backpack, 22=Robe, 23=Skirt, 24=Legs, 25=Mount, 26=ShopBuyRestock, 27=ShopBuy, 28=ShopSell, 29=Bank)</summary>
    [JsonPropertyName("OriginalLayer")] public Layer OriginalLayer;
    [JsonPropertyName("PendingDrop")] public bool PendingDrop;
    [JsonPropertyName("DropTargetSerial")] public uint DropTargetSerial;
    [JsonPropertyName("FailedDrop")] public bool FailedDrop;
}

/// <summary><c>cuo:ent/graphic</c></summary>
public partial struct Graphic
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/graphic";

    [JsonPropertyName("Value")] public ushort Value;
}

/// <summary><c>cuo:gump/grid-container</c></summary>
public partial struct GridContainerWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/grid-container";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:gump/grid-loot</c></summary>
public partial struct GridLootWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/grid-loot";

    [JsonPropertyName("CorpseSerial")] public uint CorpseSerial;
    [JsonPropertyName("CorpseEntity")] public ulong CorpseEntity;
    [JsonPropertyName("ContentSig")] public int ContentSig;
}

/// <summary><c>cuo:action/gump-close</c></summary>
public partial struct GumpCloseAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/gump-close";

    [JsonPropertyName("GumpId")] public uint GumpId;
}

/// <summary><c>cuo:action/gump-reply</c></summary>
public partial struct GumpReplyAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/gump-reply";

    [JsonPropertyName("GumpId")] public uint GumpId;
    [JsonPropertyName("ButtonId")] public int ButtonId;
    [JsonPropertyName("Switches")] public uint[] Switches;
    [JsonPropertyName("TextEntries")] public GumpTextEntry[] TextEntries;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.GumpTextEntry</c>).</summary>
public partial struct GumpTextEntry
{
    [JsonPropertyName("Id")] public ushort Id;
    [JsonPropertyName("Text")] public string Text;
}

/// <summary><c>cuo:gump/health-bar</c></summary>
public partial struct HealthBarWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/health-bar";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("IsPlayer")] public bool IsPlayer;
    [JsonPropertyName("OutOfRange")] public bool OutOfRange;
    [JsonPropertyName("HpRequested")] public bool HpRequested;
    [JsonPropertyName("WasDead")] public bool WasDead;
    [JsonPropertyName("InParty")] public bool InParty;
    [JsonPropertyName("NameEditable")] public bool NameEditable;
}

/// <summary><c>cuo:player/hits</c></summary>
public partial struct Hits
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/hits";

    [JsonPropertyName("Value")] public ushort Value;
    [JsonPropertyName("MaxValue")] public ushort MaxValue;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.HostHotkeyDto</c>).</summary>
public partial struct HostHotkeyDto
{
    [JsonPropertyName("Key")] public int Key;
    [JsonPropertyName("Ctrl")] public bool Ctrl;
    [JsonPropertyName("Shift")] public bool Shift;
    [JsonPropertyName("Alt")] public bool Alt;
    [JsonPropertyName("Action")] public string Action;
}

/// <summary><c>cuo:input/host-hotkeys</c></summary>
public partial struct HostHotkeysDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/host-hotkeys";

    [JsonPropertyName("Hotkeys")] public HostHotkeyDto[] Hotkeys;
}

/// <summary><c>cuo:gump/house-design</c></summary>
public partial struct HouseDesignWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/house-design";

    [JsonPropertyName("Content")] public ulong Content;
    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:ent/hue</c></summary>
public partial struct Hue
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/hue";

    [JsonPropertyName("Value")] public ushort Value;
}

/// <summary><c>cuo:ui/interaction</c> — the payload IS this enum's number.</summary>
/// <remarks><c>TinyEcs.Bevy.UI.Interaction</c> — crosses the boundary as a number.</remarks>
public enum Interaction : byte
{
    None = 0,
    Hovered = 1,
    Pressed = 2,
}

/// <summary><c>cuo:ent/is-container</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct IsContainer
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/is-container";
}

/// <summary><c>cuo:ent/is-multi</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct IsMulti
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/is-multi";
}

/// <summary><c>cuo:ui/topbar-root</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct IsTopBar
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/topbar-root";
}

/// <summary><c>cuo:ent/is-item</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct Items
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/is-item";
}

/// <summary><c>cuo:gump/journal</c></summary>
public partial struct JournalWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/journal";

    [JsonPropertyName("SpecialHeight")] public int SpecialHeight;
    [JsonPropertyName("Minimized")] public bool Minimized;
    [JsonPropertyName("DarkMode")] public bool DarkMode;
    [JsonPropertyName("ShowSystem")] public bool ShowSystem;
    [JsonPropertyName("ShowObjects")] public bool ShowObjects;
    [JsonPropertyName("ShowClient")] public bool ShowClient;
    [JsonPropertyName("ShowGuild")] public bool ShowGuild;
    [JsonPropertyName("BuiltRevision")] public int BuiltRevision;
    [JsonPropertyName("StyleEpoch")] public int StyleEpoch;
    [JsonPropertyName("BuiltStyleEpoch")] public int BuiltStyleEpoch;
    [JsonPropertyName("ListEntity")] public ulong ListEntity;
    [JsonPropertyName("FlagEntity")] public ulong FlagEntity;
    [JsonPropertyName("TopEntity")] public ulong TopEntity;
    [JsonPropertyName("MidEntity")] public ulong MidEntity;
    [JsonPropertyName("BottomEntity")] public ulong BottomEntity;
    [JsonPropertyName("TitleEntity")] public ulong TitleEntity;
    [JsonPropertyName("MinimizeEntity")] public ulong MinimizeEntity;
    [JsonPropertyName("DarkCheckEntity")] public ulong DarkCheckEntity;
    [JsonPropertyName("ExpanderEntity")] public ulong ExpanderEntity;
    [JsonPropertyName("Width")] public float Width;
    [JsonPropertyName("ListWidth")] public float ListWidth;
    [JsonPropertyName("ContentHeight")] public float ContentHeight;
}

/// <remarks><c>TinyEcs.Bevy.UI.JustifyContent</c> — crosses the boundary as a number.</remarks>
public enum JustifyContent : byte
{
    Start = 0,
    Center = 1,
    End = 2,
}

/// <summary><c>cuo:input/keyboard</c></summary>
public partial struct KeyboardInputDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/keyboard";

    [JsonPropertyName("Pressed")] public int[] Pressed;
}

/// <remarks><c>ClassicUO.Game.Data.Layer</c> — crosses the boundary as a number.</remarks>
public enum Layer : byte
{
    Invalid = 0,
    OneHanded = 1,
    TwoHanded = 2,
    Shoes = 3,
    Pants = 4,
    Shirt = 5,
    Helmet = 6,
    Gloves = 7,
    Ring = 8,
    Talisman = 9,
    Necklace = 10,
    Hair = 11,
    Waist = 12,
    Torso = 13,
    Bracelet = 14,
    Face = 15,
    Beard = 16,
    Tunic = 17,
    Earrings = 18,
    Arms = 19,
    Cloak = 20,
    Backpack = 21,
    Robe = 22,
    Skirt = 23,
    Legs = 24,
    Mount = 25,
    ShopBuyRestock = 26,
    ShopBuy = 27,
    ShopSell = 28,
    Bank = 29,
}

/// <summary><c>cuo:target/local-result</c></summary>
public partial struct LocalTargetResultEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:target/local-result";

    [JsonPropertyName("Entity")] public ulong Entity;
    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Graphic")] public ushort Graphic;
    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
    [JsonPropertyName("Cancelled")] public bool Cancelled;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.LoginErrorInfo</c>).</summary>
public partial struct LoginErrorInfo
{
    [JsonPropertyName("ErrorMessage")] public string ErrorMessage;
}

/// <summary><c>cuo:scene/login-error</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct LoginErrorScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/login-error";
}

/// <summary><c>cuo:scene/login-error-info</c></summary>
public partial struct LoginErrorsInfoEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/login-error-info";

    [JsonPropertyName("Error")] public LoginErrorInfo Error;
}

/// <summary><c>cuo:scene/login</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct LoginScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/login";
}

/// <summary><c>cuo:gump/logout</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct LogoutGumpWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/logout";
}

/// <summary><c>cuo:player/mana</c></summary>
public partial struct Mana
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/mana";

    [JsonPropertyName("Value")] public ushort Value;
    [JsonPropertyName("MaxValue")] public ushort MaxValue;
}

/// <summary><c>cuo:gump/map</c>
/// <para>Presence-only marker: the host always answers <c>{}</c> and ignores writes.</para>
/// </summary>
public partial struct MapWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/map";
}

/// <summary><c>cuo:ui/masked-text</c></summary>
public partial struct MaskedText
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/masked-text";

    [JsonPropertyName("Value")] public string Value;
    [JsonPropertyName("MaskChar")] public char MaskChar;
}

/// <summary><c>cuo:gump/menu</c></summary>
public partial struct MenuGumpWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/menu";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("ServerMenuId")] public ushort ServerMenuId;
    [JsonPropertyName("IsGray")] public bool IsGray;
    [JsonPropertyName("Responded")] public bool Responded;
}

/// <summary><c>cuo:gump/message-box</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct MessageBoxWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/message-box";
}

/// <summary><c>cuo:gump/minimap</c></summary>
public partial struct MiniMapWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/minimap";

    [JsonPropertyName("UseLargeMap")] public bool UseLargeMap;
}

/// <summary><c>cuo:ent/animation</c></summary>
public partial struct MobAnimation
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/animation";

    [JsonPropertyName("Index")] public int Index;
    [JsonPropertyName("FramesCount")] public int FramesCount;
    [JsonPropertyName("Interval")] public int Interval;
    [JsonPropertyName("RepeatMode")] public int RepeatMode;
    [JsonPropertyName("RepeatModeCount")] public int RepeatModeCount;
    [JsonPropertyName("Repeat")] public bool Repeat;
    [JsonPropertyName("IsFromServer")] public bool IsFromServer;
    [JsonPropertyName("ForwardDirection")] public bool ForwardDirection;
    [JsonPropertyName("Action")] public byte Action;
    [JsonPropertyName("MountAction")] public byte MountAction;
    /// <summary>enum Direction (0=North, 1=Right, 2=East, 3=Down, 4=South, 5=Left, 6=West, 7=Up, 7=Mask, 128=Running, 237=NONE)</summary>
    [JsonPropertyName("Direction")] public Direction Direction;
    [JsonPropertyName("Time")] public float Time;
    [JsonPropertyName("Run")] public bool Run;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.MobStepDto</c>).</summary>
public partial struct MobStepDto
{
    [JsonPropertyName("X")] public int X;
    [JsonPropertyName("Y")] public int Y;
    [JsonPropertyName("Z")] public sbyte Z;
    [JsonPropertyName("Direction")] public byte Direction;
    [JsonPropertyName("Run")] public bool Run;
}

/// <summary><c>cuo:ent/mob-steps</c></summary>
public partial struct MobileStepsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/mob-steps";

    [JsonPropertyName("Index")] public int Index;
    [JsonPropertyName("Time")] public float Time;
    [JsonPropertyName("Steps")] public MobStepDto[] Steps;
}

/// <summary><c>cuo:ent/is-mobile</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct Mobiles
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/is-mobile";
}

/// <summary><c>cuo:chat/message</c></summary>
public partial struct ModChatMessage
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:chat/message";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Text")] public string Text;
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Hue")] public ushort Hue;
    [JsonPropertyName("Font")] public byte Font;
    [JsonPropertyName("IsUnicode")] public bool IsUnicode;
    [JsonPropertyName("MessageType")] public byte MessageType;
    [JsonPropertyName("Time")] public float Time;
    [JsonPropertyName("Kind")] public byte Kind;
}

/// <summary><c>cuo:ui/clicked</c></summary>
public partial struct ModClicked
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/clicked";

    [JsonPropertyName("Tick")] public byte Tick;
}

/// <summary><c>cuo:test/counter</c></summary>
public partial struct ModCounter
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:test/counter";

    [JsonPropertyName("Value")] public int Value;
}

/// <summary><c>cuo:mod/owned</c>
/// <para>Presence-only marker: the host always answers <c>{}</c> and ignores writes.</para>
/// </summary>
public partial struct ModEntity
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:mod/owned";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.ModHotkeyBinding</c>).</summary>
public sealed partial class ModHotkeyBinding
{
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Key")] public int Key;
    [JsonPropertyName("Mouse")] public int Mouse;
    [JsonPropertyName("Ctrl")] public bool Ctrl;
    [JsonPropertyName("Shift")] public bool Shift;
    [JsonPropertyName("Alt")] public bool Alt;
    [JsonPropertyName("Consume")] public bool Consume;
}

/// <summary><c>cuo:input/mod-hotkeys</c></summary>
public partial struct ModHotkeyBindingsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/mod-hotkeys";

    [JsonPropertyName("Bindings")] public ModHotkeyBinding[] Bindings;
    [JsonPropertyName("ConsumeKeys")] public bool ConsumeKeys;
}

/// <summary><c>cuo:input/hotkey</c></summary>
public partial struct ModHotkeyFired
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/hotkey";

    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Key")] public int Key;
    [JsonPropertyName("Mouse")] public int Mouse;
    [JsonPropertyName("Ctrl")] public bool Ctrl;
    [JsonPropertyName("Shift")] public bool Shift;
    [JsonPropertyName("Alt")] public bool Alt;
    [JsonPropertyName("FromMod")] public bool FromMod;
}

/// <summary><c>cuo:ui/hovered</c></summary>
public partial struct ModHovered
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/hovered";

    [JsonPropertyName("Tick")] public byte Tick;
}

/// <summary><c>cuo:player/move-request</c></summary>
public partial struct ModMoveRequest
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/move-request";

    [JsonPropertyName("Direction")] public byte Direction;
    [JsonPropertyName("Run")] public bool Run;
    [JsonPropertyName("Sequence")] public byte Sequence;
}

/// <summary><c>cuo:ui/right-clicked</c></summary>
public partial struct ModRightClicked
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/right-clicked";

    [JsonPropertyName("Tick")] public byte Tick;
    [JsonPropertyName("X")] public float X;
    [JsonPropertyName("Y")] public float Y;
}

/// <summary><c>cuo:mod/state</c></summary>
public partial struct ModState
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:mod/state";

    [JsonPropertyName("Json")] public string Json;
}

/// <summary><c>cuo:input/mouse</c></summary>
public partial struct MouseInputDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/mouse";

    [JsonPropertyName("X")] public float X;
    [JsonPropertyName("Y")] public float Y;
    [JsonPropertyName("Left")] public bool Left;
    [JsonPropertyName("Right")] public bool Right;
    [JsonPropertyName("Middle")] public bool Middle;
    [JsonPropertyName("X1")] public bool X1;
    [JsonPropertyName("X2")] public bool X2;
    [JsonPropertyName("Wheel")] public float Wheel;
}

/// <summary><c>cuo:ent/serial</c></summary>
public partial struct NetworkSerial
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/serial";

    [JsonPropertyName("Value")] public uint Value;
}

/// <summary><c>cuo:ui/node</c></summary>
public partial struct Node
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/node";

    /// <summary>enum Display (0=Flex, 1=None)</summary>
    [JsonPropertyName("Display")] public Display Display;
    /// <summary>enum PositionType (0=Relative, 1=Absolute)</summary>
    [JsonPropertyName("PositionType")] public PositionType PositionType;
    /// <summary>enum Overflow (0=Visible, 1=Clip, 2=Scroll)</summary>
    [JsonPropertyName("Overflow")] public Overflow Overflow;
    /// <summary>enum FlexDirection (0=Row, 1=Column)</summary>
    [JsonPropertyName("FlexDirection")] public FlexDirection FlexDirection;
    /// <summary>enum JustifyContent (0=Start, 1=Center, 2=End)</summary>
    [JsonPropertyName("JustifyContent")] public JustifyContent JustifyContent;
    /// <summary>enum AlignItems (0=Start, 1=Center, 2=End)</summary>
    [JsonPropertyName("AlignItems")] public AlignItems AlignItems;
    [JsonPropertyName("Width")] public Val Width;
    [JsonPropertyName("Height")] public Val Height;
    [JsonPropertyName("MinWidth")] public Val MinWidth;
    [JsonPropertyName("MinHeight")] public Val MinHeight;
    [JsonPropertyName("MaxWidth")] public Val MaxWidth;
    [JsonPropertyName("MaxHeight")] public Val MaxHeight;
    [JsonPropertyName("Left")] public Val Left;
    [JsonPropertyName("Top")] public Val Top;
    [JsonPropertyName("Right")] public Val Right;
    [JsonPropertyName("Bottom")] public Val Bottom;
    [JsonPropertyName("Padding")] public UiRect Padding;
    [JsonPropertyName("Border")] public UiRect Border;
    [JsonPropertyName("Gap")] public Val Gap;
    [JsonPropertyName("AspectRatio")] public float AspectRatio;
}

/// <summary><c>cuo:ent/notoriety</c></summary>
public partial struct Notoriety
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/notoriety";

    /// <summary>enum NotorietyFlag (0=Unknown, 1=Innocent, 2=Ally, 3=Gray, 4=Criminal, 5=Enemy, 6=Murderer, 7=Invulnerable)</summary>
    [JsonPropertyName("Value")] public NotorietyFlag Value;
}

/// <remarks><c>ClassicUO.Game.Data.NotorietyFlag</c> — crosses the boundary as a number.</remarks>
public enum NotorietyFlag : byte
{
    Unknown = 0,
    Innocent = 1,
    Ally = 2,
    Gray = 3,
    Criminal = 4,
    Enemy = 5,
    Murderer = 6,
    Invulnerable = 7,
}

/// <summary><c>cuo:scene/login-request</c></summary>
public partial struct OnLoginRequest
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/login-request";

    [JsonPropertyName("Username")] public string Username;
    [JsonPropertyName("Password")] public string Password;
    [JsonPropertyName("Address")] public string Address;
    [JsonPropertyName("Port")] public ushort Port;
}

/// <summary><c>cuo:action/open-door</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct OpenDoorAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/open-door";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.OplLineDto</c>).</summary>
public partial struct OplLineDto
{
    [JsonPropertyName("Cliloc")] public int Cliloc;
    [JsonPropertyName("Args")] public string Args;
    [JsonPropertyName("Text")] public string Text;
}

/// <summary><c>cuo:ui/options-window</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct OptionsWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/options-window";
}

/// <remarks><c>TinyEcs.Bevy.UI.Overflow</c> — crosses the boundary as a number.</remarks>
public enum Overflow : byte
{
    Visible = 0,
    Clip = 1,
    Scroll = 2,
}

/// <summary><c>cuo:gump/paperdoll</c></summary>
public partial struct PaperdollWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/paperdoll";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("IsPlayer")] public bool IsPlayer;
    [JsonPropertyName("CanLift")] public bool CanLift;
}

/// <summary><c>cuo:player/party</c></summary>
public partial struct PartyDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/party";

    [JsonPropertyName("Leader")] public uint Leader;
    [JsonPropertyName("Members")] public PartyMemberDto[] Members;
    [JsonPropertyName("InParty")] public bool InParty;
    [JsonPropertyName("CanLoot")] public bool CanLoot;
}

/// <summary><c>cuo:gump/party-invite</c></summary>
public partial struct PartyInviteWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/party-invite";

    [JsonPropertyName("Inviter")] public uint Inviter;
}

/// <summary><c>cuo:gump/party-manifest</c></summary>
public partial struct PartyManifestWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/party-manifest";

    [JsonPropertyName("CanLoot")] public bool CanLoot;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.PartyMemberDto</c>).</summary>
public partial struct PartyMemberDto
{
    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Name")] public string Name;
}

/// <summary><c>cuo:action/pickup</c></summary>
public partial struct PickupAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/pickup";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Amount")] public ushort Amount;
}

/// <summary><c>cuo:player/player</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct Player
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/player";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.PlayerBuffDto</c>).</summary>
public partial struct PlayerBuffDto
{
    [JsonPropertyName("Type")] public int Type;
    [JsonPropertyName("Graphic")] public ushort Graphic;
    [JsonPropertyName("ExpiresAt")] public float ExpiresAt;
    [JsonPropertyName("Text")] public string Text;
}

/// <summary><c>cuo:player/buffs</c></summary>
public partial struct PlayerBuffsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/buffs";

    [JsonPropertyName("Buffs")] public PlayerBuffDto[] Buffs;
}

/// <summary><c>cuo:player/data</c></summary>
public partial struct PlayerData
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/data";

    [JsonPropertyName("Str")] public ushort Str;
    [JsonPropertyName("StrMax")] public ushort StrMax;
    [JsonPropertyName("Dex")] public ushort Dex;
    [JsonPropertyName("DexMax")] public ushort DexMax;
    [JsonPropertyName("Int")] public ushort Int;
    [JsonPropertyName("IntMax")] public ushort IntMax;
    [JsonPropertyName("StatsCap")] public short StatsCap;
    [JsonPropertyName("Followers")] public byte Followers;
    [JsonPropertyName("FollowersMax")] public byte FollowersMax;
    [JsonPropertyName("Weight")] public ushort Weight;
    [JsonPropertyName("WeightMax")] public ushort WeightMax;
    [JsonPropertyName("Gold")] public uint Gold;
    [JsonPropertyName("ThithingPoints")] public uint ThithingPoints;
    [JsonPropertyName("Luck")] public ushort Luck;
    [JsonPropertyName("DamageMin")] public short DamageMin;
    [JsonPropertyName("DamageMax")] public short DamageMax;
    [JsonPropertyName("PhysicalRes")] public short PhysicalRes;
    [JsonPropertyName("FireRes")] public short FireRes;
    [JsonPropertyName("ColdRes")] public short ColdRes;
    [JsonPropertyName("PoisonRes")] public short PoisonRes;
    [JsonPropertyName("EnergyRes")] public short EnergyRes;
    [JsonPropertyName("IsFemale")] public bool IsFemale;
    /// <summary>enum RaceType (1=HUMAN, 2=ELF, 3=GARGOYLE)</summary>
    [JsonPropertyName("Race")] public RaceType Race;
    [JsonPropertyName("MaxPhysicalRes")] public short MaxPhysicalRes;
    [JsonPropertyName("MaxFireRes")] public short MaxFireRes;
    [JsonPropertyName("MaxColdRes")] public short MaxColdRes;
    [JsonPropertyName("MaxPoisonRes")] public short MaxPoisonRes;
    [JsonPropertyName("MaxEnergyRes")] public short MaxEnergyRes;
    [JsonPropertyName("DefenseChanceInc")] public short DefenseChanceInc;
    [JsonPropertyName("MaxDefenseChanceInc")] public short MaxDefenseChanceInc;
    [JsonPropertyName("HitChanceInc")] public short HitChanceInc;
    [JsonPropertyName("SwingSpeedInc")] public short SwingSpeedInc;
    [JsonPropertyName("DamageInc")] public short DamageInc;
    [JsonPropertyName("LowerReagentCost")] public short LowerReagentCost;
    [JsonPropertyName("SpellDamageInc")] public short SpellDamageInc;
    [JsonPropertyName("FasterCastRecovery")] public short FasterCastRecovery;
    [JsonPropertyName("FasterCasting")] public short FasterCasting;
    [JsonPropertyName("LowerManaCost")] public short LowerManaCost;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.PlayerSkillDto</c>).</summary>
public partial struct PlayerSkillDto
{
    [JsonPropertyName("Index")] public int Index;
    [JsonPropertyName("Value")] public ushort Value;
    [JsonPropertyName("Base")] public ushort Base;
    [JsonPropertyName("Cap")] public ushort Cap;
    [JsonPropertyName("Lock")] public byte Lock;
}

/// <summary><c>cuo:player/skills</c></summary>
public partial struct PlayerSkillsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/skills";

    [JsonPropertyName("HasData")] public bool HasData;
    [JsonPropertyName("Skills")] public PlayerSkillDto[] Skills;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.PlayerStepDto</c>).</summary>
public partial struct PlayerStepDto
{
    [JsonPropertyName("Sequence")] public byte Sequence;
    [JsonPropertyName("Direction")] public byte Direction;
    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
}

/// <summary><c>cuo:player/steps</c></summary>
public partial struct PlayerStepsDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/steps";

    [JsonPropertyName("LastStep")] public float LastStep;
    [JsonPropertyName("Count")] public int Count;
    [JsonPropertyName("Sequence")] public byte Sequence;
    [JsonPropertyName("ResyncSent")] public bool ResyncSent;
    [JsonPropertyName("Steps")] public PlayerStepDto[] Steps;
}

/// <remarks><c>TinyEcs.Bevy.UI.PositionType</c> — crosses the boundary as a number.</remarks>
public enum PositionType : byte
{
    Relative = 0,
    Absolute = 1,
}

/// <summary><c>cuo:gump/profile</c></summary>
public partial struct ProfileWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/profile";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("SpecialHeight")] public int SpecialHeight;
    [JsonPropertyName("Width")] public float Width;
    [JsonPropertyName("MidEntity")] public ulong MidEntity;
    [JsonPropertyName("BottomEntity")] public ulong BottomEntity;
    [JsonPropertyName("ExpanderEntity")] public ulong ExpanderEntity;
    [JsonPropertyName("FooterEntity")] public ulong FooterEntity;
    [JsonPropertyName("FooterOffsetFromBottom")] public int FooterOffsetFromBottom;
}

/// <summary><c>cuo:chat/prompt</c></summary>
public partial struct PromptOpenedEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:chat/prompt";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("PromptId")] public uint PromptId;
    [JsonPropertyName("Unicode")] public bool Unicode;
    [JsonPropertyName("Text")] public string Text;
}

/// <summary><c>cuo:action/prompt-reply</c></summary>
public partial struct PromptReplyAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/prompt-reply";

    [JsonPropertyName("Text")] public string Text;
    [JsonPropertyName("Cancel")] public bool Cancel;
}

/// <remarks><c>ClassicUO.Game.Data.RaceType</c> — crosses the boundary as a number.</remarks>
public enum RaceType : byte
{
    HUMAN = 1,
    ELF = 2,
    GARGOYLE = 3,
}

/// <summary><c>cuo:gump/racial-book</c></summary>
public partial struct RacialBookWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/racial-book";

    [JsonPropertyName("Page")] public int Page;
    [JsonPropertyName("SoundedPage")] public int SoundedPage;
    [JsonPropertyName("PageCount")] public int PageCount;
    [JsonPropertyName("DictPages")] public int DictPages;
    [JsonPropertyName("AbilityCount")] public int AbilityCount;
    /// <summary>enum RaceType (1=HUMAN, 2=ELF, 3=GARGOYLE)</summary>
    [JsonPropertyName("Race")] public RaceType Race;
    [JsonPropertyName("Dirty")] public bool Dirty;
    [JsonPropertyName("Content")] public ulong Content;
    [JsonPropertyName("Left")] public ulong Left;
    [JsonPropertyName("Right")] public ulong Right;
}

/// <summary><c>cuo:action/rename</c></summary>
public partial struct RenameAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/rename";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Name")] public string Name;
}

/// <summary><c>cuo:action/request-context-menu</c></summary>
public partial struct RequestContextMenuAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/request-context-menu";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:action/request-properties</c></summary>
public partial struct RequestPropertiesAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/request-properties";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:action/request-skills</c></summary>
public partial struct RequestSkillsAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/request-skills";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:action/request-status</c></summary>
public partial struct RequestStatusAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/request-status";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:action/request-target</c></summary>
public partial struct RequestTargetAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/request-target";

    [JsonPropertyName("PromptText")] public string PromptText;
}

/// <summary><c>cuo:action/say</c></summary>
public partial struct SayAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/say";

    [JsonPropertyName("Text")] public string Text;
    [JsonPropertyName("Hue")] public ushort Hue;
}

/// <summary><c>cuo:ui/scroll</c></summary>
public partial struct ScrollPosition
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/scroll";

    [JsonPropertyName("OffsetX")] public float OffsetX;
    [JsonPropertyName("OffsetY")] public float OffsetY;
}

/// <remarks><c>ClassicUO.Ecs.ScrollbarStyle</c> — crosses the boundary as a number.</remarks>
public enum ScrollbarStyle : byte
{
    Uo = 0,
    Flat = 1,
}

/// <summary><c>cuo:ent/server-flags</c></summary>
public partial struct ServerFlags
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/server-flags";

    /// <summary>enum Flags (0=None, 1=Frozen, 2=Female, 4=Poisoned, 4=Flying, 8=YellowBar, 16=IgnoreMobiles, 32=Movable, 64=WarMode, 128=Hidden)</summary>
    [JsonPropertyName("Value")] public Flags Value;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.ServerGumpButtonDto</c>).</summary>
public partial struct ServerGumpButtonDto
{
    [JsonPropertyName("Id")] public int Id;
    [JsonPropertyName("X")] public float X;
    [JsonPropertyName("Y")] public float Y;
    [JsonPropertyName("W")] public float W;
    [JsonPropertyName("H")] public float H;
}

/// <summary><c>cuo:gump/server-closed</c></summary>
public partial struct ServerGumpClosedEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/server-closed";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("GumpId")] public uint GumpId;
}

/// <summary><c>cuo:gump/server</c></summary>
public partial struct ServerGumpDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/server";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("GumpId")] public uint GumpId;
    [JsonPropertyName("Page")] public int Page;
    [JsonPropertyName("X")] public int X;
    [JsonPropertyName("Y")] public int Y;
    [JsonPropertyName("Layout")] public string[] Layout;
    [JsonPropertyName("Texts")] public string[] Texts;
    [JsonPropertyName("Buttons")] public ServerGumpButtonDto[] Buttons;
    [JsonPropertyName("TextEntries")] public ServerGumpTextEntryDto[] TextEntries;
    [JsonPropertyName("Switches")] public ServerGumpSwitchDto[] Switches;
}

/// <summary><c>cuo:gump/server-opened</c></summary>
public partial struct ServerGumpOpenedEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/server-opened";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("GumpId")] public uint GumpId;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.ServerGumpSwitchDto</c>).</summary>
public partial struct ServerGumpSwitchDto
{
    [JsonPropertyName("Id")] public uint Id;
    [JsonPropertyName("Checked")] public bool Checked;
    [JsonPropertyName("IsRadio")] public bool IsRadio;
    [JsonPropertyName("Group")] public int Group;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.ServerGumpTextEntryDto</c>).</summary>
public partial struct ServerGumpTextEntryDto
{
    [JsonPropertyName("Id")] public ushort Id;
    [JsonPropertyName("Text")] public string Text;
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.ServerInfo</c>).</summary>
public partial struct ServerInfo
{
    [JsonPropertyName("Index")] public int Index;
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("PercentFull")] public byte PercentFull;
    [JsonPropertyName("TimeZone")] public byte TimeZone;
    [JsonPropertyName("Ip")] public uint Ip;
}

/// <summary><c>cuo:scene/server-list</c></summary>
public partial struct ServerSelectionInfoEvent
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/server-list";

    [JsonPropertyName("Servers")] public ServerInfo[] Servers;
}

/// <summary><c>cuo:scene/server-selection</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct ServerSelectionScene
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:scene/server-selection";
}

/// <summary><c>cuo:action/single-click</c></summary>
public partial struct SingleClickAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/single-click";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:gump/skills</c></summary>
public partial struct SkillsWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/skills";

    [JsonPropertyName("SpecialHeight")] public int SpecialHeight;
    [JsonPropertyName("Minimized")] public bool Minimized;
    [JsonPropertyName("ShowReal")] public bool ShowReal;
    [JsonPropertyName("ShowCaps")] public bool ShowCaps;
    [JsonPropertyName("Dirty")] public bool Dirty;
    [JsonPropertyName("Width")] public int Width;
    [JsonPropertyName("ListWidth")] public float ListWidth;
    [JsonPropertyName("ContentHeight")] public float ContentHeight;
    [JsonPropertyName("ListEntity")] public ulong ListEntity;
    [JsonPropertyName("TopEntity")] public ulong TopEntity;
    [JsonPropertyName("MidEntity")] public ulong MidEntity;
    [JsonPropertyName("BottomEntity")] public ulong BottomEntity;
    [JsonPropertyName("TitleEntity")] public ulong TitleEntity;
    [JsonPropertyName("MinimizeEntity")] public ulong MinimizeEntity;
    [JsonPropertyName("ExpanderEntity")] public ulong ExpanderEntity;
    [JsonPropertyName("SumLabelEntity")] public ulong SumLabelEntity;
    [JsonPropertyName("FlagEntity")] public ulong FlagEntity;
    [JsonPropertyName("LastSum")] public float LastSum;
}

/// <remarks><c>ClassicUO.Ecs.SpellBookType</c> — crosses the boundary as a number.</remarks>
public enum SpellBookType : int
{
    Magery = 0,
    Necromancy = 1,
    Chivalry = 2,
    Bushido = 4,
    Ninjitsu = 5,
    Spellweaving = 6,
    Mysticism = 7,
    Mastery = 8,
    Unknown = 255,
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.SpellbookDto</c>).</summary>
public partial struct SpellbookDto
{
    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("BookType")] public byte BookType;
    [JsonPropertyName("Spells")] public int[] Spells;
}

/// <summary><c>cuo:gump/spellbook</c></summary>
public partial struct SpellbookWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/spellbook";

    [JsonPropertyName("Serial")] public uint Serial;
    /// <summary>enum SpellBookType (0=Magery, 1=Necromancy, 2=Chivalry, 4=Bushido, 5=Ninjitsu, 6=Spellweaving, 7=Mysticism, 8=Mastery, 255=Unknown)</summary>
    [JsonPropertyName("School")] public SpellBookType School;
    [JsonPropertyName("Page")] public int Page;
    [JsonPropertyName("SoundedPage")] public int SoundedPage;
    [JsonPropertyName("PageCount")] public int PageCount;
    [JsonPropertyName("BuiltRevision")] public int BuiltRevision;
    [JsonPropertyName("Dirty")] public bool Dirty;
    [JsonPropertyName("ContentEntity")] public ulong ContentEntity;
    [JsonPropertyName("LeftCorner")] public ulong LeftCorner;
    [JsonPropertyName("RightCorner")] public ulong RightCorner;
}

/// <summary><c>cuo:player/spellbook</c></summary>
public partial struct SpellbooksDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/spellbook";

    [JsonPropertyName("Revision")] public int Revision;
    [JsonPropertyName("Books")] public SpellbookDto[] Books;
}

/// <summary><c>cuo:gump/split-menu</c></summary>
public partial struct SplitMenuWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/split-menu";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("MaxAmount")] public int MaxAmount;
    [JsonPropertyName("Slider")] public ulong Slider;
    [JsonPropertyName("Text")] public ulong Text;
    [JsonPropertyName("Ok")] public ulong Ok;
    [JsonPropertyName("LastSlider")] public int LastSlider;
    [JsonPropertyName("LastText")] public string LastText;
    [JsonPropertyName("Graphic")] public ushort Graphic;
    [JsonPropertyName("Hue")] public ushort Hue;
    [JsonPropertyName("SourceUiEntity")] public ulong SourceUiEntity;
    [JsonPropertyName("SourceContainer")] public uint SourceContainer;
    [JsonPropertyName("OriginalGraphic")] public ushort OriginalGraphic;
    [JsonPropertyName("OriginalHue")] public ushort OriginalHue;
    [JsonPropertyName("OriginalAmount")] public ushort OriginalAmount;
    [JsonPropertyName("OriginalX")] public ushort OriginalX;
    [JsonPropertyName("OriginalY")] public ushort OriginalY;
    [JsonPropertyName("OriginalZ")] public sbyte OriginalZ;
    [JsonPropertyName("OriginalContainer")] public uint OriginalContainer;
    [JsonPropertyName("OriginalGridIndex")] public byte OriginalGridIndex;
    [JsonPropertyName("OriginalFromSlot")] public bool OriginalFromSlot;
}

/// <summary><c>cuo:player/stamina</c></summary>
public partial struct Stamina
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/stamina";

    [JsonPropertyName("Value")] public ushort Value;
    [JsonPropertyName("MaxValue")] public ushort MaxValue;
}

/// <summary><c>cuo:ui/stat-lock-button</c></summary>
public partial struct StatLockButton
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/stat-lock-button";

    [JsonPropertyName("Stat")] public byte Stat;
}

/// <summary><c>cuo:player/stat-locks</c></summary>
public partial struct StatLocks
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:player/stat-locks";

    [JsonPropertyName("Str")] public byte Str;
    [JsonPropertyName("Dex")] public byte Dex;
    [JsonPropertyName("Int")] public byte Int;
}

/// <summary><c>cuo:ui/statusbar-window</c></summary>
public partial struct StatusBarWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/statusbar-window";

    [JsonPropertyName("MinimizeX")] public float MinimizeX;
    [JsonPropertyName("MinimizeY")] public float MinimizeY;
}

/// <summary><c>cuo:action/target-cancel</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct TargetCancelAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/target-cancel";
}

/// <summary><c>cuo:action/target-location</c></summary>
public partial struct TargetLocationAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/target-location";

    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
    [JsonPropertyName("Graphic")] public ushort Graphic;
}

/// <summary><c>cuo:action/target-object</c></summary>
public partial struct TargetObjectAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/target-object";

    [JsonPropertyName("Serial")] public uint Serial;
}

/// <summary><c>cuo:target/state</c></summary>
public sealed partial class TargetingState
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:target/state";

    [JsonPropertyName("IsTargeting")] public bool IsTargeting;
    [JsonPropertyName("Mode")] public byte Mode;
    [JsonPropertyName("Local")] public bool Local;
    [JsonPropertyName("CursorId")] public uint CursorId;
    [JsonPropertyName("CursorType")] public byte CursorType;
    [JsonPropertyName("JustTargeted")] public bool JustTargeted;
    [JsonPropertyName("MultiId")] public ushort MultiId;
    [JsonPropertyName("MultiOffsetX")] public short MultiOffsetX;
    [JsonPropertyName("MultiOffsetY")] public short MultiOffsetY;
    [JsonPropertyName("MultiOffsetZ")] public short MultiOffsetZ;
    [JsonPropertyName("MultiHue")] public ushort MultiHue;
    [JsonPropertyName("PreviewBuiltId")] public ushort PreviewBuiltId;
    [JsonPropertyName("HasLocalResult")] public bool HasLocalResult;
    [JsonPropertyName("LocalSerial")] public uint LocalSerial;
    [JsonPropertyName("LocalGraphic")] public ushort LocalGraphic;
    [JsonPropertyName("LocalX")] public ushort LocalX;
    [JsonPropertyName("LocalY")] public ushort LocalY;
    [JsonPropertyName("LocalZ")] public sbyte LocalZ;
    [JsonPropertyName("LocalCancelled")] public bool LocalCancelled;
}

/// <summary><c>cuo:ui/text</c></summary>
public partial struct Text
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text";

    [JsonPropertyName("Value")] public string Value;
}

/// <summary><c>cuo:ui/text-caret</c></summary>
public partial struct TextCaretDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-caret";

    [JsonPropertyName("Entity")] public ulong Entity;
    [JsonPropertyName("Cursor")] public int Cursor;
    [JsonPropertyName("SelectStart")] public int SelectStart;
    [JsonPropertyName("SelectEnd")] public int SelectEnd;
    [JsonPropertyName("Line")] public int Line;
    [JsonPropertyName("Column")] public int Column;
    [JsonPropertyName("ScreenX")] public float ScreenX;
    [JsonPropertyName("ScreenY")] public float ScreenY;
    [JsonPropertyName("RowHeight")] public float RowHeight;
}

/// <summary><c>cuo:ui/text-clipboard-action</c></summary>
public sealed partial class TextClipboardActionDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-clipboard-action";

    [JsonPropertyName("Entity")] public ulong Entity;
    [JsonPropertyName("Action")] public int Action;
    [JsonPropertyName("Seq")] public int Seq;
}

/// <summary><c>cuo:ui/text-color</c></summary>
public partial struct TextColor
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-color";

    [JsonPropertyName("Value")] public Color Value;
}

/// <summary><c>cuo:ui/text-completion</c></summary>
public sealed partial class TextCompletionDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-completion";

    [JsonPropertyName("Entity")] public ulong Entity;
    [JsonPropertyName("Prefix")] public string Prefix;
    [JsonPropertyName("Items")] public string[] Items;
}

/// <summary><c>cuo:ui/text-completion-pick</c></summary>
public sealed partial class TextCompletionPickDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-completion-pick";

    [JsonPropertyName("Entity")] public ulong Entity;
    [JsonPropertyName("Index")] public int Index;
    [JsonPropertyName("Seq")] public int Seq;
}

/// <summary><c>cuo:ui/text-completion-state</c></summary>
public partial struct TextCompletionStateDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-completion-state";

    [JsonPropertyName("Selected")] public int Selected;
}

/// <summary><c>cuo:ui/text-font</c></summary>
public partial struct TextFont
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-font";

    [JsonPropertyName("FontId")] public ushort FontId;
    [JsonPropertyName("Size")] public ushort Size;
}

/// <summary><c>cuo:ui/text-hue</c></summary>
public partial struct TextHue
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-hue";

    [JsonPropertyName("Value")] public ushort Value;
}

/// <summary><c>cuo:ui/text-input</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct TextInput
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-input";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.TextSpan</c>).</summary>
public partial struct TextSpan
{
    [JsonPropertyName("Start")] public int Start;
    [JsonPropertyName("Length")] public int Length;
    [JsonPropertyName("Color")] public Color Color;
}

/// <summary><c>cuo:ui/text-spans</c></summary>
public partial struct TextSpans
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-spans";

    [JsonPropertyName("Spans")] public TextSpan[] Spans;
}

/// <summary><c>cuo:ui/text-wrap</c></summary>
public partial struct TextWrap
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/text-wrap";

    /// <summary>enum TextWrapKind (0=Words, 1=Newlines, 2=None)</summary>
    [JsonPropertyName("Kind")] public TextWrapKind Kind;
}

/// <remarks><c>TinyEcs.Bevy.UI.TextWrapKind</c> — crosses the boundary as a number.</remarks>
public enum TextWrapKind : byte
{
    Words = 0,
    Newlines = 1,
    None = 2,
}

/// <summary><c>cuo:engine/time</c></summary>
public sealed partial class Time
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:engine/time";

    [JsonPropertyName("Total")] public float Total;
    [JsonPropertyName("Frame")] public float Frame;
}

/// <summary><c>cuo:gump/tip-notice</c></summary>
public partial struct TipNoticeWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/tip-notice";

    [JsonPropertyName("TipSerial")] public ushort TipSerial;
    [JsonPropertyName("SpecialHeight")] public int SpecialHeight;
    [JsonPropertyName("Width")] public float Width;
    [JsonPropertyName("MidEntity")] public ulong MidEntity;
    [JsonPropertyName("BottomEntity")] public ulong BottomEntity;
    [JsonPropertyName("ExpanderEntity")] public ulong ExpanderEntity;
    [JsonPropertyName("PrevEntity")] public ulong PrevEntity;
    [JsonPropertyName("NextEntity")] public ulong NextEntity;
}

/// <summary><c>cuo:action/toggle-war-mode</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct ToggleWarModeAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/toggle-war-mode";
}

/// <summary><c>cuo:ui/topbar-button</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct TopBarButton
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/topbar-button";
}

/// <summary><c>cuo:ui/topbar-bg</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct TopBarDragHandle
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/topbar-bg";
}

/// <summary><c>cuo:ui/topbar-full</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct TopBarFull
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/topbar-full";
}

/// <summary>Nested payload type (<c>ClassicUO.Ecs.Modding.TownInfoDto</c>).</summary>
public partial struct TownInfoDto
{
    [JsonPropertyName("Index")] public byte Index;
    [JsonPropertyName("Name")] public string Name;
    [JsonPropertyName("Building")] public string Building;
    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
    [JsonPropertyName("Map")] public uint Map;
    [JsonPropertyName("ClilocDescription")] public uint ClilocDescription;
}

/// <summary><c>cuo:gump/trade</c></summary>
public partial struct TradeWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/trade";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("Id1")] public uint Id1;
    [JsonPropertyName("Id2")] public uint Id2;
    [JsonPropertyName("ImAccepting")] public bool ImAccepting;
    [JsonPropertyName("HeIsAccepting")] public bool HeIsAccepting;
    [JsonPropertyName("IsNew")] public bool IsNew;
}

/// <summary><c>cuo:ui/button</c></summary>
public partial struct UOButton
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/button";

    [JsonPropertyName("Normal")] public ushort Normal;
    [JsonPropertyName("Pressed")] public ushort Pressed;
    [JsonPropertyName("Over")] public ushort Over;
}

/// <summary><c>cuo:ui/contains-by-bounds</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiContainsByBounds
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/contains-by-bounds";
}

/// <summary><c>cuo:ui/custom</c></summary>
public partial struct UiCustomDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/custom";

    [JsonPropertyName("Kind")] public byte Kind;
    [JsonPropertyName("AssetId")] public uint AssetId;
    [JsonPropertyName("HueX")] public float HueX;
    [JsonPropertyName("HueY")] public float HueY;
    [JsonPropertyName("HueZ")] public float HueZ;
}

/// <summary><c>cuo:ui/hover-tint</c></summary>
public partial struct UiHoverTint
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/hover-tint";

    [JsonPropertyName("Normal")] public Color Normal;
    [JsonPropertyName("Hover")] public Color Hover;
}

/// <summary><c>cuo:ui/movable</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiMovable
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/movable";
}

/// <summary><c>cuo:ui/movable-no-drag</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiMovableNoDrag
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/movable-no-drag";
}

/// <summary><c>cuo:ui/name</c></summary>
public partial struct UiName
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/name";

    [JsonPropertyName("Value")] public string Value;
}

/// <summary><c>cuo:ui/no-blur</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiNoBlur
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/no-blur";
}

/// <summary><c>cuo:ui/no-right-click-close</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiNoRightClickClose
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/no-right-click-close";
}

/// <summary><c>cuo:ui/no-window-drag</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiNoWindowDrag
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/no-window-drag";
}

/// <summary><c>cuo:ui/popup</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct UiPopup
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/popup";
}

/// <summary>Nested payload type (<c>TinyEcs.Bevy.UI.UiRect</c>).</summary>
public partial struct UiRect
{
    [JsonPropertyName("Left")] public Val Left;
    [JsonPropertyName("Right")] public Val Right;
    [JsonPropertyName("Top")] public Val Top;
    [JsonPropertyName("Bottom")] public Val Bottom;
}

/// <summary><c>cuo:ui/resizable</c></summary>
public partial struct UiResizable
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/resizable";

    [JsonPropertyName("MinW")] public float MinW;
    [JsonPropertyName("MinH")] public float MinH;
    [JsonPropertyName("MaxW")] public float MaxW;
    [JsonPropertyName("MaxH")] public float MaxH;
    [JsonPropertyName("Grip")] public float Grip;
}

/// <summary><c>cuo:ui/scrollbar</c></summary>
public partial struct UiScrollbar
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/scrollbar";

    [JsonPropertyName("Width")] public float Width;
    /// <summary>enum ScrollbarStyle (0=Uo, 1=Flat)</summary>
    [JsonPropertyName("Style")] public ScrollbarStyle Style;
}

/// <summary><c>cuo:ui/surface</c></summary>
public partial struct UiSurfaceDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/surface";

    [JsonPropertyName("W")] public float W;
    [JsonPropertyName("H")] public float H;
}

/// <summary><c>cuo:ui/tooltip</c></summary>
public partial struct UiTooltip
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ui/tooltip";

    [JsonPropertyName("Text")] public string Text;
    [JsonPropertyName("MaxWidth")] public int MaxWidth;
}

/// <summary><c>cuo:action/use-skill</c></summary>
public partial struct UseSkillAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/use-skill";

    [JsonPropertyName("Id")] public int Id;
}

/// <summary>Nested payload type (<c>TinyEcs.Bevy.UI.Val</c>).</summary>
public partial struct Val
{
    /// <summary>enum ValType (0=Auto, 1=Px, 2=Percent, 3=Grow)</summary>
    [JsonPropertyName("Type")] public ValType Type;
    [JsonPropertyName("Value")] public float Value;
    /// <remarks>Host-computed: written by the host, ignored when a mod sets it.</remarks>
    [JsonPropertyName("IsAuto")] public bool IsAuto;
}

/// <remarks><c>TinyEcs.Bevy.UI.ValType</c> — crosses the boundary as a number.</remarks>
public enum ValType : byte
{
    Auto = 0,
    Px = 1,
    Percent = 2,
    Grow = 3,
}

/// <summary><c>cuo:gump/vendor</c>
/// <para>Presence-only marker: the host always answers <c>{}</c> and ignores writes.</para>
/// </summary>
public partial struct VendorWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/vendor";
}

/// <summary><c>cuo:action/walk</c></summary>
public partial struct WalkAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/walk";

    [JsonPropertyName("Direction")] public byte Direction;
    [JsonPropertyName("Run")] public bool Run;
}

/// <summary><c>cuo:action/walk-to</c></summary>
public partial struct WalkToAction
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:action/walk-to";

    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
}

/// <summary><c>cuo:gump/worldmap</c>
/// <para>Zero-size tag: its payload is <c>{}</c> in both directions.</para>
/// </summary>
public partial struct WorldMapWindow
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:gump/worldmap";
}

/// <summary><c>cuo:ent/world-position</c></summary>
public partial struct WorldPosition
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:ent/world-position";

    [JsonPropertyName("X")] public ushort X;
    [JsonPropertyName("Y")] public ushort Y;
    [JsonPropertyName("Z")] public sbyte Z;
}

/// <summary><c>cuo:input/world-single-click</c></summary>
public partial struct WorldSingleClickDto
{
    /// <summary>The registry type-path this payload belongs to.</summary>
    public const string Path = "cuo:input/world-single-click";

    [JsonPropertyName("Serial")] public uint Serial;
    [JsonPropertyName("AtMs")] public ulong AtMs;
}

/// <summary>Source-gen JSON context for every generated payload type, so NativeAOT
/// mods (de)serialize them without reflection. <c>IncludeFields</c> mirrors the host's
/// <c>ModJsonContext</c>: these shapes are public fields, not properties.</summary>
[JsonSourceGenerationOptions(IncludeFields = true)]
[JsonSerializable(typeof(AlignItems))]
[JsonSerializable(typeof(Amount))]
[JsonSerializable(typeof(BackgroundColor))]
[JsonSerializable(typeof(BookWindow))]
[JsonSerializable(typeof(BorderRadius))]
[JsonSerializable(typeof(BuffGumpUI))]
[JsonSerializable(typeof(BulletinBoardWindow))]
[JsonSerializable(typeof(CastSpellAction))]
[JsonSerializable(typeof(CharCreationScene))]
[JsonSerializable(typeof(CharInfoDto))]
[JsonSerializable(typeof(CharacterSelectionDto))]
[JsonSerializable(typeof(CharacterSelectionScene))]
[JsonSerializable(typeof(Color))]
[JsonSerializable(typeof(CombatBookWindow))]
[JsonSerializable(typeof(ContainedInDto))]
[JsonSerializable(typeof(ContainedInto))]
[JsonSerializable(typeof(ContainerClosedEvent))]
[JsonSerializable(typeof(ContainerOpenedEvent))]
[JsonSerializable(typeof(ContainerSlotPosition))]
[JsonSerializable(typeof(ContainerWindow))]
[JsonSerializable(typeof(ContextMenuEntry))]
[JsonSerializable(typeof(ContextMenuEvent))]
[JsonSerializable(typeof(ContextMenuReplyAction))]
[JsonSerializable(typeof(Direction))]
[JsonSerializable(typeof(Display))]
[JsonSerializable(typeof(DoubleClickAction))]
[JsonSerializable(typeof(DropAction))]
[JsonSerializable(typeof(EditableText))]
[JsonSerializable(typeof(EntityName))]
[JsonSerializable(typeof(EntityPropertiesDto))]
[JsonSerializable(typeof(EquipAction))]
[JsonSerializable(typeof(EquipmentSlotsDto))]
[JsonSerializable(typeof(Facing))]
[JsonSerializable(typeof(Flags))]
[JsonSerializable(typeof(FlexDirection))]
[JsonSerializable(typeof(FocusedInput))]
[JsonSerializable(typeof(GameContextDto))]
[JsonSerializable(typeof(GameScene))]
[JsonSerializable(typeof(GameStateDto))]
[JsonSerializable(typeof(GlobalZIndex))]
[JsonSerializable(typeof(GrabbedItem))]
[JsonSerializable(typeof(Graphic))]
[JsonSerializable(typeof(GridContainerWindow))]
[JsonSerializable(typeof(GridLootWindow))]
[JsonSerializable(typeof(GumpCloseAction))]
[JsonSerializable(typeof(GumpReplyAction))]
[JsonSerializable(typeof(GumpTextEntry))]
[JsonSerializable(typeof(HealthBarWindow))]
[JsonSerializable(typeof(Hits))]
[JsonSerializable(typeof(HostHotkeyDto))]
[JsonSerializable(typeof(HostHotkeysDto))]
[JsonSerializable(typeof(HouseDesignWindow))]
[JsonSerializable(typeof(Hue))]
[JsonSerializable(typeof(Interaction))]
[JsonSerializable(typeof(IsContainer))]
[JsonSerializable(typeof(IsMulti))]
[JsonSerializable(typeof(IsTopBar))]
[JsonSerializable(typeof(Items))]
[JsonSerializable(typeof(JournalWindow))]
[JsonSerializable(typeof(JustifyContent))]
[JsonSerializable(typeof(KeyboardInputDto))]
[JsonSerializable(typeof(Layer))]
[JsonSerializable(typeof(LocalTargetResultEvent))]
[JsonSerializable(typeof(LoginErrorInfo))]
[JsonSerializable(typeof(LoginErrorScene))]
[JsonSerializable(typeof(LoginErrorsInfoEvent))]
[JsonSerializable(typeof(LoginScene))]
[JsonSerializable(typeof(LogoutGumpWindow))]
[JsonSerializable(typeof(Mana))]
[JsonSerializable(typeof(MapWindow))]
[JsonSerializable(typeof(MaskedText))]
[JsonSerializable(typeof(MenuGumpWindow))]
[JsonSerializable(typeof(MessageBoxWindow))]
[JsonSerializable(typeof(MiniMapWindow))]
[JsonSerializable(typeof(MobAnimation))]
[JsonSerializable(typeof(MobStepDto))]
[JsonSerializable(typeof(MobileStepsDto))]
[JsonSerializable(typeof(Mobiles))]
[JsonSerializable(typeof(ModChatMessage))]
[JsonSerializable(typeof(ModClicked))]
[JsonSerializable(typeof(ModCounter))]
[JsonSerializable(typeof(ModEntity))]
[JsonSerializable(typeof(ModHotkeyBinding))]
[JsonSerializable(typeof(ModHotkeyBindingsDto))]
[JsonSerializable(typeof(ModHotkeyFired))]
[JsonSerializable(typeof(ModHovered))]
[JsonSerializable(typeof(ModMoveRequest))]
[JsonSerializable(typeof(ModRightClicked))]
[JsonSerializable(typeof(ModState))]
[JsonSerializable(typeof(MouseInputDto))]
[JsonSerializable(typeof(NetworkSerial))]
[JsonSerializable(typeof(Node))]
[JsonSerializable(typeof(Notoriety))]
[JsonSerializable(typeof(NotorietyFlag))]
[JsonSerializable(typeof(OnLoginRequest))]
[JsonSerializable(typeof(OpenDoorAction))]
[JsonSerializable(typeof(OplLineDto))]
[JsonSerializable(typeof(OptionsWindow))]
[JsonSerializable(typeof(Overflow))]
[JsonSerializable(typeof(PaperdollWindow))]
[JsonSerializable(typeof(PartyDto))]
[JsonSerializable(typeof(PartyInviteWindow))]
[JsonSerializable(typeof(PartyManifestWindow))]
[JsonSerializable(typeof(PartyMemberDto))]
[JsonSerializable(typeof(PickupAction))]
[JsonSerializable(typeof(Player))]
[JsonSerializable(typeof(PlayerBuffDto))]
[JsonSerializable(typeof(PlayerBuffsDto))]
[JsonSerializable(typeof(PlayerData))]
[JsonSerializable(typeof(PlayerSkillDto))]
[JsonSerializable(typeof(PlayerSkillsDto))]
[JsonSerializable(typeof(PlayerStepDto))]
[JsonSerializable(typeof(PlayerStepsDto))]
[JsonSerializable(typeof(PositionType))]
[JsonSerializable(typeof(ProfileWindow))]
[JsonSerializable(typeof(PromptOpenedEvent))]
[JsonSerializable(typeof(PromptReplyAction))]
[JsonSerializable(typeof(RaceType))]
[JsonSerializable(typeof(RacialBookWindow))]
[JsonSerializable(typeof(RenameAction))]
[JsonSerializable(typeof(RequestContextMenuAction))]
[JsonSerializable(typeof(RequestPropertiesAction))]
[JsonSerializable(typeof(RequestSkillsAction))]
[JsonSerializable(typeof(RequestStatusAction))]
[JsonSerializable(typeof(RequestTargetAction))]
[JsonSerializable(typeof(SayAction))]
[JsonSerializable(typeof(ScrollPosition))]
[JsonSerializable(typeof(ScrollbarStyle))]
[JsonSerializable(typeof(ServerFlags))]
[JsonSerializable(typeof(ServerGumpButtonDto))]
[JsonSerializable(typeof(ServerGumpClosedEvent))]
[JsonSerializable(typeof(ServerGumpDto))]
[JsonSerializable(typeof(ServerGumpOpenedEvent))]
[JsonSerializable(typeof(ServerGumpSwitchDto))]
[JsonSerializable(typeof(ServerGumpTextEntryDto))]
[JsonSerializable(typeof(ServerInfo))]
[JsonSerializable(typeof(ServerSelectionInfoEvent))]
[JsonSerializable(typeof(ServerSelectionScene))]
[JsonSerializable(typeof(SingleClickAction))]
[JsonSerializable(typeof(SkillsWindow))]
[JsonSerializable(typeof(SpellBookType))]
[JsonSerializable(typeof(SpellbookDto))]
[JsonSerializable(typeof(SpellbookWindow))]
[JsonSerializable(typeof(SpellbooksDto))]
[JsonSerializable(typeof(SplitMenuWindow))]
[JsonSerializable(typeof(Stamina))]
[JsonSerializable(typeof(StatLockButton))]
[JsonSerializable(typeof(StatLocks))]
[JsonSerializable(typeof(StatusBarWindow))]
[JsonSerializable(typeof(TargetCancelAction))]
[JsonSerializable(typeof(TargetLocationAction))]
[JsonSerializable(typeof(TargetObjectAction))]
[JsonSerializable(typeof(TargetingState))]
[JsonSerializable(typeof(Text))]
[JsonSerializable(typeof(TextCaretDto))]
[JsonSerializable(typeof(TextClipboardActionDto))]
[JsonSerializable(typeof(TextColor))]
[JsonSerializable(typeof(TextCompletionDto))]
[JsonSerializable(typeof(TextCompletionPickDto))]
[JsonSerializable(typeof(TextCompletionStateDto))]
[JsonSerializable(typeof(TextFont))]
[JsonSerializable(typeof(TextHue))]
[JsonSerializable(typeof(TextInput))]
[JsonSerializable(typeof(TextSpan))]
[JsonSerializable(typeof(TextSpans))]
[JsonSerializable(typeof(TextWrap))]
[JsonSerializable(typeof(TextWrapKind))]
[JsonSerializable(typeof(Time))]
[JsonSerializable(typeof(TipNoticeWindow))]
[JsonSerializable(typeof(ToggleWarModeAction))]
[JsonSerializable(typeof(TopBarButton))]
[JsonSerializable(typeof(TopBarDragHandle))]
[JsonSerializable(typeof(TopBarFull))]
[JsonSerializable(typeof(TownInfoDto))]
[JsonSerializable(typeof(TradeWindow))]
[JsonSerializable(typeof(UOButton))]
[JsonSerializable(typeof(UiContainsByBounds))]
[JsonSerializable(typeof(UiCustomDto))]
[JsonSerializable(typeof(UiHoverTint))]
[JsonSerializable(typeof(UiMovable))]
[JsonSerializable(typeof(UiMovableNoDrag))]
[JsonSerializable(typeof(UiName))]
[JsonSerializable(typeof(UiNoBlur))]
[JsonSerializable(typeof(UiNoRightClickClose))]
[JsonSerializable(typeof(UiNoWindowDrag))]
[JsonSerializable(typeof(UiPopup))]
[JsonSerializable(typeof(UiRect))]
[JsonSerializable(typeof(UiResizable))]
[JsonSerializable(typeof(UiScrollbar))]
[JsonSerializable(typeof(UiSurfaceDto))]
[JsonSerializable(typeof(UiTooltip))]
[JsonSerializable(typeof(UseSkillAction))]
[JsonSerializable(typeof(Val))]
[JsonSerializable(typeof(ValType))]
[JsonSerializable(typeof(VendorWindow))]
[JsonSerializable(typeof(WalkAction))]
[JsonSerializable(typeof(WalkToAction))]
[JsonSerializable(typeof(WorldMapWindow))]
[JsonSerializable(typeof(WorldPosition))]
[JsonSerializable(typeof(WorldSingleClickDto))]
public partial class ModTypesJsonContext : JsonSerializerContext;

/// <summary>Type → registry type-path, for the payload types registered under exactly
/// one path. Same value as the type's own <c>Path</c> constant, reachable generically.</summary>
public static class TypePaths
{
    private static readonly System.Collections.Generic.Dictionary<System.Type, string> Map = new()
    {
        [typeof(Amount)] = "cuo:ent/amount",
        [typeof(BackgroundColor)] = "cuo:ui/bg-color",
        [typeof(BookWindow)] = "cuo:gump/book",
        [typeof(BorderRadius)] = "cuo:ui/border-radius",
        [typeof(BuffGumpUI)] = "cuo:gump/buff",
        [typeof(BulletinBoardWindow)] = "cuo:gump/bulletin-board",
        [typeof(CastSpellAction)] = "cuo:action/cast-spell",
        [typeof(CharCreationScene)] = "cuo:scene/character-creation",
        [typeof(CharacterSelectionDto)] = "cuo:scene/character-list",
        [typeof(CharacterSelectionScene)] = "cuo:scene/character-selection",
        [typeof(CombatBookWindow)] = "cuo:gump/combat-book",
        [typeof(ContainedInDto)] = "cuo:ent/container",
        [typeof(ContainedInto)] = "cuo:ent/contained-into",
        [typeof(ContainerClosedEvent)] = "cuo:gump/container-closed",
        [typeof(ContainerOpenedEvent)] = "cuo:gump/container-opened",
        [typeof(ContainerSlotPosition)] = "cuo:ent/slot-position",
        [typeof(ContainerWindow)] = "cuo:gump/container",
        [typeof(ContextMenuEvent)] = "cuo:gump/context-menu",
        [typeof(ContextMenuReplyAction)] = "cuo:action/context-menu-reply",
        [typeof(DoubleClickAction)] = "cuo:action/double-click",
        [typeof(DropAction)] = "cuo:action/drop",
        [typeof(EditableText)] = "cuo:ui/editable-text",
        [typeof(EntityName)] = "cuo:ent/name",
        [typeof(EntityPropertiesDto)] = "cuo:ent/properties",
        [typeof(EquipAction)] = "cuo:action/equip",
        [typeof(EquipmentSlotsDto)] = "cuo:ent/equipment",
        [typeof(Facing)] = "cuo:ent/facing",
        [typeof(FocusedInput)] = "cuo:ui/focused-input",
        [typeof(GameContextDto)] = "cuo:game/context",
        [typeof(GameScene)] = "cuo:scene/game",
        [typeof(GameStateDto)] = "cuo:game/state",
        [typeof(GlobalZIndex)] = "cuo:ui/global-z",
        [typeof(GrabbedItem)] = "cuo:player/grabbed-item",
        [typeof(Graphic)] = "cuo:ent/graphic",
        [typeof(GridContainerWindow)] = "cuo:gump/grid-container",
        [typeof(GridLootWindow)] = "cuo:gump/grid-loot",
        [typeof(GumpCloseAction)] = "cuo:action/gump-close",
        [typeof(GumpReplyAction)] = "cuo:action/gump-reply",
        [typeof(HealthBarWindow)] = "cuo:gump/health-bar",
        [typeof(Hits)] = "cuo:player/hits",
        [typeof(HostHotkeysDto)] = "cuo:input/host-hotkeys",
        [typeof(HouseDesignWindow)] = "cuo:gump/house-design",
        [typeof(Hue)] = "cuo:ent/hue",
        [typeof(Interaction)] = "cuo:ui/interaction",
        [typeof(IsContainer)] = "cuo:ent/is-container",
        [typeof(IsMulti)] = "cuo:ent/is-multi",
        [typeof(IsTopBar)] = "cuo:ui/topbar-root",
        [typeof(Items)] = "cuo:ent/is-item",
        [typeof(JournalWindow)] = "cuo:gump/journal",
        [typeof(KeyboardInputDto)] = "cuo:input/keyboard",
        [typeof(LocalTargetResultEvent)] = "cuo:target/local-result",
        [typeof(LoginErrorScene)] = "cuo:scene/login-error",
        [typeof(LoginErrorsInfoEvent)] = "cuo:scene/login-error-info",
        [typeof(LoginScene)] = "cuo:scene/login",
        [typeof(LogoutGumpWindow)] = "cuo:gump/logout",
        [typeof(Mana)] = "cuo:player/mana",
        [typeof(MapWindow)] = "cuo:gump/map",
        [typeof(MaskedText)] = "cuo:ui/masked-text",
        [typeof(MenuGumpWindow)] = "cuo:gump/menu",
        [typeof(MessageBoxWindow)] = "cuo:gump/message-box",
        [typeof(MiniMapWindow)] = "cuo:gump/minimap",
        [typeof(MobAnimation)] = "cuo:ent/animation",
        [typeof(MobileStepsDto)] = "cuo:ent/mob-steps",
        [typeof(Mobiles)] = "cuo:ent/is-mobile",
        [typeof(ModChatMessage)] = "cuo:chat/message",
        [typeof(ModClicked)] = "cuo:ui/clicked",
        [typeof(ModCounter)] = "cuo:test/counter",
        [typeof(ModEntity)] = "cuo:mod/owned",
        [typeof(ModHotkeyBindingsDto)] = "cuo:input/mod-hotkeys",
        [typeof(ModHotkeyFired)] = "cuo:input/hotkey",
        [typeof(ModHovered)] = "cuo:ui/hovered",
        [typeof(ModMoveRequest)] = "cuo:player/move-request",
        [typeof(ModRightClicked)] = "cuo:ui/right-clicked",
        [typeof(ModState)] = "cuo:mod/state",
        [typeof(MouseInputDto)] = "cuo:input/mouse",
        [typeof(NetworkSerial)] = "cuo:ent/serial",
        [typeof(Node)] = "cuo:ui/node",
        [typeof(Notoriety)] = "cuo:ent/notoriety",
        [typeof(OnLoginRequest)] = "cuo:scene/login-request",
        [typeof(OpenDoorAction)] = "cuo:action/open-door",
        [typeof(OptionsWindow)] = "cuo:ui/options-window",
        [typeof(PaperdollWindow)] = "cuo:gump/paperdoll",
        [typeof(PartyDto)] = "cuo:player/party",
        [typeof(PartyInviteWindow)] = "cuo:gump/party-invite",
        [typeof(PartyManifestWindow)] = "cuo:gump/party-manifest",
        [typeof(PickupAction)] = "cuo:action/pickup",
        [typeof(Player)] = "cuo:player/player",
        [typeof(PlayerBuffsDto)] = "cuo:player/buffs",
        [typeof(PlayerData)] = "cuo:player/data",
        [typeof(PlayerSkillsDto)] = "cuo:player/skills",
        [typeof(PlayerStepsDto)] = "cuo:player/steps",
        [typeof(ProfileWindow)] = "cuo:gump/profile",
        [typeof(PromptOpenedEvent)] = "cuo:chat/prompt",
        [typeof(PromptReplyAction)] = "cuo:action/prompt-reply",
        [typeof(RacialBookWindow)] = "cuo:gump/racial-book",
        [typeof(RenameAction)] = "cuo:action/rename",
        [typeof(RequestContextMenuAction)] = "cuo:action/request-context-menu",
        [typeof(RequestPropertiesAction)] = "cuo:action/request-properties",
        [typeof(RequestSkillsAction)] = "cuo:action/request-skills",
        [typeof(RequestStatusAction)] = "cuo:action/request-status",
        [typeof(RequestTargetAction)] = "cuo:action/request-target",
        [typeof(SayAction)] = "cuo:action/say",
        [typeof(ScrollPosition)] = "cuo:ui/scroll",
        [typeof(ServerFlags)] = "cuo:ent/server-flags",
        [typeof(ServerGumpClosedEvent)] = "cuo:gump/server-closed",
        [typeof(ServerGumpDto)] = "cuo:gump/server",
        [typeof(ServerGumpOpenedEvent)] = "cuo:gump/server-opened",
        [typeof(ServerSelectionInfoEvent)] = "cuo:scene/server-list",
        [typeof(ServerSelectionScene)] = "cuo:scene/server-selection",
        [typeof(SingleClickAction)] = "cuo:action/single-click",
        [typeof(SkillsWindow)] = "cuo:gump/skills",
        [typeof(SpellbookWindow)] = "cuo:gump/spellbook",
        [typeof(SpellbooksDto)] = "cuo:player/spellbook",
        [typeof(SplitMenuWindow)] = "cuo:gump/split-menu",
        [typeof(Stamina)] = "cuo:player/stamina",
        [typeof(StatLockButton)] = "cuo:ui/stat-lock-button",
        [typeof(StatLocks)] = "cuo:player/stat-locks",
        [typeof(StatusBarWindow)] = "cuo:ui/statusbar-window",
        [typeof(TargetCancelAction)] = "cuo:action/target-cancel",
        [typeof(TargetLocationAction)] = "cuo:action/target-location",
        [typeof(TargetObjectAction)] = "cuo:action/target-object",
        [typeof(TargetingState)] = "cuo:target/state",
        [typeof(Text)] = "cuo:ui/text",
        [typeof(TextCaretDto)] = "cuo:ui/text-caret",
        [typeof(TextClipboardActionDto)] = "cuo:ui/text-clipboard-action",
        [typeof(TextColor)] = "cuo:ui/text-color",
        [typeof(TextCompletionDto)] = "cuo:ui/text-completion",
        [typeof(TextCompletionPickDto)] = "cuo:ui/text-completion-pick",
        [typeof(TextCompletionStateDto)] = "cuo:ui/text-completion-state",
        [typeof(TextFont)] = "cuo:ui/text-font",
        [typeof(TextHue)] = "cuo:ui/text-hue",
        [typeof(TextInput)] = "cuo:ui/text-input",
        [typeof(TextSpans)] = "cuo:ui/text-spans",
        [typeof(TextWrap)] = "cuo:ui/text-wrap",
        [typeof(Time)] = "cuo:engine/time",
        [typeof(TipNoticeWindow)] = "cuo:gump/tip-notice",
        [typeof(ToggleWarModeAction)] = "cuo:action/toggle-war-mode",
        [typeof(TopBarButton)] = "cuo:ui/topbar-button",
        [typeof(TopBarDragHandle)] = "cuo:ui/topbar-bg",
        [typeof(TopBarFull)] = "cuo:ui/topbar-full",
        [typeof(TradeWindow)] = "cuo:gump/trade",
        [typeof(UOButton)] = "cuo:ui/button",
        [typeof(UiContainsByBounds)] = "cuo:ui/contains-by-bounds",
        [typeof(UiCustomDto)] = "cuo:ui/custom",
        [typeof(UiHoverTint)] = "cuo:ui/hover-tint",
        [typeof(UiMovable)] = "cuo:ui/movable",
        [typeof(UiMovableNoDrag)] = "cuo:ui/movable-no-drag",
        [typeof(UiName)] = "cuo:ui/name",
        [typeof(UiNoBlur)] = "cuo:ui/no-blur",
        [typeof(UiNoRightClickClose)] = "cuo:ui/no-right-click-close",
        [typeof(UiNoWindowDrag)] = "cuo:ui/no-window-drag",
        [typeof(UiPopup)] = "cuo:ui/popup",
        [typeof(UiResizable)] = "cuo:ui/resizable",
        [typeof(UiScrollbar)] = "cuo:ui/scrollbar",
        [typeof(UiSurfaceDto)] = "cuo:ui/surface",
        [typeof(UiTooltip)] = "cuo:ui/tooltip",
        [typeof(UseSkillAction)] = "cuo:action/use-skill",
        [typeof(VendorWindow)] = "cuo:gump/vendor",
        [typeof(WalkAction)] = "cuo:action/walk",
        [typeof(WalkToAction)] = "cuo:action/walk-to",
        [typeof(WorldMapWindow)] = "cuo:gump/worldmap",
        [typeof(WorldPosition)] = "cuo:ent/world-position",
        [typeof(WorldSingleClickDto)] = "cuo:input/world-single-click",
    };

    public static string Of<T>() => Map[typeof(T)];

    /// <summary>Of&lt;T&gt; without the throw — the SDK turns a miss into a message naming T.</summary>
    public static bool TryOf<T>(out string path) => Map.TryGetValue(typeof(T), out path!);
}
