// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ModWorld.wit.Imports.cuo.modding.v0_1_0;

internal interface ITypesImports {

    /**
    * `cuo:player/hits`
    */

    internal struct Hits {
        internal ushort value;
        internal ushort maxValue;

        internal Hits(ushort value, ushort maxValue) {
            this.value = value;
            this.maxValue = maxValue;
        }
    }

    /**
    * `cuo:player/mana`
    */

    internal struct Mana {
        internal ushort value;
        internal ushort maxValue;

        internal Mana(ushort value, ushort maxValue) {
            this.value = value;
            this.maxValue = maxValue;
        }
    }

    /**
    * `cuo:player/stamina`
    */

    internal struct Stamina {
        internal ushort value;
        internal ushort maxValue;

        internal Stamina(ushort value, ushort maxValue) {
            this.value = value;
            this.maxValue = maxValue;
        }
    }

    /**
    * `cuo:player/data`
    */

    internal struct PlayerData {
        internal ushort str;
        internal ushort strMax;
        internal ushort dex;
        internal ushort dexMax;
        internal ushort @int;
        internal ushort intMax;
        internal short statsCap;
        internal byte followers;
        internal byte followersMax;
        internal ushort weight;
        internal ushort weightMax;
        internal uint gold;
        internal uint thithingPoints;
        internal ushort luck;
        internal short damageMin;
        internal short damageMax;
        internal short physicalRes;
        internal short fireRes;
        internal short coldRes;
        internal short poisonRes;
        internal short energyRes;
        internal bool isFemale;
        internal byte race;
        internal short maxPhysicalRes;
        internal short maxFireRes;
        internal short maxColdRes;
        internal short maxPoisonRes;
        internal short maxEnergyRes;
        internal short defenseChanceInc;
        internal short maxDefenseChanceInc;
        internal short hitChanceInc;
        internal short swingSpeedInc;
        internal short damageInc;
        internal short lowerReagentCost;
        internal short spellDamageInc;
        internal short fasterCastRecovery;
        internal short fasterCasting;
        internal short lowerManaCost;

        internal PlayerData(ushort str, ushort strMax, ushort dex, ushort dexMax, ushort @int, ushort intMax, short statsCap, byte followers, byte followersMax, ushort weight, ushort weightMax, uint gold, uint thithingPoints, ushort luck, short damageMin, short damageMax, short physicalRes, short fireRes, short coldRes, short poisonRes, short energyRes, bool isFemale, byte race, short maxPhysicalRes, short maxFireRes, short maxColdRes, short maxPoisonRes, short maxEnergyRes, short defenseChanceInc, short maxDefenseChanceInc, short hitChanceInc, short swingSpeedInc, short damageInc, short lowerReagentCost, short spellDamageInc, short fasterCastRecovery, short fasterCasting, short lowerManaCost) {
            this.str = str;
            this.strMax = strMax;
            this.dex = dex;
            this.dexMax = dexMax;
            this.@int = @int;
            this.intMax = intMax;
            this.statsCap = statsCap;
            this.followers = followers;
            this.followersMax = followersMax;
            this.weight = weight;
            this.weightMax = weightMax;
            this.gold = gold;
            this.thithingPoints = thithingPoints;
            this.luck = luck;
            this.damageMin = damageMin;
            this.damageMax = damageMax;
            this.physicalRes = physicalRes;
            this.fireRes = fireRes;
            this.coldRes = coldRes;
            this.poisonRes = poisonRes;
            this.energyRes = energyRes;
            this.isFemale = isFemale;
            this.race = race;
            this.maxPhysicalRes = maxPhysicalRes;
            this.maxFireRes = maxFireRes;
            this.maxColdRes = maxColdRes;
            this.maxPoisonRes = maxPoisonRes;
            this.maxEnergyRes = maxEnergyRes;
            this.defenseChanceInc = defenseChanceInc;
            this.maxDefenseChanceInc = maxDefenseChanceInc;
            this.hitChanceInc = hitChanceInc;
            this.swingSpeedInc = swingSpeedInc;
            this.damageInc = damageInc;
            this.lowerReagentCost = lowerReagentCost;
            this.spellDamageInc = spellDamageInc;
            this.fasterCastRecovery = fasterCastRecovery;
            this.fasterCasting = fasterCasting;
            this.lowerManaCost = lowerManaCost;
        }
    }

    /**
    * `cuo:ent/serial`
    */

    internal struct Serial {
        internal uint value;

        internal Serial(uint value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/graphic`
    */

    internal struct Graphic {
        internal ushort value;

        internal Graphic(ushort value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/hue`
    */

    internal struct Hue {
        internal ushort value;

        internal Hue(ushort value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/world-position`
    */

    internal struct WorldPosition {
        internal ushort x;
        internal ushort y;
        internal sbyte z;

        internal WorldPosition(ushort x, ushort y, sbyte z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }

    /**
    * `NotorietyFlag`
    */

    internal enum NotorietyFlag {
        UNKNOWN, INNOCENT, ALLY, GRAY, CRIMINAL, ENEMY, MURDERER, INVULNERABLE
    }

    /**
    * `cuo:ent/notoriety`
    */

    internal struct Notoriety {
        internal NotorietyFlag value;

        internal Notoriety(NotorietyFlag value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/name`
    */

    internal struct EntityName {
        internal string value;

        internal EntityName(string value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/amount`
    */

    internal struct Amount {
        internal int value;

        internal Amount(int value) {
            this.value = value;
        }
    }

    /**
    * `Display`
    */

    internal enum Display {
        FLEX, NONE
    }

    /**
    * `PositionType`
    */

    internal enum PositionType {
        RELATIVE, ABSOLUTE
    }

    /**
    * `Overflow`
    */

    internal enum Overflow {
        VISIBLE, CLIP, SCROLL
    }

    /**
    * `FlexDirection`
    */

    internal enum FlexDirection {
        ROW, COLUMN
    }

    /**
    * `JustifyContent`
    */

    internal enum JustifyContent {
        START, CENTER, END
    }

    /**
    * `AlignItems`
    */

    internal enum AlignItems {
        START, CENTER, END
    }

    /**
    * `ValType`
    */

    internal enum ValType {
        AUTO, PX, PERCENT, GROW
    }

    /**
    * `Val`
    */

    internal struct Val {
        internal ValType type;
        internal float value;

        internal Val(ValType type, float value) {
            this.type = type;
            this.value = value;
        }
    }

    /**
    * `UiRect`
    */

    internal struct UiRect {
        internal Val left;
        internal Val right;
        internal Val top;
        internal Val bottom;

        internal UiRect(Val left, Val right, Val top, Val bottom) {
            this.left = left;
            this.right = right;
            this.top = top;
            this.bottom = bottom;
        }
    }

    /**
    * `cuo:ui/node`
    */

    internal struct Node {
        internal Display display;
        internal PositionType positionType;
        internal Overflow overflow;
        internal FlexDirection flexDirection;
        internal JustifyContent justifyContent;
        internal AlignItems alignItems;
        internal Val width;
        internal Val height;
        internal Val minWidth;
        internal Val minHeight;
        internal Val maxWidth;
        internal Val maxHeight;
        internal Val left;
        internal Val top;
        internal Val right;
        internal Val bottom;
        internal UiRect padding;
        internal UiRect border;
        internal Val gap;
        internal float aspectRatio;

        internal Node(Display display, PositionType positionType, Overflow overflow, FlexDirection flexDirection, JustifyContent justifyContent, AlignItems alignItems, Val width, Val height, Val minWidth, Val minHeight, Val maxWidth, Val maxHeight, Val left, Val top, Val right, Val bottom, UiRect padding, UiRect border, Val gap, float aspectRatio) {
            this.display = display;
            this.positionType = positionType;
            this.overflow = overflow;
            this.flexDirection = flexDirection;
            this.justifyContent = justifyContent;
            this.alignItems = alignItems;
            this.width = width;
            this.height = height;
            this.minWidth = minWidth;
            this.minHeight = minHeight;
            this.maxWidth = maxWidth;
            this.maxHeight = maxHeight;
            this.left = left;
            this.top = top;
            this.right = right;
            this.bottom = bottom;
            this.padding = padding;
            this.border = border;
            this.gap = gap;
            this.aspectRatio = aspectRatio;
        }
    }

    /**
    * `cuo:ui/text`
    */

    internal struct Text {
        internal string value;

        internal Text(string value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ui/text-font`
    */

    internal struct TextFont {
        internal ushort fontId;
        internal ushort size;

        internal TextFont(ushort fontId, ushort size) {
            this.fontId = fontId;
            this.size = size;
        }
    }

    /**
    * `Color`
    */

    internal struct Color {
        internal float r;
        internal float g;
        internal float b;
        internal float a;

        internal Color(float r, float g, float b, float a) {
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }
    }

    /**
    * `cuo:ui/text-color`
    */

    internal struct TextColor {
        internal Color value;

        internal TextColor(Color value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ui/bg-color`
    */

    internal struct BackgroundColor {
        internal Color value;

        internal BackgroundColor(Color value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ui/border-radius`
    */

    internal struct BorderRadius {
        internal float topLeft;
        internal float topRight;
        internal float bottomLeft;
        internal float bottomRight;

        internal BorderRadius(float topLeft, float topRight, float bottomLeft, float bottomRight) {
            this.topLeft = topLeft;
            this.topRight = topRight;
            this.bottomLeft = bottomLeft;
            this.bottomRight = bottomRight;
        }
    }

    /**
    * `cuo:ecs/child-of`
    */

    internal struct ChildOf {
        internal ulong parent;

        internal ChildOf(ulong parent) {
            this.parent = parent;
        }
    }

    /**
    * `cuo:ui/global-z`
    */

    internal struct GlobalZIndex {
        internal int value;

        internal GlobalZIndex(int value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ui/interaction`
    */

    internal struct Interaction {
        internal byte state;

        internal Interaction(byte state) {
            this.state = state;
        }
    }

    /**
    * `cuo:input/mouse`
    */

    internal struct MouseInput {
        internal float x;
        internal float y;
        internal bool left;
        internal bool right;
        internal bool middle;
        internal bool x1;
        internal bool x2;
        internal float wheel;
        internal bool leftPressed;
        internal bool leftReleased;
        internal bool leftDouble;
        internal bool rightPressed;
        internal bool rightReleased;
        internal bool middlePressed;
        internal bool middleReleased;
        internal bool x1Pressed;
        internal bool x2Pressed;

        internal MouseInput(float x, float y, bool left, bool right, bool middle, bool x1, bool x2, float wheel, bool leftPressed, bool leftReleased, bool leftDouble, bool rightPressed, bool rightReleased, bool middlePressed, bool middleReleased, bool x1Pressed, bool x2Pressed) {
            this.x = x;
            this.y = y;
            this.left = left;
            this.right = right;
            this.middle = middle;
            this.x1 = x1;
            this.x2 = x2;
            this.wheel = wheel;
            this.leftPressed = leftPressed;
            this.leftReleased = leftReleased;
            this.leftDouble = leftDouble;
            this.rightPressed = rightPressed;
            this.rightReleased = rightReleased;
            this.middlePressed = middlePressed;
            this.middleReleased = middleReleased;
            this.x1Pressed = x1Pressed;
            this.x2Pressed = x2Pressed;
        }
    }

    /**
    * `cuo:input/keyboard`
    */

    internal struct KeyboardInput {
        internal int[] pressed;
        internal int[] pressedOnce;

        internal KeyboardInput(int[] pressed, int[] pressedOnce) {
            this.pressed = pressed;
            this.pressedOnce = pressedOnce;
        }
    }

    /**
    * `cuo:chat/message`
    */

    internal struct ChatMessage {
        internal uint serial;
        internal string text;
        internal string name;
        internal ushort hue;
        internal byte font;
        internal bool isUnicode;
        internal byte messageType;
        internal float time;
        internal byte kind;

        internal ChatMessage(uint serial, string text, string name, ushort hue, byte font, bool isUnicode, byte messageType, float time, byte kind) {
            this.serial = serial;
            this.text = text;
            this.name = name;
            this.hue = hue;
            this.font = font;
            this.isUnicode = isUnicode;
            this.messageType = messageType;
            this.time = time;
            this.kind = kind;
        }
    }

    /**
    * `cuo:chat/prompt`
    */

    internal struct PromptOpenedEvent {
        internal uint serial;
        internal uint promptId;
        internal bool unicode;
        internal string text;

        internal PromptOpenedEvent(uint serial, uint promptId, bool unicode, string text) {
            this.serial = serial;
            this.promptId = promptId;
            this.unicode = unicode;
            this.text = text;
        }
    }

    /**
    * `cuo:engine/time`
    */

    internal struct Time {
        internal float total;
        internal float frame;

        internal Time(float total, float frame) {
            this.total = total;
            this.frame = frame;
        }
    }

    /**
    * `cuo:ent/equipment`
    */

    internal struct EquipmentSlots {
        internal uint[] serials;

        internal EquipmentSlots(uint[] serials) {
            this.serials = serials;
        }
    }

    /**
    * `cuo:ent/facing`
    */

    internal struct Facing {
        internal byte value;

        internal Facing(byte value) {
            this.value = value;
        }
    }

    /**
    * `OplLineDto`
    */

    internal struct OplLine {
        internal int cliloc;
        internal string args;
        internal string text;

        internal OplLine(int cliloc, string args, string text) {
            this.cliloc = cliloc;
            this.args = args;
            this.text = text;
        }
    }

    /**
    * `cuo:ent/properties`
    */

    internal struct EntityProperties {
        internal uint serial;
        internal uint revision;
        internal string name;
        internal global::System.Collections.Generic.List<OplLine> lines;

        internal EntityProperties(uint serial, uint revision, string name, global::System.Collections.Generic.List<OplLine> lines) {
            this.serial = serial;
            this.revision = revision;
            this.name = name;
            this.lines = lines;
        }
    }

    /**
    * `cuo:ent/server-flags`
    */

    internal struct ServerFlags {
        internal byte value;

        internal ServerFlags(byte value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ent/slot-position`
    */

    internal struct ContainerSlotPosition {
        internal ushort x;
        internal ushort y;
        internal byte gridIndex;

        internal ContainerSlotPosition(ushort x, ushort y, byte gridIndex) {
            this.x = x;
            this.y = y;
            this.gridIndex = gridIndex;
        }
    }

    /**
    * `cuo:game/context`
    */

    internal struct GameContext {
        internal uint playerSerial;
        internal string playerName;
        internal int map;
        internal byte season;
        internal uint clientVersion;
        internal bool useOldStatusGump;

        internal GameContext(uint playerSerial, string playerName, int map, byte season, uint clientVersion, bool useOldStatusGump) {
            this.playerSerial = playerSerial;
            this.playerName = playerName;
            this.map = map;
            this.season = season;
            this.clientVersion = clientVersion;
            this.useOldStatusGump = useOldStatusGump;
        }
    }

    /**
    * `cuo:game/settings`
    */

    internal struct GameSettings {
        internal int gridLootType;
        internal bool skipEmptyCorpse;
        internal bool autoOpenCorpses;
        internal int autoOpenCorpseRange;
        internal int corpseOpenOptions;
        internal bool doubleClickToLootInsideContainers;
        internal bool holdShiftToSplitStack;
        internal bool relativeDragAndDropItems;
        internal ushort speechHue;
        internal bool alwaysRun;
        internal bool highlightGameObjects;

        internal GameSettings(int gridLootType, bool skipEmptyCorpse, bool autoOpenCorpses, int autoOpenCorpseRange, int corpseOpenOptions, bool doubleClickToLootInsideContainers, bool holdShiftToSplitStack, bool relativeDragAndDropItems, ushort speechHue, bool alwaysRun, bool highlightGameObjects) {
            this.gridLootType = gridLootType;
            this.skipEmptyCorpse = skipEmptyCorpse;
            this.autoOpenCorpses = autoOpenCorpses;
            this.autoOpenCorpseRange = autoOpenCorpseRange;
            this.corpseOpenOptions = corpseOpenOptions;
            this.doubleClickToLootInsideContainers = doubleClickToLootInsideContainers;
            this.holdShiftToSplitStack = holdShiftToSplitStack;
            this.relativeDragAndDropItems = relativeDragAndDropItems;
            this.speechHue = speechHue;
            this.alwaysRun = alwaysRun;
            this.highlightGameObjects = highlightGameObjects;
        }
    }

    /**
    * `cuo:game/state`
    */

    internal struct GameState {
        internal byte current;

        internal GameState(byte current) {
            this.current = current;
        }
    }

    /**
    * `cuo:gump/container`
    */

    internal struct ContainerWindow {
        internal uint serial;

        internal ContainerWindow(uint serial) {
            this.serial = serial;
        }
    }

    /**
    * `cuo:gump/container-closed`
    */

    internal struct ContainerClosedEvent {
        internal uint serial;
        internal bool userInitiated;

        internal ContainerClosedEvent(uint serial, bool userInitiated) {
            this.serial = serial;
            this.userInitiated = userInitiated;
        }
    }

    /**
    * `cuo:gump/container-opened`
    */

    internal struct ContainerOpenedEvent {
        internal uint serial;
        internal ushort graphic;

        internal ContainerOpenedEvent(uint serial, ushort graphic) {
            this.serial = serial;
            this.graphic = graphic;
        }
    }

    /**
    * `ContainerPositionDto`
    */

    internal struct ContainerPosition {
        internal uint serial;
        internal int x;
        internal int y;

        internal ContainerPosition(uint serial, int x, int y) {
            this.serial = serial;
            this.x = x;
            this.y = y;
        }
    }

    /**
    * `cuo:gump/container-positions`
    */

    internal struct ContainerPositions {
        internal global::System.Collections.Generic.List<ContainerPosition> saved;

        internal ContainerPositions(global::System.Collections.Generic.List<ContainerPosition> saved) {
            this.saved = saved;
        }
    }

    /**
    * `ContainerSlotAction`
    */

    internal enum ContainerSlotAction {
        ADD, REMOVE
    }

    /**
    * `cuo:gump/container-slot`
    */

    internal struct ContainerSlotEvent {
        internal ContainerSlotAction action;
        internal uint containerSerial;
        internal uint itemSerial;
        internal ushort graphic;
        internal ushort hue;
        internal ushort x;
        internal ushort y;
        internal ushort amount;

        internal ContainerSlotEvent(ContainerSlotAction action, uint containerSerial, uint itemSerial, ushort graphic, ushort hue, ushort x, ushort y, ushort amount) {
            this.action = action;
            this.containerSerial = containerSerial;
            this.itemSerial = itemSerial;
            this.graphic = graphic;
            this.hue = hue;
            this.x = x;
            this.y = y;
            this.amount = amount;
        }
    }

    /**
    * `cuo:gump/container-tag`
    */

    internal struct ContainerGumpTag {
        internal ushort graphic;
        internal ushort originalGraphic;
        internal float scale;
        internal int boundsX;
        internal int boundsY;
        internal int boundsW;
        internal int boundsH;

        internal ContainerGumpTag(ushort graphic, ushort originalGraphic, float scale, int boundsX, int boundsY, int boundsW, int boundsH) {
            this.graphic = graphic;
            this.originalGraphic = originalGraphic;
            this.scale = scale;
            this.boundsX = boundsX;
            this.boundsY = boundsY;
            this.boundsW = boundsW;
            this.boundsH = boundsH;
        }
    }

    /**
    * `ContextMenuEntry`
    */

    internal struct ContextMenuEntry {
        internal ushort index;
        internal int cliloc;
        internal string text;
        internal ushort flags;
        internal ushort hue;

        internal ContextMenuEntry(ushort index, int cliloc, string text, ushort flags, ushort hue) {
            this.index = index;
            this.cliloc = cliloc;
            this.text = text;
            this.flags = flags;
            this.hue = hue;
        }
    }

    /**
    * `cuo:gump/context-menu`
    */

    internal struct ContextMenuEvent {
        internal uint serial;
        internal global::System.Collections.Generic.List<ContextMenuEntry> entries;

        internal ContextMenuEvent(uint serial, global::System.Collections.Generic.List<ContextMenuEntry> entries) {
            this.serial = serial;
            this.entries = entries;
        }
    }

    /**
    * `cuo:gump/grid-container`
    */

    internal struct GridContainerWindow {
        internal uint serial;

        internal GridContainerWindow(uint serial) {
            this.serial = serial;
        }
    }

    /**
    * `cuo:gump/grid-loot`
    */

    internal struct GridLootWindow {
        internal uint corpseSerial;
        internal ulong corpseEntity;
        internal int contentSig;

        internal GridLootWindow(uint corpseSerial, ulong corpseEntity, int contentSig) {
            this.corpseSerial = corpseSerial;
            this.corpseEntity = corpseEntity;
            this.contentSig = contentSig;
        }
    }

    /**
    * `cuo:gump/health-bar`
    */

    internal struct HealthBarWindow {
        internal uint serial;
        internal bool isPlayer;
        internal bool outOfRange;
        internal bool hpRequested;
        internal bool wasDead;
        internal bool inParty;
        internal bool nameEditable;

        internal HealthBarWindow(uint serial, bool isPlayer, bool outOfRange, bool hpRequested, bool wasDead, bool inParty, bool nameEditable) {
            this.serial = serial;
            this.isPlayer = isPlayer;
            this.outOfRange = outOfRange;
            this.hpRequested = hpRequested;
            this.wasDead = wasDead;
            this.inParty = inParty;
            this.nameEditable = nameEditable;
        }
    }

    /**
    * `ServerGumpButtonDto`
    */

    internal struct ServerGumpButton {
        internal int id;
        internal float x;
        internal float y;
        internal float w;
        internal float h;

        internal ServerGumpButton(int id, float x, float y, float w, float h) {
            this.id = id;
            this.x = x;
            this.y = y;
            this.w = w;
            this.h = h;
        }
    }

    /**
    * `ServerGumpTextEntryDto`
    */

    internal struct ServerGumpTextEntry {
        internal ushort id;
        internal string text;

        internal ServerGumpTextEntry(ushort id, string text) {
            this.id = id;
            this.text = text;
        }
    }

    /**
    * `ServerGumpSwitchDto`
    */

    internal struct ServerGumpSwitch {
        internal uint id;
        internal bool @checked;
        internal bool isRadio;
        internal int group;

        internal ServerGumpSwitch(uint id, bool @checked, bool isRadio, int group) {
            this.id = id;
            this.@checked = @checked;
            this.isRadio = isRadio;
            this.group = group;
        }
    }

    /**
    * `cuo:gump/server`
    */

    internal struct ServerGump {
        internal uint serial;
        internal uint gumpId;
        internal int page;
        internal int x;
        internal int y;
        internal global::System.Collections.Generic.List<string> layout;
        internal global::System.Collections.Generic.List<string> texts;
        internal global::System.Collections.Generic.List<ServerGumpButton> buttons;
        internal global::System.Collections.Generic.List<ServerGumpTextEntry> textEntries;
        internal global::System.Collections.Generic.List<ServerGumpSwitch> switches;

        internal ServerGump(uint serial, uint gumpId, int page, int x, int y, global::System.Collections.Generic.List<string> layout, global::System.Collections.Generic.List<string> texts, global::System.Collections.Generic.List<ServerGumpButton> buttons, global::System.Collections.Generic.List<ServerGumpTextEntry> textEntries, global::System.Collections.Generic.List<ServerGumpSwitch> switches) {
            this.serial = serial;
            this.gumpId = gumpId;
            this.page = page;
            this.x = x;
            this.y = y;
            this.layout = layout;
            this.texts = texts;
            this.buttons = buttons;
            this.textEntries = textEntries;
            this.switches = switches;
        }
    }

    /**
    * `cuo:input/consume`
    */

    internal struct InputConsume {
        internal byte mouse;
        internal uint key;

        internal InputConsume(byte mouse, uint key) {
            this.mouse = mouse;
            this.key = key;
        }
    }

    /**
    * `HostHotkeyDto`
    */

    internal struct HostHotkey {
        internal int key;
        internal bool ctrl;
        internal bool shift;
        internal bool alt;
        internal string action;

        internal HostHotkey(int key, bool ctrl, bool shift, bool alt, string action) {
            this.key = key;
            this.ctrl = ctrl;
            this.shift = shift;
            this.alt = alt;
            this.action = action;
        }
    }

    /**
    * `cuo:input/host-hotkeys`
    */

    internal struct HostHotkeys {
        internal global::System.Collections.Generic.List<HostHotkey> hotkeys;

        internal HostHotkeys(global::System.Collections.Generic.List<HostHotkey> hotkeys) {
            this.hotkeys = hotkeys;
        }
    }

    /**
    * `cuo:input/hotkey`
    */

    internal struct ModHotkeyFired {
        internal string name;
        internal int key;
        internal int mouse;
        internal bool ctrl;
        internal bool shift;
        internal bool alt;
        internal bool fromMod;

        internal ModHotkeyFired(string name, int key, int mouse, bool ctrl, bool shift, bool alt, bool fromMod) {
            this.name = name;
            this.key = key;
            this.mouse = mouse;
            this.ctrl = ctrl;
            this.shift = shift;
            this.alt = alt;
            this.fromMod = fromMod;
        }
    }

    /**
    * `ModHotkeyBinding`
    */

    internal struct ModHotkeyBinding {
        internal string name;
        internal int key;
        internal int mouse;
        internal bool ctrl;
        internal bool shift;
        internal bool alt;
        internal bool consume;

        internal ModHotkeyBinding(string name, int key, int mouse, bool ctrl, bool shift, bool alt, bool consume) {
            this.name = name;
            this.key = key;
            this.mouse = mouse;
            this.ctrl = ctrl;
            this.shift = shift;
            this.alt = alt;
            this.consume = consume;
        }
    }

    /**
    * `cuo:input/mod-hotkeys`
    */

    internal struct ModHotkeyBindings {
        internal global::System.Collections.Generic.List<ModHotkeyBinding> bindings;
        internal bool consumeKeys;

        internal ModHotkeyBindings(global::System.Collections.Generic.List<ModHotkeyBinding> bindings, bool consumeKeys) {
            this.bindings = bindings;
            this.consumeKeys = consumeKeys;
        }
    }

    /**
    * `cuo:input/world-single-click`
    */

    internal struct WorldSingleClick {
        internal uint serial;
        internal ulong atMs;

        internal WorldSingleClick(uint serial, ulong atMs) {
            this.serial = serial;
            this.atMs = atMs;
        }
    }

    /**
    * `cuo:item/drop-sent`
    */

    internal struct ItemDropSent {
        internal uint serial;
        internal ushort x;
        internal ushort y;
        internal sbyte z;
        internal uint container;

        internal ItemDropSent(uint serial, ushort x, ushort y, sbyte z, uint container) {
            this.serial = serial;
            this.x = x;
            this.y = y;
            this.z = z;
            this.container = container;
        }
    }

    /**
    * `cuo:item/move-result`
    */

    internal struct ItemMoveResult {
        internal byte result;
        internal byte code;

        internal ItemMoveResult(byte result, byte code) {
            this.result = result;
            this.code = code;
        }
    }

    /**
    * `ModOptionDto`
    */

    internal struct ModOption {
        internal string key;
        internal string label;
        internal string group;
        internal string keywords;
        internal byte kind;
        internal int min;
        internal int max;
        internal int step;
        internal int @default;
        internal global::System.Collections.Generic.List<string> choices;

        internal ModOption(string key, string label, string group, string keywords, byte kind, int min, int max, int step, int @default, global::System.Collections.Generic.List<string> choices) {
            this.key = key;
            this.label = label;
            this.group = group;
            this.keywords = keywords;
            this.kind = kind;
            this.min = min;
            this.max = max;
            this.step = step;
            this.@default = @default;
            this.choices = choices;
        }
    }

    /**
    * `cuo:options/schema`
    */

    internal struct ModOptionsSchema {
        internal global::System.Collections.Generic.List<ModOption> options;

        internal ModOptionsSchema(global::System.Collections.Generic.List<ModOption> options) {
            this.options = options;
        }
    }

    /**
    * `PlayerBuffDto`
    */

    internal struct PlayerBuff {
        internal int type;
        internal ushort graphic;
        internal float expiresAt;
        internal string text;

        internal PlayerBuff(int type, ushort graphic, float expiresAt, string text) {
            this.type = type;
            this.graphic = graphic;
            this.expiresAt = expiresAt;
            this.text = text;
        }
    }

    /**
    * `cuo:player/buffs`
    */

    internal struct PlayerBuffs {
        internal global::System.Collections.Generic.List<PlayerBuff> buffs;

        internal PlayerBuffs(global::System.Collections.Generic.List<PlayerBuff> buffs) {
            this.buffs = buffs;
        }
    }

    /**
    * `Layer`
    */

    internal enum Layer {
        INVALID, ONE_HANDED, TWO_HANDED, SHOES, PANTS, SHIRT, HELMET, GLOVES, RING, TALISMAN, NECKLACE, HAIR, WAIST, TORSO, BRACELET, FACE, BEARD, TUNIC, EARRINGS, ARMS, CLOAK, BACKPACK, ROBE, SKIRT, LEGS, MOUNT, SHOP_BUY_RESTOCK, SHOP_BUY, SHOP_SELL, BANK
    }

    /**
    * `Vector2`
    */

    internal struct Vector2 {
        internal float x;
        internal float y;

        internal Vector2(float x, float y) {
            this.x = x;
            this.y = y;
        }
    }

    /**
    * `cuo:player/grabbed-item`
    */

    internal struct GrabbedItem {
        internal bool isActive;
        internal uint serial;
        internal ushort graphic;
        internal ushort hue;
        internal int amount;
        internal ulong sourceUiEntity;
        internal ushort originalGraphic;
        internal ushort originalHue;
        internal ushort originalAmount;
        internal ushort originalX;
        internal ushort originalY;
        internal sbyte originalZ;
        internal uint originalContainer;
        internal byte originalGridIndex;
        internal bool originalFromSlot;
        internal Layer originalLayer;
        internal bool pendingDrop;
        internal uint dropTargetSerial;
        internal bool failedDrop;
        internal Vector2 mouseOffset;

        internal GrabbedItem(bool isActive, uint serial, ushort graphic, ushort hue, int amount, ulong sourceUiEntity, ushort originalGraphic, ushort originalHue, ushort originalAmount, ushort originalX, ushort originalY, sbyte originalZ, uint originalContainer, byte originalGridIndex, bool originalFromSlot, Layer originalLayer, bool pendingDrop, uint dropTargetSerial, bool failedDrop, Vector2 mouseOffset) {
            this.isActive = isActive;
            this.serial = serial;
            this.graphic = graphic;
            this.hue = hue;
            this.amount = amount;
            this.sourceUiEntity = sourceUiEntity;
            this.originalGraphic = originalGraphic;
            this.originalHue = originalHue;
            this.originalAmount = originalAmount;
            this.originalX = originalX;
            this.originalY = originalY;
            this.originalZ = originalZ;
            this.originalContainer = originalContainer;
            this.originalGridIndex = originalGridIndex;
            this.originalFromSlot = originalFromSlot;
            this.originalLayer = originalLayer;
            this.pendingDrop = pendingDrop;
            this.dropTargetSerial = dropTargetSerial;
            this.failedDrop = failedDrop;
            this.mouseOffset = mouseOffset;
        }
    }

    /**
    * `PlayerSkillDto`
    */

    internal struct PlayerSkill {
        internal int index;
        internal ushort value;
        internal ushort @base;
        internal ushort cap;
        internal byte @lock;

        internal PlayerSkill(int index, ushort value, ushort @base, ushort cap, byte @lock) {
            this.index = index;
            this.value = value;
            this.@base = @base;
            this.cap = cap;
            this.@lock = @lock;
        }
    }

    /**
    * `cuo:player/skills`
    */

    internal struct PlayerSkills {
        internal bool hasData;
        internal global::System.Collections.Generic.List<PlayerSkill> skills;

        internal PlayerSkills(bool hasData, global::System.Collections.Generic.List<PlayerSkill> skills) {
            this.hasData = hasData;
            this.skills = skills;
        }
    }

    /**
    * `cuo:player/stat-locks`
    */

    internal struct StatLocks {
        internal byte str;
        internal byte dex;
        internal byte @int;

        internal StatLocks(byte str, byte dex, byte @int) {
            this.str = str;
            this.dex = dex;
            this.@int = @int;
        }
    }

    /**
    * `cuo:target/local-result`
    */

    internal struct LocalTargetResultEvent {
        internal ulong entity;
        internal uint serial;
        internal ushort graphic;
        internal ushort x;
        internal ushort y;
        internal sbyte z;
        internal bool cancelled;

        internal LocalTargetResultEvent(ulong entity, uint serial, ushort graphic, ushort x, ushort y, sbyte z, bool cancelled) {
            this.entity = entity;
            this.serial = serial;
            this.graphic = graphic;
            this.x = x;
            this.y = y;
            this.z = z;
            this.cancelled = cancelled;
        }
    }

    /**
    * `cuo:target/state`
    */

    internal struct TargetingState {
        internal bool isTargeting;
        internal byte mode;
        internal bool local;
        internal uint cursorId;
        internal byte cursorType;
        internal bool justTargeted;
        internal ushort multiId;
        internal short multiOffsetX;
        internal short multiOffsetY;
        internal short multiOffsetZ;
        internal ushort multiHue;
        internal ushort previewBuiltId;
        internal bool hasLocalResult;
        internal uint localSerial;
        internal ushort localGraphic;
        internal ushort localX;
        internal ushort localY;
        internal sbyte localZ;
        internal bool localCancelled;

        internal TargetingState(bool isTargeting, byte mode, bool local, uint cursorId, byte cursorType, bool justTargeted, ushort multiId, short multiOffsetX, short multiOffsetY, short multiOffsetZ, ushort multiHue, ushort previewBuiltId, bool hasLocalResult, uint localSerial, ushort localGraphic, ushort localX, ushort localY, sbyte localZ, bool localCancelled) {
            this.isTargeting = isTargeting;
            this.mode = mode;
            this.local = local;
            this.cursorId = cursorId;
            this.cursorType = cursorType;
            this.justTargeted = justTargeted;
            this.multiId = multiId;
            this.multiOffsetX = multiOffsetX;
            this.multiOffsetY = multiOffsetY;
            this.multiOffsetZ = multiOffsetZ;
            this.multiHue = multiHue;
            this.previewBuiltId = previewBuiltId;
            this.hasLocalResult = hasLocalResult;
            this.localSerial = localSerial;
            this.localGraphic = localGraphic;
            this.localX = localX;
            this.localY = localY;
            this.localZ = localZ;
            this.localCancelled = localCancelled;
        }
    }

    /**
    * `cuo:ui/border-color`
    */

    internal struct BorderColor {
        internal float r;
        internal float g;
        internal float b;
        internal float a;

        internal BorderColor(float r, float g, float b, float a) {
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }
    }

    /**
    * `cuo:ui/button`
    */

    internal struct UoButton {
        internal ushort normal;
        internal ushort pressed;
        internal ushort over;

        internal UoButton(ushort normal, ushort pressed, ushort over) {
            this.normal = normal;
            this.pressed = pressed;
            this.over = over;
        }
    }

    /**
    * `cuo:ui/computed`
    */

    internal struct ComputedNode {
        internal Vector2 size;
        internal Vector2 position;
        internal uint clayId;
        internal int paintOrder;

        internal ComputedNode(Vector2 size, Vector2 position, uint clayId, int paintOrder) {
            this.size = size;
            this.position = position;
            this.clayId = clayId;
            this.paintOrder = paintOrder;
        }
    }

    /**
    * `Vector3`
    */

    internal struct Vector3 {
        internal float x;
        internal float y;
        internal float z;

        internal Vector3(float x, float y, float z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }

    /**
    * `cuo:ui/container-item`
    */

    internal struct ContainerItemUi {
        internal ulong container;
        internal uint serial;
        internal Vector3 originalHue;
        internal Vector3 hoverHue;

        internal ContainerItemUi(ulong container, uint serial, Vector3 originalHue, Vector3 hoverHue) {
            this.container = container;
            this.serial = serial;
            this.originalHue = originalHue;
            this.hoverHue = hoverHue;
        }
    }

    /**
    * `cuo:ui/custom`
    */

    internal struct UiCustom {
        internal byte kind;
        internal uint assetId;
        internal float hueX;
        internal float hueY;
        internal float hueZ;
        internal bool stacked;

        internal UiCustom(byte kind, uint assetId, float hueX, float hueY, float hueZ, bool stacked) {
            this.kind = kind;
            this.assetId = assetId;
            this.hueX = hueX;
            this.hueY = hueY;
            this.hueZ = hueZ;
            this.stacked = stacked;
        }
    }

    /**
    * `cuo:ui/editable-text`
    */

    internal struct EditableText {
        internal bool multiline;

        internal EditableText(bool multiline) {
            this.multiline = multiline;
        }
    }

    /**
    * `cuo:ui/hover`
    */

    internal struct UiHover {
        internal bool over;

        internal UiHover(bool over) {
            this.over = over;
        }
    }

    /**
    * `cuo:ui/hover-tint`
    */

    internal struct UiHoverTint {
        internal Color normal;
        internal Color hover;

        internal UiHoverTint(Color normal, Color hover) {
            this.normal = normal;
            this.hover = hover;
        }
    }

    /**
    * `cuo:ui/name`
    */

    internal struct UiName {
        internal string value;

        internal UiName(string value) {
            this.value = value;
        }
    }

    /**
    * `cuo:ui/pick`
    */

    internal struct UiPick {
        internal ulong entity;
        internal ulong root;
        internal int paintOrder;
        internal float x;
        internal float y;

        internal UiPick(ulong entity, ulong root, int paintOrder, float x, float y) {
            this.entity = entity;
            this.root = root;
            this.paintOrder = paintOrder;
            this.x = x;
            this.y = y;
        }
    }

    /**
    * `cuo:ui/resizable`
    */

    internal struct UiResizable {
        internal float minW;
        internal float minH;
        internal float maxW;
        internal float maxH;
        internal float grip;
        internal float gripInset;
        internal bool wholePixels;

        internal UiResizable(float minW, float minH, float maxW, float maxH, float grip, float gripInset, bool wholePixels) {
            this.minW = minW;
            this.minH = minH;
            this.maxW = maxW;
            this.maxH = maxH;
            this.grip = grip;
            this.gripInset = gripInset;
            this.wholePixels = wholePixels;
        }
    }

    /**
    * `cuo:ui/right-click`
    */

    internal struct UiRightClick {
        internal float x;
        internal float y;

        internal UiRightClick(float x, float y) {
            this.x = x;
            this.y = y;
        }
    }

    /**
    * `cuo:ui/scroll`
    */

    internal struct ScrollPosition {
        internal float offsetX;
        internal float offsetY;

        internal ScrollPosition(float offsetX, float offsetY) {
            this.offsetX = offsetX;
            this.offsetY = offsetY;
        }
    }

    /**
    * `ScrollbarStyle`
    */

    internal enum ScrollbarStyle {
        UO, FLAT
    }

    /**
    * `cuo:ui/scrollbar`
    */

    internal struct UiScrollbar {
        internal float width;
        internal ScrollbarStyle style;

        internal UiScrollbar(float width, ScrollbarStyle style) {
            this.width = width;
            this.style = style;
        }
    }

    /**
    * `cuo:ui/stat-lock-button`
    */

    internal struct StatLockButton {
        internal byte stat;

        internal StatLockButton(byte stat) {
            this.stat = stat;
        }
    }

    /**
    * `cuo:ui/statusbar-window`
    */

    internal struct StatusBarWindow {
        internal float minimizeX;
        internal float minimizeY;

        internal StatusBarWindow(float minimizeX, float minimizeY) {
            this.minimizeX = minimizeX;
            this.minimizeY = minimizeY;
        }
    }

    /**
    * `cuo:ui/supersedes`
    */

    internal struct ModSupersedes {
        internal string feature;

        internal ModSupersedes(string feature) {
            this.feature = feature;
        }
    }

    /**
    * `cuo:ui/surface`
    */

    internal struct UiSurface {
        internal float w;
        internal float h;

        internal UiSurface(float w, float h) {
            this.w = w;
            this.h = h;
        }
    }

    /**
    * `cuo:ui/text-caret`
    */

    internal struct TextCaret {
        internal ulong entity;
        internal int cursor;
        internal int selectStart;
        internal int selectEnd;
        internal int line;
        internal int column;
        internal float screenX;
        internal float screenY;
        internal float rowHeight;

        internal TextCaret(ulong entity, int cursor, int selectStart, int selectEnd, int line, int column, float screenX, float screenY, float rowHeight) {
            this.entity = entity;
            this.cursor = cursor;
            this.selectStart = selectStart;
            this.selectEnd = selectEnd;
            this.line = line;
            this.column = column;
            this.screenX = screenX;
            this.screenY = screenY;
            this.rowHeight = rowHeight;
        }
    }

    /**
    * `cuo:ui/text-completion-state`
    */

    internal struct TextCompletionState {
        internal int selected;

        internal TextCompletionState(int selected) {
            this.selected = selected;
        }
    }

    /**
    * `cuo:ui/text-hue`
    */

    internal struct TextHue {
        internal ushort value;

        internal TextHue(ushort value) {
            this.value = value;
        }
    }

    /**
    * `TextSpan`
    */

    internal struct TextSpan {
        internal int start;
        internal int length;
        internal Color color;

        internal TextSpan(int start, int length, Color color) {
            this.start = start;
            this.length = length;
            this.color = color;
        }
    }

    /**
    * `cuo:ui/text-spans`
    */

    internal struct TextSpans {
        internal global::System.Collections.Generic.List<TextSpan> spans;

        internal TextSpans(global::System.Collections.Generic.List<TextSpan> spans) {
            this.spans = spans;
        }
    }

    /**
    * `TextWrapKind`
    */

    internal enum TextWrapKind {
        WORDS, NEWLINES, NONE
    }

    /**
    * `cuo:ui/text-wrap`
    */

    internal struct TextWrap {
        internal TextWrapKind kind;

        internal TextWrap(TextWrapKind kind) {
            this.kind = kind;
        }
    }

    /**
    * `cuo:ui/tooltip`
    */

    internal struct UiTooltip {
        internal string text;
        internal int maxWidth;

        internal UiTooltip(string text, int maxWidth) {
            this.text = text;
            this.maxWidth = maxWidth;
        }
    }

}
