// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ModWorld.wit.Imports.cuo.modding.v0_1_0;

internal interface IActionsImports {

    internal enum Direction {
        NORTH, NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST
    }

    internal enum SpeechKind {
        REGULAR, EMOTE, WHISPER, YELL, GUILD, ALLIANCE
    }

    internal enum LockState {
        UP, DOWN, LOCKED
    }

    internal enum Stat {
        STR, DEX, INT
    }

    internal enum Virtue {
        HONOR, SACRIFICE, VALOR
    }

    internal enum Ability {
        PRIMARY, SECONDARY
    }

    internal enum Window {
        PAPERDOLL, STATUS, JOURNAL, SKILLS, BACKPACK, WORLD_MAP, MINIMAP, OPTIONS, BUFFS, COMBAT_BOOK, PARTY, GUILD, QUEST, LOGOUT
    }

    internal struct Point {
        internal ushort x;
        internal ushort y;
        internal sbyte z;

        internal Point(ushort x, ushort y, sbyte z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }

    internal class Destination {
        internal readonly byte Tag;
        private readonly object? value;

        private Destination(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        internal static Destination Container(uint container) {
            return new Destination(Tags.Container, container);
        }

        internal static Destination ContainerAt((uint, ushort, ushort) containerAt) {
            return new Destination(Tags.ContainerAt, containerAt);
        }

        internal static Destination Ground(Point ground) {
            return new Destination(Tags.Ground, ground);
        }

        internal uint AsContainer
        {
            get
            {
                if (Tag == Tags.Container)
                return (uint)value!;
                else
                throw new global::System.ArgumentException("expected Container, got " + Tag);
            }
        }

        internal (uint, ushort, ushort) AsContainerAt
        {
            get
            {
                if (Tag == Tags.ContainerAt)
                return ((uint, ushort, ushort))value!;
                else
                throw new global::System.ArgumentException("expected ContainerAt, got " + Tag);
            }
        }

        internal Point AsGround
        {
            get
            {
                if (Tag == Tags.Ground)
                return (Point)value!;
                else
                throw new global::System.ArgumentException("expected Ground, got " + Tag);
            }
        }

        internal class Tags {
            internal const byte Container = 0;
            internal const byte ContainerAt = 1;
            internal const byte Ground = 2;
        }
    }

    internal static unsafe void DoubleClick(uint target)
    {
        ActionsImportsInterop.DoubleClickWasmInterop.wasmImportDoubleClick(unchecked((int)(target)));

    }

    internal static unsafe void SingleClick(uint target)
    {
        ActionsImportsInterop.SingleClickWasmInterop.wasmImportSingleClick(unchecked((int)(target)));

    }

    internal static unsafe void PickUp(uint item, ushort amount)
    {
        ActionsImportsInterop.PickUpWasmInterop.wasmImportPickUp(unchecked((int)(item)), amount);

    }

    internal static unsafe void Drop(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Destination to)
    {

        int lowered;
        int lowered6;
        int lowered7;
        int lowered8;

        switch (to.Tag) {
            case 0: {
                uint payload = to.AsContainer;

                lowered = 0;
                lowered6 = unchecked((int)(payload));
                lowered7 = 0;
                lowered8 = 0;

                break;
            }
            case 1: {
                (uint, ushort, ushort) payload2 = to.AsContainerAt;

                lowered = 1;
                lowered6 = unchecked((int)(payload2.Item1));
                lowered7 = payload2.Item2;
                lowered8 = payload2.Item3;

                break;
            }
            case 2: {
                global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Point payload5 = to.AsGround;

                lowered = 2;
                lowered6 = payload5.x;
                lowered7 = payload5.y;
                lowered8 = payload5.z;

                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + to);
        }
        ActionsImportsInterop.DropWasmInterop.wasmImportDrop(lowered, lowered6, lowered7, lowered8);

    }

    internal static unsafe void Equip(byte layer, uint mobile)
    {
        ActionsImportsInterop.EquipWasmInterop.wasmImportEquip(layer, unchecked((int)(mobile)));

    }

    internal static unsafe void MoveItem(uint item, ushort amount, global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Destination to)
    {

        int lowered;
        int lowered6;
        int lowered7;
        int lowered8;

        switch (to.Tag) {
            case 0: {
                uint payload = to.AsContainer;

                lowered = 0;
                lowered6 = unchecked((int)(payload));
                lowered7 = 0;
                lowered8 = 0;

                break;
            }
            case 1: {
                (uint, ushort, ushort) payload2 = to.AsContainerAt;

                lowered = 1;
                lowered6 = unchecked((int)(payload2.Item1));
                lowered7 = payload2.Item2;
                lowered8 = payload2.Item3;

                break;
            }
            case 2: {
                global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Point payload5 = to.AsGround;

                lowered = 2;
                lowered6 = payload5.x;
                lowered7 = payload5.y;
                lowered8 = payload5.z;

                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + to);
        }
        ActionsImportsInterop.MoveItemWasmInterop.wasmImportMoveItem(unchecked((int)(item)), amount, lowered, lowered6, lowered7, lowered8);

    }

    internal static unsafe void Wear(uint item, byte layer, uint mobile)
    {
        ActionsImportsInterop.WearWasmInterop.wasmImportWear(unchecked((int)(item)), layer, unchecked((int)(mobile)));

    }

    internal static unsafe void UseItemOn(uint item, uint target)
    {
        ActionsImportsInterop.UseItemOnWasmInterop.wasmImportUseItemOn(unchecked((int)(item)), unchecked((int)(target)));

    }

    internal static unsafe void EquipLastWeapon()
    {
        ActionsImportsInterop.EquipLastWeaponWasmInterop.wasmImportEquipLastWeapon();

    }

    internal static unsafe void Rename(uint mobile, string name)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(name);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());
        ActionsImportsInterop.RenameWasmInterop.wasmImportRename(unchecked((int)(mobile)), strPtr.ToInt32(), length);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void RequestProperties(uint target)
    {
        ActionsImportsInterop.RequestPropertiesWasmInterop.wasmImportRequestProperties(unchecked((int)(target)));

    }

    internal static unsafe void CloseContainer(uint container)
    {
        ActionsImportsInterop.CloseContainerWasmInterop.wasmImportCloseContainer(unchecked((int)(container)));

    }

    internal static unsafe void Walk(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Direction dir, bool run)
    {
        ActionsImportsInterop.WalkWasmInterop.wasmImportWalk((int)dir, (run ? 1 : 0));

    }

    internal static unsafe void WalkTo(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Point at)
    {
        ActionsImportsInterop.WalkToWasmInterop.wasmImportWalkTo(at.x, at.y, at.z);

    }

    internal static unsafe void CancelWalkTo()
    {
        ActionsImportsInterop.CancelWalkToWasmInterop.wasmImportCancelWalkTo();

    }

    internal static unsafe void OpenDoor()
    {
        ActionsImportsInterop.OpenDoorWasmInterop.wasmImportOpenDoor();

    }

    internal static unsafe void Resync()
    {
        ActionsImportsInterop.ResyncWasmInterop.wasmImportResync();

    }

    internal static unsafe void SetWarMode(bool on)
    {
        ActionsImportsInterop.SetWarModeWasmInterop.wasmImportSetWarMode((on ? 1 : 0));

    }

    internal static unsafe void Attack(uint mobile)
    {
        ActionsImportsInterop.AttackWasmInterop.wasmImportAttack(unchecked((int)(mobile)));

    }

    internal static unsafe void UseAbility(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Ability which)
    {
        ActionsImportsInterop.UseAbilityWasmInterop.wasmImportUseAbility((int)which);

    }

    internal static unsafe void ClearAbility()
    {
        ActionsImportsInterop.ClearAbilityWasmInterop.wasmImportClearAbility();

    }

    internal static unsafe void ToggleFlying()
    {
        ActionsImportsInterop.ToggleFlyingWasmInterop.wasmImportToggleFlying();

    }

    internal static unsafe void TargetObject(uint target)
    {
        ActionsImportsInterop.TargetObjectWasmInterop.wasmImportTargetObject(unchecked((int)(target)));

    }

    internal static unsafe void TargetLocation(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Point at, ushort graphic)
    {
        ActionsImportsInterop.TargetLocationWasmInterop.wasmImportTargetLocation(at.x, at.y, at.z, graphic);

    }

    internal static unsafe void TargetCancel()
    {
        ActionsImportsInterop.TargetCancelWasmInterop.wasmImportTargetCancel();

    }

    internal static unsafe void ClearTargetQueue()
    {
        ActionsImportsInterop.ClearTargetQueueWasmInterop.wasmImportClearTargetQueue();

    }

    internal static unsafe void RequestTarget(string prompt)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(prompt);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());
        ActionsImportsInterop.RequestTargetWasmInterop.wasmImportRequestTarget(strPtr.ToInt32(), length);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void CastSpell(ushort id)
    {
        ActionsImportsInterop.CastSpellWasmInterop.wasmImportCastSpell(id);

    }

    internal static unsafe void OpenSpellbook(byte kind)
    {
        ActionsImportsInterop.OpenSpellbookWasmInterop.wasmImportOpenSpellbook(kind);

    }

    internal static unsafe void UseSkill(ushort index)
    {
        ActionsImportsInterop.UseSkillWasmInterop.wasmImportUseSkill(index);

    }

    internal static unsafe void SetSkillLock(ushort index, global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.LockState state)
    {
        ActionsImportsInterop.SetSkillLockWasmInterop.wasmImportSetSkillLock(index, (int)state);

    }

    internal static unsafe void SetStatLock(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Stat which, global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.LockState state)
    {
        ActionsImportsInterop.SetStatLockWasmInterop.wasmImportSetStatLock((int)which, (int)state);

    }

    internal static unsafe void InvokeVirtue(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Virtue which)
    {
        ActionsImportsInterop.InvokeVirtueWasmInterop.wasmImportInvokeVirtue((int)which);

    }

    internal static unsafe void EmoteAction(string name)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(name);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());
        ActionsImportsInterop.EmoteActionWasmInterop.wasmImportEmoteAction(strPtr.ToInt32(), length);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void Say(string text, global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.SpeechKind kind, ushort? hue)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(text);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());

        int lowered;
        int lowered3;

        if (hue != null) {
            var payload2 = (ushort) hue;

            lowered = 1;
            lowered3 = payload2;

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.SayWasmInterop.wasmImportSay(strPtr.ToInt32(), length, (int)kind, lowered, lowered3);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void PartySay(string text, uint? to)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(text);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());

        int lowered;
        int lowered3;

        if (to != null) {
            var payload2 = (uint) to;

            lowered = 1;
            lowered3 = unchecked((int)(payload2));

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.PartySayWasmInterop.wasmImportPartySay(strPtr.ToInt32(), length, lowered, lowered3);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void GumpReply(uint gump, int button, uint[] switches, global::System.Collections.Generic.List<(ushort, string)> texts)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(switches, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var listPtr = gcHandle.AddrOfPinnedObject();
        cleanups.Add(()=> gcHandle.Free());

        void* address;
        if ((12 * texts.Count) < 1024) {
            var retArea = stackalloc uint[3 * texts.Count + 1];
            address = MemoryHelper.AlignStackPtr(retArea, 4);
        }
        else
        {
            var bufferSize = 12 * (nuint)texts.Count;
            address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
            cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
        }

        for (int index = 0; index < texts.Count; ++index) {
            (ushort, string) element = texts[index];
            int basePtr = (int)address + (index * 12);
            new global::System.Span<short>((void*)((byte*)basePtr + 0), 1)[0] = (short)element.Item1;

            var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(element.Item2);
            var length = utf8Bytes.Length;
            var gcHandle0 = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
            var strPtr = gcHandle0.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle0.Free());
            new global::System.Span<int>((void*)((byte*)basePtr + 8), 1)[0] = length;
            new global::System.Span<nint>((void*)((byte*)basePtr + 4), 1)[0] = (nint)strPtr.ToInt32();

        }
        ActionsImportsInterop.GumpReplyWasmInterop.wasmImportGumpReply(unchecked((int)(gump)), button, (nint)listPtr, (switches).Length, (int)address, texts.Count);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void GumpReply(uint gump, int button, global::System.Span<uint> switches, global::System.Collections.Generic.List<(ushort, string)> texts)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();
        fixed (void* listPtr = switches)
        {

            void* address;
            if ((12 * texts.Count) < 1024) {
                var retArea = stackalloc uint[3 * texts.Count + 1];
                address = MemoryHelper.AlignStackPtr(retArea, 4);
            }
            else
            {
                var bufferSize = 12 * (nuint)texts.Count;
                address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
                cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
            }

            for (int index = 0; index < texts.Count; ++index) {
                (ushort, string) element = texts[index];
                int basePtr = (int)address + (index * 12);
                new global::System.Span<short>((void*)((byte*)basePtr + 0), 1)[0] = (short)element.Item1;

                var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(element.Item2);
                var length = utf8Bytes.Length;
                var gcHandle0 = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
                var strPtr = gcHandle0.AddrOfPinnedObject();

                cleanups.Add(()=> gcHandle0.Free());
                new global::System.Span<int>((void*)((byte*)basePtr + 8), 1)[0] = length;
                new global::System.Span<nint>((void*)((byte*)basePtr + 4), 1)[0] = (nint)strPtr.ToInt32();

            }
            ActionsImportsInterop.GumpReplyWasmInterop.wasmImportGumpReply(unchecked((int)(gump)), button, (nint)listPtr, (switches).Length, (int)address, texts.Count);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
        }

    }

    internal static unsafe void GumpReply(uint gump, int button, global::System.Memory<uint> switches, global::System.Collections.Generic.List<(ushort, string)> texts)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();
        fixed (void* listPtr = switches.Span)
        {

            void* address;
            if ((12 * texts.Count) < 1024) {
                var retArea = stackalloc uint[3 * texts.Count + 1];
                address = MemoryHelper.AlignStackPtr(retArea, 4);
            }
            else
            {
                var bufferSize = 12 * (nuint)texts.Count;
                address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
                cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
            }

            for (int index = 0; index < texts.Count; ++index) {
                (ushort, string) element = texts[index];
                int basePtr = (int)address + (index * 12);
                new global::System.Span<short>((void*)((byte*)basePtr + 0), 1)[0] = (short)element.Item1;

                var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(element.Item2);
                var length = utf8Bytes.Length;
                var gcHandle0 = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
                var strPtr = gcHandle0.AddrOfPinnedObject();

                cleanups.Add(()=> gcHandle0.Free());
                new global::System.Span<int>((void*)((byte*)basePtr + 8), 1)[0] = length;
                new global::System.Span<nint>((void*)((byte*)basePtr + 4), 1)[0] = (nint)strPtr.ToInt32();

            }
            ActionsImportsInterop.GumpReplyWasmInterop.wasmImportGumpReply(unchecked((int)(gump)), button, (nint)listPtr, (switches).Length, (int)address, texts.Count);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
        }

    }

    internal static unsafe void GumpClose(uint gump)
    {
        ActionsImportsInterop.GumpCloseWasmInterop.wasmImportGumpClose(unchecked((int)(gump)));

    }

    internal static unsafe void RequestContextMenu(uint target)
    {
        ActionsImportsInterop.RequestContextMenuWasmInterop.wasmImportRequestContextMenu(unchecked((int)(target)));

    }

    internal static unsafe void ContextMenuReply(uint target, ushort index)
    {
        ActionsImportsInterop.ContextMenuReplyWasmInterop.wasmImportContextMenuReply(unchecked((int)(target)), index);

    }

    internal static unsafe void PromptReply(string text)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(text);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());
        ActionsImportsInterop.PromptReplyWasmInterop.wasmImportPromptReply(strPtr.ToInt32(), length);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void PromptCancel()
    {
        ActionsImportsInterop.PromptCancelWasmInterop.wasmImportPromptCancel();

    }

    internal static unsafe void MenuReply(uint menu, ushort menuId, ushort index, ushort graphic, ushort hue)
    {
        ActionsImportsInterop.MenuReplyWasmInterop.wasmImportMenuReply(unchecked((int)(menu)), menuId, index, graphic, hue);

    }

    internal static unsafe void TextEntryReply(uint dialog, byte parentId, byte button, string text, bool ok)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        var utf8Bytes = global::System.Text.Encoding.UTF8.GetBytes(text);
        var length = utf8Bytes.Length;
        var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(utf8Bytes, global::System.Runtime.InteropServices.GCHandleType.Pinned);
        var strPtr = gcHandle.AddrOfPinnedObject();

        cleanups.Add(()=> gcHandle.Free());
        ActionsImportsInterop.TextEntryReplyWasmInterop.wasmImportTextEntryReply(unchecked((int)(dialog)), parentId, button, strPtr.ToInt32(), length, (ok ? 1 : 0));

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void DyeReply(uint tub, ushort graphic, ushort hue)
    {
        ActionsImportsInterop.DyeReplyWasmInterop.wasmImportDyeReply(unchecked((int)(tub)), graphic, hue);

    }

    internal static unsafe void HelpRequest()
    {
        ActionsImportsInterop.HelpRequestWasmInterop.wasmImportHelpRequest();

    }

    internal static unsafe void PartyInvite()
    {
        ActionsImportsInterop.PartyInviteWasmInterop.wasmImportPartyInvite();

    }

    internal static unsafe void PartyRemove(uint? member)
    {

        int lowered;
        int lowered3;

        if (member != null) {
            var payload2 = (uint) member;

            lowered = 1;
            lowered3 = unchecked((int)(payload2));

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.PartyRemoveWasmInterop.wasmImportPartyRemove(lowered, lowered3);

    }

    internal static unsafe void PartyAccept(uint leader)
    {
        ActionsImportsInterop.PartyAcceptWasmInterop.wasmImportPartyAccept(unchecked((int)(leader)));

    }

    internal static unsafe void PartyDecline(uint leader)
    {
        ActionsImportsInterop.PartyDeclineWasmInterop.wasmImportPartyDecline(unchecked((int)(leader)));

    }

    internal static unsafe void PartySetLoot(bool shareable)
    {
        ActionsImportsInterop.PartySetLootWasmInterop.wasmImportPartySetLoot((shareable ? 1 : 0));

    }

    internal static unsafe void TradeAccept(uint container, bool accepted)
    {
        ActionsImportsInterop.TradeAcceptWasmInterop.wasmImportTradeAccept(unchecked((int)(container)), (accepted ? 1 : 0));

    }

    internal static unsafe void TradeCancel(uint container)
    {
        ActionsImportsInterop.TradeCancelWasmInterop.wasmImportTradeCancel(unchecked((int)(container)));

    }

    internal static unsafe void TradeSetGold(uint container, uint gold, uint platinum)
    {
        ActionsImportsInterop.TradeSetGoldWasmInterop.wasmImportTradeSetGold(unchecked((int)(container)), unchecked((int)(gold)), unchecked((int)(platinum)));

    }

    internal static unsafe void VendorBuy(uint vendor, global::System.Collections.Generic.List<(uint, ushort)> items)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        void* address;
        if ((8 * items.Count) < 1024) {
            var retArea = stackalloc uint[2 * items.Count + 1];
            address = MemoryHelper.AlignStackPtr(retArea, 4);
        }
        else
        {
            var bufferSize = 8 * (nuint)items.Count;
            address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
            cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
        }

        for (int index = 0; index < items.Count; ++index) {
            (uint, ushort) element = items[index];
            int basePtr = (int)address + (index * 8);
            new global::System.Span<int>((void*)((byte*)basePtr + 0), 1)[0] = unchecked((int)(element.Item1));
            new global::System.Span<short>((void*)((byte*)basePtr + 4), 1)[0] = (short)element.Item2;

        }
        ActionsImportsInterop.VendorBuyWasmInterop.wasmImportVendorBuy(unchecked((int)(vendor)), (int)address, items.Count);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void VendorSell(uint vendor, global::System.Collections.Generic.List<(uint, ushort)> items)
    {
        var cleanups = new global::System.Collections.Generic.List<global::System.Action>();

        void* address;
        if ((8 * items.Count) < 1024) {
            var retArea = stackalloc uint[2 * items.Count + 1];
            address = MemoryHelper.AlignStackPtr(retArea, 4);
        }
        else
        {
            var bufferSize = 8 * (nuint)items.Count;
            address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
            cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
        }

        for (int index = 0; index < items.Count; ++index) {
            (uint, ushort) element = items[index];
            int basePtr = (int)address + (index * 8);
            new global::System.Span<int>((void*)((byte*)basePtr + 0), 1)[0] = unchecked((int)(element.Item1));
            new global::System.Span<short>((void*)((byte*)basePtr + 4), 1)[0] = (short)element.Item2;

        }
        ActionsImportsInterop.VendorSellWasmInterop.wasmImportVendorSell(unchecked((int)(vendor)), (int)address, items.Count);

        foreach (var cleanup in cleanups)
        {
            cleanup();
        }

    }

    internal static unsafe void RequestStatus(uint? mobile)
    {

        int lowered;
        int lowered3;

        if (mobile != null) {
            var payload2 = (uint) mobile;

            lowered = 1;
            lowered3 = unchecked((int)(payload2));

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.RequestStatusWasmInterop.wasmImportRequestStatus(lowered, lowered3);

    }

    internal static unsafe void RequestSkills(uint? mobile)
    {

        int lowered;
        int lowered3;

        if (mobile != null) {
            var payload2 = (uint) mobile;

            lowered = 1;
            lowered3 = unchecked((int)(payload2));

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.RequestSkillsWasmInterop.wasmImportRequestSkills(lowered, lowered3);

    }

    internal static unsafe void OpenWindow(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Window w, uint? target)
    {

        int lowered;
        int lowered3;

        if (target != null) {
            var payload2 = (uint) target;

            lowered = 1;
            lowered3 = unchecked((int)(payload2));

        } else {

            lowered = 0;
            lowered3 = 0;

        }
        ActionsImportsInterop.OpenWindowWasmInterop.wasmImportOpenWindow((int)w, lowered, lowered3);

    }

    internal static unsafe void CloseWindow(global::ModWorld.wit.Imports.cuo.modding.v0_1_0.IActionsImports.Window w)
    {
        ActionsImportsInterop.CloseWindowWasmInterop.wasmImportCloseWindow((int)w);

    }

    internal static unsafe void SetViewRange(byte range)
    {
        ActionsImportsInterop.SetViewRangeWasmInterop.wasmImportSetViewRange(range);

    }

    internal static unsafe void Logout()
    {
        ActionsImportsInterop.LogoutWasmInterop.wasmImportLogout();

    }

}
