// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ModWorld.wit.Imports.tinyecs.modding.v0_1_0
{
    internal static class EcsImportsInterop {

        internal static class System
        {

            public static class ConstructorWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[constructor]system"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportConstructor(nint p0, int p1);
            }

            public static class AddCommandsWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.add-commands"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddCommands(int p0);
            }

            public static class AddQueryWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.add-query"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddQuery(int p0, nint p1, int p2);
            }

            public static class AddResWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.add-res"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddRes(int p0, nint p1, int p2);
            }

            public static class AddResMutWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.add-res-mut"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddResMut(int p0, nint p1, int p2);
            }

            public static class AddEventsWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.add-events"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddEvents(int p0, nint p1, int p2);
            }

            public static class AfterWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.after"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAfter(int p0, int p1);
            }

            public static class BeforeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]system.before"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportBefore(int p0, int p1);
            }

        }

        internal static class App
        {

            public static class AddSystemsWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]app.add-systems"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddSystems(int p0, int p1, nint p2, int p3);
            }

            public static class AddObserverWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]app.add-observer"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportAddObserver(int p0, int p1, nint p2, nint p3, int p4, int p5);
            }

        }

        internal static class Commands
        {

            public static class SpawnWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]commands.spawn"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern long wasmImportSpawn(int p0, nint p1, int p2);
            }

            public static class InsertWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]commands.insert"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportInsert(int p0, long p1, nint p2, int p3);
            }

            public static class RemoveWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]commands.remove"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportRemove(int p0, long p1, nint p2, int p3);
            }

            public static class DespawnWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]commands.despawn"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportDespawn(int p0, long p1);
            }

            public static class SendWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]commands.send"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSend(int p0, nint p1, int p2, nint p3, int p4);
            }

        }

        internal static class Query
        {

            public static class RowsWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]query.rows"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportRows(int p0, nint p1);
            }

            public static class SetWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]query.set"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSet(int p0, long p1, int p2, nint p3, int p4);
            }

        }

        internal static class Res
        {

            public static class GetWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]res.get"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportGet(int p0, nint p1);
            }

            public static class SetWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]res.set"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSet(int p0, nint p1, int p2);
            }

        }

        internal static class Events
        {

            public static class ReadWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("tinyecs:modding/ecs@0.1.0", EntryPoint = "[method]events.read"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportRead(int p0, nint p1);
            }

        }

    }
}
